(()=>{
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),panel=document.querySelector('#panel'),title=document.querySelector('#panelTitle'),panelText=document.querySelector('#panelText'),startBtn=document.querySelector('#start'),hint=document.querySelector('#hint'),hud=document.querySelector('#hud'),controls=document.querySelector('#controls'),pauseBtn=document.querySelector('#pause'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),coinsEl=document.querySelector('#coins'),hero=new Image();hero.src='../vladi-run/assets/vladi-runner.webp';
let W=innerWidth,H=innerHeight,dpr=1,state='menu',last=0,clock=0,player={x:2,row:0,hop:0},camera=0,score=0,coins=0,best=+(localStorage.getItem('vladiCrossyBest')||0),traffic=[],logs=[],coinRows=new Set(),stripe=0,toast='',toastAt=0,shake=0,moveLock=0,waterGraceUntil=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),mod=(a,b)=>(a%b+b)%b;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
function typeAt(row){const n=mod(row,12);if(n===3||n===4||n===8)return'road';if(n===6||n===7)return'river';return'grass'}
function rowData(row){if(typeAt(row)==='road'&&!traffic.some(t=>t.row===row)){const dir=(row%2?1:-1),colors=['#ed4b35','#ffd94d','#38a5e5','#f3f0dc','#a557dc'];for(let i=0;i<2;i++)traffic.push({row,x:dir>0?-1.2-i*3.4:6.2+i*3.4,dir,speed:rand(.55,.88),color:colors[Math.floor(Math.random()*colors.length)],type:Math.random()<.55?'car':'van'})}if(typeAt(row)==='river'&&!logs.some(t=>t.row===row)){const dir=row%2?1:-1,length=2,startX=clamp(player.x-length*.42,-.8,4-length*.42);logs.push({row,x:startX,dir,speed:rand(.25,.4),length})}if(typeAt(row)==='grass'&&row>3&&!coinRows.has(row)&&Math.random()<.09)coinRows.add(row)}
function spawnAhead(){for(let r=Math.floor(player.row)-2;r<Math.floor(player.row)+22;r++)rowData(r);traffic=traffic.filter(t=>t.row>player.row-5&&t.row<player.row+24);logs=logs.filter(t=>t.row>player.row-5&&t.row<player.row+24);for(const n of coinRows)if(n<player.row-5)coinRows.delete(n)}
function groundY(row){const depth=row-camera;return H*.79-depth*Math.max(27,Math.min(49,H*.052))}
function scaleAt(row){return clamp(1.08-(row-camera)*.032,.42,1.18)}
function cellSize(row){return Math.min(W*.188,256)*scaleAt(row)}
function rowShift(row){return-(row-camera)*Math.max(6,Math.min(34,H*.018))}
function rowWidth(row,kind){const unit=cellSize(row);return unit*(kind==='grass'?8.4:6.4)}
function cellX(x,row){return W/2+(x-2)*cellSize(row)+rowShift(row)}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#254c32');g.addColorStop(.38,'#3f823d');g.addColorStop(1,'#63b83a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#244e35';for(let i=0;i<10;i++){const x=(i*173+clock*3)%(W+90)-45,y=H*.08+(i%3)*H*.035;ctx.beginPath();ctx.moveTo(x,y+42);ctx.lineTo(x-42,y+9);ctx.lineTo(x-15,y+20);ctx.lineTo(x-30,y-3);ctx.lineTo(x+2,y+12);ctx.lineTo(x+28,y-10);ctx.lineTo(x+18,y+22);ctx.lineTo(x+50,y+1);ctx.lineTo(x+29,y+38);ctx.closePath();ctx.fill()}}
function rounded(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function polygon(points,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.closePath();ctx.fill()}
function topBand(row,y,step,kind,top,side){const width=rowWidth(row,kind),x=W/2+rowShift(row),skew=step*.36,half=width/2;polygon([[x-half,y-step*.5],[x+half,y-step*.5],[x+half+skew,y+step*.5],[x-half+skew,y+step*.5]],top);polygon([[x-half+skew,y+step*.5],[x+half+skew,y+step*.5],[x+half+skew,y+step*.5+step*.18],[x-half+skew,y+step*.5+step*.18]],side);ctx.strokeStyle='#1e402b44';ctx.lineWidth=1;for(let n=-3;n<=3;n++){const xx=x+n*cellSize(row);ctx.beginPath();ctx.moveTo(xx,y-step*.48);ctx.lineTo(xx+skew,y+step*.48);ctx.stroke()}}
function drawTree(x,y,s,row,variant=0){const w=cellSize(row)*.34,h=w*(1.15+variant*.12);ctx.save();ctx.fillStyle='#1b492e77';ctx.beginPath();ctx.ellipse(x+4*s,y+2*s,w*.72,w*.25,0,0,6.3);ctx.fill();polygon([[x-w*.11,y-h*.42],[x+w*.12,y-h*.42],[x+w*.12,y],[x-w*.11,y]],'#78502b');polygon([[x-w*.48,y-h*.83],[x+w*.29,y-h*.83],[x+w*.29,y-h*.35],[x-w*.48,y-h*.35]],'#38802e');polygon([[x-w*.48,y-h*.83],[x-w*.23,y-h],[x+w*.52,y-h],[x+w*.29,y-h*.83]],'#77cb36');polygon([[x+w*.29,y-h*.83],[x+w*.52,y-h],[x+w*.52,y-h*.51],[x+w*.29,y-h*.35]],'#286d2b');polygon([[x-w*.3,y-h*.55],[x+w*.36,y-h*.55],[x+w*.36,y-h*.12],[x-w*.3,y-h*.12]],'#56a832');polygon([[x+w*.36,y-h*.55],[x+w*.53,y-h*.66],[x+w*.53,y-h*.27],[x+w*.36,y-h*.12]],'#347d2c');ctx.restore()}
function seeded(row,n){const a=Math.sin(row*127.1+n*311.7)*43758.5453;return a-Math.floor(a)}
function drawVehicle(t){const y=groundY(t.row),s=scaleAt(t.row),x=cellX(t.x,t.row),w=cellSize(t.row)*(t.type==='van'?1.15:.92),h=cellSize(t.row)*.58;ctx.save();ctx.translate(x,y);ctx.shadowColor='#11251d88';ctx.shadowBlur=8*s;ctx.shadowOffsetY=7*s;rounded(-w*.5,-h*.4,w,h*.8,4*s,t.color);ctx.shadowBlur=0;polygon([[-w*.4,-h*.34],[-w*.22,-h*.55],[w*.28,-h*.55],[w*.43,-h*.34]],'#f6f1da');rounded(-w*.23,-h*.34,w*.48,h*.25,3*s,'#213b46');rounded(-w*.37,h*.03,w*.74,h*.2,2*s,'#9edced');ctx.fillStyle='#191d1d';for(const q of [-.37,.27]){ctx.fillRect(w*q,-h*.43,w*.12,h*.21);ctx.fillRect(w*q,h*.22,w*.12,h*.21)}ctx.fillStyle='#fff6ca';ctx.fillRect(-w*.42,-h*.35,w*.12,h*.1);ctx.fillRect(w*.3,-h*.35,w*.12,h*.1);ctx.restore()}
function drawLog(t){const y=groundY(t.row),s=scaleAt(t.row),x=cellX(t.x,t.row),w=cellSize(t.row)*t.length,h=cellSize(t.row)*.32,skew=h*.5;ctx.save();ctx.shadowColor='#083d4777';ctx.shadowBlur=7*s;ctx.shadowOffsetY=5*s;polygon([[x-w/2,y-h*.25],[x+w/2,y-h*.25],[x+w/2+skew,y+h*.25],[x-w/2+skew,y+h*.25]],'#62371f');polygon([[x-w/2+skew,y+h*.25],[x+w/2+skew,y+h*.25],[x+w/2+skew,y+h*.58],[x-w/2+skew,y+h*.58]],'#482718');polygon([[x-w/2,y-h*.25],[x+w/2,y-h*.25],[x+w/2+skew,y+h*.25],[x-w/2+skew,y+h*.25]],'#a66835');ctx.shadowBlur=0;for(let k=0;k<t.length;k++){const cx=x-w/2+(k+.5)*(w/t.length);ctx.strokeStyle='#d19450';ctx.lineWidth=Math.max(1,2*s);ctx.beginPath();ctx.ellipse(cx,y,w/t.length*.36,h*.2,0,0,6.3);ctx.stroke()}ctx.restore()}
function drawRow(row){const y=groundY(row),s=scaleAt(row),step=Math.max(27,Math.min(49,H*.052));if(y<-step||y>H+step)return;const kind=typeAt(row);if(kind==='grass'){topBand(row,y,step,'grass',row%2?'#a2df39':'#8dd532','#4a8d31');for(let c=-1;c<=5;c++){const chance=seeded(row,c+7);if(chance>.78&&!(row>player.row-3&&row<player.row+4&&Math.abs(c-player.x)<1.25))drawTree(cellX(c,row),y-step*.14,s,row,chance)}for(let c=0;c<6;c++)if(seeded(row,c+31)>.43){const x=cellX(c-.5,row),yy=y-step*.26;ctx.fillStyle=seeded(row,c+48)>.5?'#d7f486':'#76c73b';polygon([[x,yy-3*s],[x+4*s,yy],[x,yy+3*s],[x-4*s,yy]],ctx.fillStyle)}if(coinRows.has(row))drawCoin(cellX(2,row),y-step*.15,s)}else if(kind==='road'){topBand(row,y,step,'road','#414a52','#29343a');const width=rowWidth(row,'road'),left=W/2+rowShift(row)-width/2;ctx.strokeStyle='#dbd4ae';ctx.lineWidth=Math.max(2,3*s);ctx.setLineDash([Math.max(12,cellSize(row)*.32),Math.max(10,cellSize(row)*.32)]);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+width+step*.36,y+step*.36);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#eadb98';ctx.lineWidth=Math.max(3,5*s);ctx.beginPath();ctx.moveTo(left,y-step*.47);ctx.lineTo(left+width+step*.36,y-step*.11);ctx.stroke();ctx.beginPath();ctx.moveTo(left,y+step*.48);ctx.lineTo(left+width+step*.36,y+step*.84);ctx.stroke();traffic.filter(a=>a.row===row).forEach(drawVehicle)}else{topBand(row,y,step,'river','#37c7e7','#157ba5');ctx.strokeStyle='#8cecff';ctx.lineWidth=Math.max(1,2*s);for(let c=-2;c<=6;c++)if(seeded(row,c+56)>.25){const x=cellX(c,row)+mod(clock*10+row*9,W*.09),yy=y-step*.15+(c%2)*step*.22;ctx.beginPath();ctx.moveTo(x,yy);ctx.lineTo(x+cellSize(row)*.22,yy+step*.12);ctx.lineTo(x+cellSize(row)*.42,yy);ctx.stroke()}const l=logs.find(a=>a.row===row);if(l)drawLog(l)}}
function drawCoin(x,y,s){ctx.save();ctx.translate(x,y);ctx.shadowColor='#f8b725';ctx.shadowBlur=12*s;ctx.fillStyle='#ffce28';ctx.beginPath();ctx.arc(0,0,12*s,0,6.3);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffef83';ctx.lineWidth=2*s;ctx.beginPath();ctx.arc(0,0,8*s,0,6.3);ctx.stroke();ctx.fillStyle='#9d5a05';ctx.font=`900 ${12*s}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('$',0,1*s);ctx.restore()}
function drawPlayer(){const y=groundY(player.row),s=scaleAt(player.row),x=cellX(player.x,player.row),w=cellSize(player.row)*.78,h=w*1.32,hop=Math.sin(player.hop*Math.PI)*12*s;ctx.save();ctx.translate(x,y-hop);ctx.shadowColor='#13201577';ctx.shadowBlur=10*s;ctx.shadowOffsetY=5*s;if(hero.complete&&hero.naturalWidth){ctx.drawImage(hero,0,0,hero.naturalWidth/4,hero.naturalHeight,-w/2,-h*.88,w,h)}else{ctx.fillStyle='#176ce5';ctx.fillRect(-w*.3,-h*.45,w*.6,h*.48);ctx.fillStyle='#e9b994';ctx.beginPath();ctx.arc(0,-h*.67,w*.25,0,6.3);ctx.fill();ctx.fillStyle='#172137';ctx.fillRect(-w*.27,-h*.86,w*.54,h*.1);ctx.fillStyle='#ffd225';ctx.font=`bold ${w*.2}px Arial`;ctx.fillText('★',0,-h*.36)}ctx.restore()}
function draw(){drawBackground();spawnAhead();for(let r=Math.floor(player.row)+21;r>=Math.floor(player.row)-2;r--)drawRow(r);drawPlayer();if(toast&&performance.now()-toastAt<900){ctx.textAlign='center';ctx.font='900 20px system-ui';ctx.fillStyle='#fff3b4';ctx.shadowColor='#172819';ctx.shadowBlur=5;ctx.fillText(toast,W/2,H*.23);ctx.shadowBlur=0}}
function update(dt){if(state!=='playing')return;clock+=dt;moveLock=Math.max(0,moveLock-dt);const camTarget=Math.max(0,player.row-2);camera+=(camTarget-camera)*Math.min(1,dt*8);for(const t of traffic){t.x+=t.dir*t.speed*dt;if(t.dir>0&&t.x>6.2)t.x=-1.2;if(t.dir<0&&t.x< -1.2)t.x=6.2}for(const l of logs){l.x+=l.dir*l.speed*dt;if(l.dir>0&&l.x>6+l.length)l.x=-l.length;if(l.dir<0&&l.x< -l.length)l.x=6+l.length}
const k=Math.round(player.row);if(typeAt(k)==='road'){if(traffic.some(v=>v.row===k&&Math.abs(v.x-player.x)<.62)){endGame('¡Un auto te alcanzó!')}}if(typeAt(k)==='river'){const l=logs.find(v=>v.row===k);if(!l||Math.abs(l.x-player.x)>l.length*.52+.25){if(performance.now()>waterGraceUntil)endGame('¡Te caíste al agua!')}else{waterGraceUntil=0;player.x+=l.dir*l.speed*dt;if(player.x<-.45||player.x>4.45)endGame('¡La corriente te arrastró!')}}if(coinRows.has(k)&&Math.abs(player.row-k)<.35){coinRows.delete(k);coins++;coinsEl.textContent=coins;toast='¡MONEDA! +1';toastAt=performance.now()}score=Math.max(score,Math.max(0,Math.floor(player.row)));scoreEl.textContent=score;if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('vladiCrossyBest',best)}player.hop=Math.max(0,player.hop-dt*3.2)}
let lastMove=performance.now();function move(dir){if(state!=='playing'||moveLock>0)return;moveLock=.08;lastMove=performance.now();if(dir==='up'){player.row=Math.floor(player.row)+1;player.hop=1}else if(dir==='down'){player.row=Math.max(0,Math.ceil(player.row)-1);player.hop=1}else if(dir==='left')player.x=Math.max(0,player.x-1);else if(dir==='right')player.x=Math.min(4,player.x+1);spawnAhead();waterGraceUntil=typeAt(Math.round(player.row))==='river'?performance.now()+850:0;const k=Math.round(player.row);if(coinRows.has(k)&&Math.abs(player.x-2)<2){coinRows.delete(k);coins++;coinsEl.textContent=coins;toast='¡MONEDA! +1';toastAt=performance.now()}score=Math.max(score,player.row);scoreEl.textContent=score;if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('vladiCrossyBest',best)}}
function begin(){player={x:2,row:0,hop:0};camera=0;score=0;coins=0;clock=0;waterGraceUntil=0;traffic=[];logs=[];coinRows=new Set();lastMove=performance.now();state='playing';spawnAhead();panel.classList.add('hidden');hud.classList.remove('hidden');controls.classList.remove('hidden');pauseBtn.classList.remove('hidden');scoreEl.textContent='0';coinsEl.textContent='0';bestEl.textContent=best}
function pause(){if(state==='playing'){state='paused';title.textContent='PAUSA';panelText.textContent='La partida quedó pausada.';hint.textContent='';startBtn.textContent='▶ CONTINUAR';panel.classList.remove('hidden')}else if(state==='paused'){state='playing';panel.classList.add('hidden');startBtn.textContent='▶ JUGAR';lastMove=performance.now()}}
function endGame(msg){if(state!=='playing')return;state='over';title.textContent='¡FIN DEL JUEGO!';panelText.textContent=`${msg} Cruzaste ${score} calles y juntaste ${coins} monedas.`;hint.textContent=`Récord: ${best} cruces`;startBtn.textContent='↻ REINTENTAR';panel.classList.remove('hidden');controls.classList.add('hidden');pauseBtn.classList.add('hidden')}
startBtn.addEventListener('click',()=>state==='paused'?pause():begin());pauseBtn.addEventListener('click',pause);document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();move(b.dataset.move)}));addEventListener('keydown',e=>{const map={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};if(map[e.code]){e.preventDefault();move(map[e.code])}if(e.code==='Escape'||e.code==='KeyP')pause()},{passive:false});let start=null;canvas.addEventListener('pointerdown',e=>{start=[e.clientX,e.clientY]},{passive:true});canvas.addEventListener('pointerup',e=>{if(!start||state!=='playing')return;const dx=e.clientX-start[0],dy=e.clientY-start[1];if(Math.max(Math.abs(dx),Math.abs(dy))<18){start=null;return}move(Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down'));start=null},{passive:true});
function frame(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.__vladiCrossy={get state(){return state},get metrics(){return{score,coins,best,row:player.row,x:player.x,traffic:traffic.length,logs:logs.length}},start:begin,move,forceTraffic:(row,x)=>traffic.push({row,x,dir:1,speed:0,color:'#ed4b35',type:'car'}),setPlayer:(x,row)=>{player.x=x;player.row=row},resize,getLayout:()=>({width:W,height:H,dpr})};
})();
