(()=>{
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),panel=document.querySelector('#panel'),title=document.querySelector('#panelTitle'),panelText=document.querySelector('#panelText'),startBtn=document.querySelector('#start'),hint=document.querySelector('#hint'),hud=document.querySelector('#hud'),controls=document.querySelector('#controls'),pauseBtn=document.querySelector('#pause'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),coinsEl=document.querySelector('#coins'),hero=new Image();hero.src='../vladi-run/assets/vladi-runner.webp';
let W=innerWidth,H=innerHeight,dpr=1,state='menu',last=0,clock=0,player={x:2,row:0,hop:0},camera=0,score=0,coins=0,best=+(localStorage.getItem('vladiCrossyBest')||0),traffic=[],logs=[],coinRows=new Set(),stripe=0,toast='',toastAt=0,shake=0,moveLock=0,waterGraceUntil=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),mod=(a,b)=>(a%b+b)%b;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
function typeAt(row){const n=mod(row,12);if(n===3||n===4||n===8)return'road';if(n===6||n===7)return'river';return'grass'}
function rowData(row){if(typeAt(row)==='road'&&!traffic.some(t=>t.row===row)){const dir=(row%2?1:-1);traffic.push({row,x:dir>0?-.9:5.9,dir,speed:rand(.72,1.22),color:['#ed4b35','#ffd94d','#38a5e5','#f3f0dc','#a557dc'][Math.floor(rand(0,5))],type:Math.random()<.55?'car':'van'})}if(typeAt(row)==='river'&&!logs.some(t=>t.row===row)){const dir=row%2?1:-1,length=2,startX=clamp(player.x-length*.42,-.8,4-length*.42);logs.push({row,x:startX,dir,speed:rand(.25,.4),length})}if(typeAt(row)==='grass'&&row>3&&!coinRows.has(row)&&Math.random()<.09)coinRows.add(row)}
function spawnAhead(){for(let r=Math.floor(player.row)-2;r<Math.floor(player.row)+22;r++)rowData(r);traffic=traffic.filter(t=>t.row>player.row-5&&t.row<player.row+24);logs=logs.filter(t=>t.row>player.row-5&&t.row<player.row+24);for(const n of coinRows)if(n<player.row-5)coinRows.delete(n)}
function groundY(row){const depth=row-camera;return H*.79-depth*Math.max(27,Math.min(49,H*.052))}
function scaleAt(row){return clamp(1.08-(row-camera)*.032,.42,1.18)}
function cellSize(row){return Math.min(W*.188,256)*scaleAt(row)}
function cellX(x,row){return W/2+(x-2)*cellSize(row)}
function drawBackground(){let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#69d5f4');sky.addColorStop(.48,'#b9e9b0');sky.addColorStop(1,'#4b9d36');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
// distant tropical cliffs and palms
ctx.fillStyle='#398d63';ctx.beginPath();ctx.moveTo(0,H*.39);for(let x=0;x<=W+80;x+=80)ctx.lineTo(x,H*(.31+Math.sin(x*.018+clock*.08)*.035));ctx.lineTo(W,H*.58);ctx.lineTo(0,H*.58);ctx.fill();ctx.fillStyle='#24714f';for(let i=0;i<12;i++){const x=(i*137+clock*5)%(W+80)-40,y=H*(.25+(i%3)*.055),s=.7+(i%4)*.13;ctx.fillRect(x-3,y,6,H*.13);for(let a=0;a<5;a++){ctx.beginPath();ctx.ellipse(x+Math.cos(a*1.25)*20*s,y+Math.sin(a*1.25)*11*s,23*s,9*s,a*1.25,0,6.29);ctx.fill()}}}
function rounded(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawCar(t,y,s){const cx=cellX(t.x,y,s);}
function drawVehicle(t){const y=groundY(t.row),s=scaleAt(t.row),x=cellX(t.x,t.row),w=cellSize(t.row)*.68,h=w*(t.type==='van'?1.34:1.08);ctx.save();ctx.translate(x,y);ctx.shadowColor='#12251f77';ctx.shadowBlur=8*s;ctx.shadowOffsetY=5*s;rounded(-w*.48,-h*.45,w*.96,h*.9,10*s,t.color);ctx.shadowBlur=0;rounded(-w*.32,-h*.29,w*.64,h*.25,5*s,'#172c35');rounded(-w*.32,h*.05,w*.64,h*.22,5*s,'#9fdbeb');rounded(-w*.42,-h*.3,w*.1,h*.15,3*s,'#17191b');rounded(w*.32,-h*.3,w*.1,h*.15,3*s,'#17191b');rounded(-w*.42,h*.17,w*.1,h*.15,3*s,'#17191b');rounded(w*.32,h*.17,w*.1,h*.15,3*s,'#17191b');ctx.fillStyle='#fff2b2';ctx.fillRect(-w*.36,-h*.46,w*.17,h*.07);ctx.fillRect(w*.19,-h*.46,w*.17,h*.07);ctx.restore()}
function drawLog(t){const y=groundY(t.row),s=scaleAt(t.row),x=cellX(t.x,t.row),w=cellSize(t.row)*t.length;ctx.save();ctx.translate(x,y);ctx.shadowColor='#0006';ctx.shadowBlur=7*s;rounded(-w/2,-12*s,w,24*s,10*s,'#8d552b');ctx.shadowBlur=0;for(let k=0;k<t.length;k++){ctx.strokeStyle='#c18243';ctx.lineWidth=2*s;ctx.beginPath();ctx.ellipse(-w/2+(k+.5)*(w/t.length),0,w/t.length*.38,8*s,0,0,6.3);ctx.stroke()}ctx.restore()}
function drawRow(row){const y=groundY(row),s=scaleAt(row),step=Math.max(27,Math.min(49,H*.052))*s;if(y<-step||y>H+step)return;const kind=typeAt(row);if(kind==='grass'){ctx.fillStyle=row%2?'#59ae45':'#66ba4e';ctx.fillRect(0,y-step*.48,W,step*.96);ctx.fillStyle='#84d853';for(let i=0;i<12;i++){const x=mod(i*113+row*41,W);ctx.beginPath();ctx.ellipse(x,y-step*.3,8*s,3*s,-.5,0,6.3);ctx.fill()}if(coinRows.has(row)){drawCoin(W/2,y-step*.13,s)}}else if(kind==='road'){ctx.fillStyle='#414b51';ctx.fillRect(0,y-step*.48,W,step*.96);ctx.fillStyle='#eee0b4';ctx.fillRect(0,y-step*.5,5*s,step);ctx.fillRect(W-5*s,y-step*.5,5*s,step);ctx.fillStyle='#dfcf9c';for(let x=W*.08;x<W;x+=W*.18)ctx.fillRect(x,y-2*s,Math.max(12,24*s),4*s);const t=traffic.find(a=>a.row===row);if(t)drawVehicle(t)}else{ctx.fillStyle='#168ec0';ctx.fillRect(0,y-step*.48,W,step*.96);ctx.strokeStyle='#70daf0';ctx.lineWidth=2*s;for(let x=mod(clock*24+row*17,W)-W;x<W;x+=W*.2){ctx.beginPath();ctx.moveTo(x,y-step*.2);ctx.quadraticCurveTo(x+16*s,y-step*.34,x+30*s,y-step*.2);ctx.stroke()}const l=logs.find(a=>a.row===row);if(l)drawLog(l)}}
function drawCoin(x,y,s){ctx.save();ctx.translate(x,y);ctx.shadowColor='#f8b725';ctx.shadowBlur=12*s;ctx.fillStyle='#ffce28';ctx.beginPath();ctx.arc(0,0,12*s,0,6.3);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffef83';ctx.lineWidth=2*s;ctx.beginPath();ctx.arc(0,0,8*s,0,6.3);ctx.stroke();ctx.fillStyle='#9d5a05';ctx.font=`900 ${12*s}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('$',0,1*s);ctx.restore()}
function drawPlayer(){const y=groundY(player.row),s=scaleAt(player.row),x=cellX(player.x,player.row),w=cellSize(player.row)*.78,h=w*1.32,hop=Math.sin(player.hop*Math.PI)*12*s;ctx.save();ctx.translate(x,y-hop);ctx.shadowColor='#13201577';ctx.shadowBlur=10*s;ctx.shadowOffsetY=5*s;if(hero.complete&&hero.naturalWidth){ctx.drawImage(hero,0,0,hero.naturalWidth/4,hero.naturalHeight,-w/2,-h*.88,w,h)}else{ctx.fillStyle='#176ce5';ctx.fillRect(-w*.3,-h*.45,w*.6,h*.48);ctx.fillStyle='#e9b994';ctx.beginPath();ctx.arc(0,-h*.67,w*.25,0,6.3);ctx.fill();ctx.fillStyle='#172137';ctx.fillRect(-w*.27,-h*.86,w*.54,h*.1);ctx.fillStyle='#ffd225';ctx.font=`bold ${w*.2}px Arial`;ctx.fillText('★',0,-h*.36)}ctx.restore()}
function draw(){drawBackground();spawnAhead();for(let r=Math.floor(player.row)-2;r<Math.floor(player.row)+21;r++)drawRow(r);drawPlayer();if(toast&&performance.now()-toastAt<900){ctx.textAlign='center';ctx.font='900 20px system-ui';ctx.fillStyle='#fff3b4';ctx.shadowColor='#172819';ctx.shadowBlur=5;ctx.fillText(toast,W/2,H*.23);ctx.shadowBlur=0}}
function update(dt){if(state!=='playing')return;clock+=dt;moveLock=Math.max(0,moveLock-dt);const camTarget=Math.max(0,player.row-2);camera+=(camTarget-camera)*Math.min(1,dt*8);for(const t of traffic){t.x+=t.dir*t.speed*dt;if(t.dir>0&&t.x>6.2)t.x=-1.2;if(t.dir<0&&t.x< -1.2)t.x=6.2}for(const l of logs){l.x+=l.dir*l.speed*dt;if(l.dir>0&&l.x>6+l.length)l.x=-l.length;if(l.dir<0&&l.x< -l.length)l.x=6+l.length}
const k=Math.round(player.row);if(typeAt(k)==='road'){const t=traffic.find(v=>v.row===k);if(t&&Math.abs(t.x-player.x)<.62){endGame('¡Un auto te alcanzó!')}}if(typeAt(k)==='river'){const l=logs.find(v=>v.row===k);if(!l||Math.abs(l.x-player.x)>l.length*.52+.25){if(performance.now()>waterGraceUntil)endGame('¡Te caíste al agua!')}else{waterGraceUntil=0;player.x+=l.dir*l.speed*dt;if(player.x<-.45||player.x>4.45)endGame('¡La corriente te arrastró!')}}if(coinRows.has(k)&&Math.abs(player.row-k)<.35){coinRows.delete(k);coins++;coinsEl.textContent=coins;toast='¡MONEDA! +1';toastAt=performance.now()}score=Math.max(score,Math.max(0,Math.floor(player.row)));scoreEl.textContent=score;if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('vladiCrossyBest',best)}player.hop=Math.max(0,player.hop-dt*3.2)}
let lastMove=performance.now();function move(dir){if(state!=='playing'||moveLock>0)return;moveLock=.08;lastMove=performance.now();if(dir==='up'){player.row=Math.floor(player.row)+1;player.hop=1}else if(dir==='down'){player.row=Math.max(0,Math.ceil(player.row)-1);player.hop=1}else if(dir==='left')player.x=Math.max(0,player.x-1);else if(dir==='right')player.x=Math.min(4,player.x+1);spawnAhead();waterGraceUntil=typeAt(Math.round(player.row))==='river'?performance.now()+850:0;const k=Math.round(player.row);if(coinRows.has(k)&&Math.abs(player.x-2)<2){coinRows.delete(k);coins++;coinsEl.textContent=coins;toast='¡MONEDA! +1';toastAt=performance.now()}score=Math.max(score,player.row);scoreEl.textContent=score;if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('vladiCrossyBest',best)}}
function begin(){player={x:2,row:0,hop:0};camera=0;score=0;coins=0;clock=0;waterGraceUntil=0;traffic=[];logs=[];coinRows=new Set();lastMove=performance.now();state='playing';spawnAhead();panel.classList.add('hidden');hud.classList.remove('hidden');controls.classList.remove('hidden');pauseBtn.classList.remove('hidden');scoreEl.textContent='0';coinsEl.textContent='0';bestEl.textContent=best}
function pause(){if(state==='playing'){state='paused';title.textContent='PAUSA';panelText.textContent='La partida quedó pausada.';hint.textContent='';startBtn.textContent='▶ CONTINUAR';panel.classList.remove('hidden')}else if(state==='paused'){state='playing';panel.classList.add('hidden');startBtn.textContent='▶ JUGAR';lastMove=performance.now()}}
function endGame(msg){if(state!=='playing')return;state='over';title.textContent='¡FIN DEL JUEGO!';panelText.textContent=`${msg} Cruzaste ${score} calles y juntaste ${coins} monedas.`;hint.textContent=`Récord: ${best} cruces`;startBtn.textContent='↻ REINTENTAR';panel.classList.remove('hidden');controls.classList.add('hidden');pauseBtn.classList.add('hidden')}
startBtn.addEventListener('click',()=>state==='paused'?pause():begin());pauseBtn.addEventListener('click',pause);document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();move(b.dataset.move)}));addEventListener('keydown',e=>{const map={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};if(map[e.code]){e.preventDefault();move(map[e.code])}if(e.code==='Escape'||e.code==='KeyP')pause()},{passive:false});let start=null;canvas.addEventListener('pointerdown',e=>{start=[e.clientX,e.clientY]},{passive:true});canvas.addEventListener('pointerup',e=>{if(!start||state!=='playing')return;const dx=e.clientX-start[0],dy=e.clientY-start[1];if(Math.max(Math.abs(dx),Math.abs(dy))<18){start=null;return}move(Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down'));start=null},{passive:true});
function frame(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.__vladiCrossy={get state(){return state},get metrics(){return{score,coins,best,row:player.row,x:player.x,traffic:traffic.length,logs:logs.length}},start:begin,move,forceTraffic:(row,x)=>traffic.push({row,x,dir:1,speed:0,color:'#ed4b35',type:'car'}),setPlayer:(x,row)=>{player.x=x;player.row=row},resize,getLayout:()=>({width:W,height:H,dpr})};
})();
