(()=>{
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),hero=document.querySelector('#hero'),hctx=hero.getContext('2d');
const panel=document.querySelector('#panel'),title=document.querySelector('#panelTitle'),panelText=document.querySelector('#panelText'),hint=document.querySelector('#hint'),startBtn=document.querySelector('#start'),pauseBtn=document.querySelector('#pause'),hud=document.querySelector('#hud'),help=document.querySelector('#help'),scoreEl=document.querySelector('#score'),waveEl=document.querySelector('#wave'),livesEl=document.querySelector('#lives'),menuBest=document.querySelector('#menuBest');
const pilotArt=new Image();pilotArt.src='../vladi-run/assets/vladi-runner.webp';
const STORE='vladiGalaxiaBest';let W=innerWidth,H=innerHeight,D=1,state='menu',time=0,lastFrame=0,elapsed=0,score=0,best=+(localStorage.getItem(STORE)||0),lives=3,wave=1,waveClock=0,lastBossWave=0,spawnClock=.8,fireClock=0,boss=null,player=null,shots=[],enemyShots=[],enemies=[],meteors=[],pickups=[],particles=[],stars=[],keys=new Set(),pointerActive=false,targetX=0,targetY=0,shake=0,flash=0,toast='',toastUntil=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);const r=hero.getBoundingClientRect(),heroW=r.width||Math.min(300,W*.78),heroH=r.height||Math.min(190,H*.24);hero.width=Math.round(heroW*D);hero.height=Math.round(heroH*D);hctx.setTransform(D,0,0,D,0,0);makeStars();drawHero()}
function makeStars(){stars=Array.from({length:Math.max(75,Math.round(W*H/8500))},()=>({x:Math.random()*W,y:Math.random()*H,r:rand(.5,2.1),z:rand(.2,1),phase:rand(0,Math.PI*2)}))}
addEventListener('resize',resize);resize();
function sound(name){window.VladiSound?.play(name)}
function drawStar(x,y,r,rotation=0,color='#ffe27a',c=ctx){c.save();c.translate(x,y);c.rotate(rotation);c.fillStyle=color;c.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.43:r;c.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}c.closePath();c.fill();c.restore()}
function drawPilot(c,x,y,s){c.save();c.translate(x,y);c.scale(s,s);
 // Traje azul y estrella de Vladi.
 c.fillStyle='#1c63bd';c.beginPath();c.moveTo(-20,28);c.quadraticCurveTo(-29,42,-25,61);c.lineTo(25,61);c.quadraticCurveTo(29,42,20,28);c.closePath();c.fill();c.strokeStyle='#8edfff';c.lineWidth=2;c.stroke();
 c.fillStyle='#ffcf67';c.beginPath();c.moveTo(-9,37);c.lineTo(0,31);c.lineTo(9,37);c.lineTo(5,47);c.lineTo(-5,47);c.closePath();c.fill();drawStar(0,40,5,0,'#fff2a2',c);
 // Rostro real de Vladi, recortado dentro del visor de la nave.
 c.save();c.beginPath();c.ellipse(0,3,25,31,0,0,Math.PI*2);c.clip();
 if(pilotArt.complete&&pilotArt.naturalWidth)c.drawImage(pilotArt,54,8,176,137,-25,-30,50,62);
 else {c.fillStyle='#efb387';c.beginPath();c.ellipse(0,4,20,25,0,0,Math.PI*2);c.fill();c.fillStyle='#151627';c.beginPath();c.ellipse(0,-10,22,11,0,0,Math.PI*2);c.fill();}
 c.restore();
 // Borde luminoso del casco.
 c.strokeStyle='#b8f7ff';c.lineWidth=4;c.beginPath();c.ellipse(0,4,26,32,0,0,Math.PI*2);c.stroke();c.strokeStyle='#fff';c.lineWidth=1.4;c.beginPath();c.arc(0,4,28,-2.25,-1.55);c.stroke();c.fillStyle='#ffd353';c.beginPath();c.arc(-25,5,4,0,Math.PI*2);c.arc(25,5,4,0,Math.PI*2);c.fill();c.restore()}
function drawShip(c,x,y,scale,flame=0){c.save();c.translate(x,y);c.scale(scale,scale);
 // animated plasma exhaust
 const flameLen=16+flame*11;c.shadowColor='#ff8b34';c.shadowBlur=17;c.fillStyle='#ff8e36';c.beginPath();c.moveTo(-15,35);c.quadraticCurveTo(-25,35,-18,35+flameLen);c.quadraticCurveTo(0,44+flameLen,18,35+flameLen);c.quadraticCurveTo(24,35,-15,35);c.fill();c.fillStyle='#ffe67a';c.beginPath();c.moveTo(-7,35);c.quadraticCurveTo(-10,40,-5,35+flameLen*.66);c.quadraticCurveTo(0,43+flameLen*.66,6,35+flameLen*.66);c.quadraticCurveTo(10,39,-7,35);c.fill();c.shadowBlur=0;
 // side wings, hull
 const wing=c.createLinearGradient(-48,0,48,0);wing.addColorStop(0,'#b12684');wing.addColorStop(.48,'#f3b83d');wing.addColorStop(1,'#a92a93');c.fillStyle=wing;c.strokeStyle='#ffe27c';c.lineWidth=2.2;c.beginPath();c.moveTo(-15,-8);c.lineTo(-48,13);c.lineTo(-42,34);c.lineTo(-12,27);c.lineTo(0,38);c.lineTo(12,27);c.lineTo(42,34);c.lineTo(48,13);c.lineTo(15,-8);c.closePath();c.fill();c.stroke();
 c.fillStyle='#e94e48';c.beginPath();c.moveTo(-31,19);c.lineTo(-45,17);c.lineTo(-39,27);c.lineTo(-25,27);c.closePath();c.fill();c.beginPath();c.moveTo(31,19);c.lineTo(45,17);c.lineTo(39,27);c.lineTo(25,27);c.closePath();c.fill();
 const hull=c.createLinearGradient(0,-26,0,42);hull.addColorStop(0,'#f6faff');hull.addColorStop(.45,'#8ca9da');hull.addColorStop(1,'#354d85');c.fillStyle=hull;c.strokeStyle='#e2f8ff';c.lineWidth=2;c.beginPath();c.moveTo(0,-34);c.quadraticCurveTo(18,-15,18,12);c.lineTo(11,34);c.quadraticCurveTo(0,42,-11,34);c.lineTo(-18,12);c.quadraticCurveTo(-18,-15,0,-34);c.fill();c.stroke();
 // viewport
 const glass=c.createLinearGradient(-18,-24,18,19);glass.addColorStop(0,'#173456');glass.addColorStop(.48,'#46bbdf');glass.addColorStop(1,'#96efff');c.fillStyle=glass;c.beginPath();c.ellipse(0,-8,16,21,0,0,Math.PI*2);c.fill();c.strokeStyle='#fff';c.lineWidth=2;c.stroke();
 c.save();c.beginPath();c.ellipse(0,-7,13,17,0,0,Math.PI*2);c.clip();drawPilot(c,0,-11,.56,0);c.restore();
 c.fillStyle='#ffdc62';c.beginPath();c.arc(-26,15,3,0,Math.PI*2);c.arc(26,15,3,0,Math.PI*2);c.fill();c.restore()}
function drawHero(){if(!hero.isConnected||hero.clientWidth===0)return;const w=hero.clientWidth,h=hero.clientHeight;hctx.clearRect(0,0,w,h);const t=performance.now()/1000;for(let i=0;i<32;i++){const x=(i*71%w),y=(i*37%h);hctx.globalAlpha=.25+.55*((Math.sin(t*2+i)+1)/2);hctx.fillStyle=i%4?'#fff':'#79eaff';hctx.beginPath();hctx.arc(x,y,i%6===0?1.7:.9,0,Math.PI*2);hctx.fill()}hctx.globalAlpha=1;drawShip(hctx,w/2,h*.67,1.35,Math.sin(t*9)*.45+.55)}
function background(dt){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#091938');g.addColorStop(.42,'#111b46');g.addColorStop(1,'#080c24');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
 // nebula clouds
 for(let i=0;i<3;i++){const x=W*(.18+i*.34)+Math.sin(time*.07+i*2)*W*.035,y=H*(.23+(i%2)*.27),r=Math.max(W,H)*(.25+i*.035),ng=ctx.createRadialGradient(x,y,2,x,y,r);ng.addColorStop(0,['#8d3eb22b','#1874aa2a','#dc4b8b21'][i]);ng.addColorStop(1,'#0d174000');ctx.fillStyle=ng;ctx.fillRect(x-r,y-r,r*2,r*2)}
 // distant planet and ring
 ctx.save();ctx.translate(W*.82,H*.26);ctx.rotate(-.18);ctx.strokeStyle='#8ae8ff44';ctx.lineWidth=Math.max(3,W*.006);ctx.beginPath();ctx.ellipse(0,0,W*.095,H*.027,0,0,Math.PI*2);ctx.stroke();const pg=ctx.createRadialGradient(-W*.025,-H*.04,2,0,0,W*.075);pg.addColorStop(0,'#b9f4ff');pg.addColorStop(.22,'#699ecf');pg.addColorStop(1,'#2e3e84');ctx.fillStyle=pg;ctx.beginPath();ctx.arc(0,0,W*.06,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#bacfff66';ctx.lineWidth=2;for(let k=-2;k<=2;k++){ctx.beginPath();ctx.ellipse(0,k*H*.008,W*.052,Math.abs(k)*3+2,0,0,Math.PI*2);ctx.stroke()}ctx.restore();
 // distant banded moon
 ctx.globalAlpha=.55;ctx.fillStyle='#b6caf7';ctx.beginPath();ctx.arc(W*.14,H*.44,Math.min(W,H)*.035,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
 for(const s of stars){s.y+=dt*(12+68*s.z);if(s.y>H+3){s.y=-3;s.x=Math.random()*W}const tw=.5+.5*Math.sin(time*2+s.phase);ctx.globalAlpha=(.3+.65*tw)*s.z;ctx.fillStyle=s.z>.83?'#b9f5ff':'#fff';ctx.beginPath();ctx.arc(s.x,s.y,s.r*(.7+tw*.5),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 // subtle horizon depth bands
 const hz=ctx.createLinearGradient(0,H*.59,0,H);hz.addColorStop(0,'#53297800');hz.addColorStop(1,'#16183c99');ctx.fillStyle=hz;ctx.fillRect(0,H*.58,W,H*.42);
}
function addParticle(x,y,color,n=7,power=150){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),v=rand(power*.25,power),life=rand(.22,.68);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,r:rand(1.5,4.5),life,age:0,color})}}
function fire(){if(!player)return;shots.push({x:player.x,y:player.y-31,vx:0,vy:-H*1.35,r:4.5,life:1.6});shots.push({x:player.x-10,y:player.y-19,vx:-W*.018,vy:-H*1.22,r:3,life:1.5});shots.push({x:player.x+10,y:player.y-19,vx:W*.018,vy:-H*1.22,r:3,life:1.5});sound('move')}
function spawnFormation(){const n=Math.min(6,3+Math.floor(wave/3)),margin=W*.17,span=Math.max(0,W-margin*2),gap=span/Math.max(1,n-1);for(let i=0;i<n;i++){const type=wave>2&&Math.random()<.22?'scout':'drone',r=type==='scout'?17:22,x=margin+i*gap,yOffset=(i%2)*H*.045;enemies.push({type,x,y:-r-yOffset-rand(0,30),baseX:x,r,hp:type==='scout'?1:2,phase:rand(0,Math.PI*2),speed:H*(.14+Math.min(.13,wave*.007)),score:type==='scout'?100:75,fire:rand(1.8,4)})}if(Math.random()<.48)meteors.push({x:rand(W*.08,W*.92),y:-35,r:rand(13,21),vx:rand(-W*.12,W*.12),vy:H*rand(.17,.27),rot:rand(0,6),vr:rand(-2,2)})}
function spawnBoss(){boss={x:W/2,y:-70,targetY:Math.max(100,H*.2),r:Math.min(W*.12,52),hp:20+wave*2,maxHp:20+wave*2,t:0,fire:.8,direction:1};toast='¡JEFE DE OLEADA!';toastUntil=time+2;sound('explosion')}
function setScore(amount){score+=amount;scoreEl.textContent=String(score);if(score>best){best=score;menuBest.textContent=String(best);try{localStorage.setItem(STORE,String(best))}catch(_){}}}
function damage(){if(!player||player.invuln>0)return;lives--;livesEl.textContent='♥'.repeat(Math.max(0,lives));player.invuln=1.25;shake=.25;flash=.2;sound('explosion');addParticle(player.x,player.y,'#ff9256',18,240);if(lives<=0)endGame()}
function killEnemy(e){e.dead=true;setScore(e.score);addParticle(e.x,e.y,e.type==='scout'?'#ff65cb':'#61ecff',13,190);sound('collect');if(Math.random()<.12)pickups.push({x:e.x,y:e.y,r:13,type:Math.random()<.25?'shield':'star',vy:H*.13,phase:0})}
function endGame(){if(state!=='playing')return;if(typeof gtag==='function')gtag('event','game_end',{game_id:'vladi-galaxia',game_name:'Vladi Galaxia',score:score,level:wave});state='over';sound('gameover');title.textContent='FIN DE LA MISIÓN';panelText.textContent='Conseguiste '+score+' puntos y llegaste a la oleada '+wave+'.';hint.textContent='Tocá jugar para volver a defender la galaxia.';startBtn.textContent='↻ VOLVER A JUGAR';panel.classList.remove('hidden');pauseBtn.classList.add('hidden');help.classList.add('hidden')}
function start(){if(typeof gtag==='function')gtag('event','game_start',{game_id:'vladi-galaxia',game_name:'Vladi Galaxia'});sound('start');score=0;lives=3;wave=1;elapsed=0;waveClock=0;lastBossWave=0;spawnClock=.75;fireClock=.14;boss=null;shots=[];enemyShots=[];enemies=[];meteors=[];pickups=[];particles=[];shake=0;flash=0;toast='';scoreEl.textContent='0';waveEl.textContent='1';livesEl.textContent='♥♥♥';player={x:W/2,y:H*.81,r:Math.max(17,Math.min(W,H)*.035),invuln:1};targetX=player.x;targetY=player.y;state='playing';panel.classList.add('hidden');hud.classList.remove('hidden');pauseBtn.classList.remove('hidden');help.classList.remove('hidden');startBtn.textContent='▶ JUGAR'}
function pause(){if(state==='playing'){sound('pause');state='paused';title.textContent='PAUSA';panelText.textContent='Puntaje: '+score+' · Oleada '+wave+'.';hint.textContent='Tomate un respiro y seguí cuando quieras.';startBtn.textContent='▶ CONTINUAR';panel.classList.remove('hidden')}else if(state==='paused'){sound('resume');state='playing';panel.classList.add('hidden')}}
startBtn.addEventListener('click',()=>state==='paused'?pause():start());pauseBtn.addEventListener('click',pause);
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;e.preventDefault();pointerActive=true;const p=pos(e);targetX=p.x;targetY=p.y;try{canvas.setPointerCapture(e.pointerId)}catch{}},{passive:false});
canvas.addEventListener('pointermove',e=>{if(!pointerActive||state!=='playing')return;e.preventDefault();const p=pos(e);targetX=p.x;targetY=p.y},{passive:false});
function release(e){if(pointerActive&&player&&state==='playing'){if(e&&Number.isFinite(e.clientX)){const p=pos(e);targetX=p.x;targetY=p.y}player.x=clamp(targetX,player.r+5,W-player.r-5);player.y=clamp(targetY,H*.48,H*.9)}pointerActive=false}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' ','w','a','s','d','escape','p'].includes(k))e.preventDefault();keys.add(k);if((k==='escape'||k==='p')&&state!=='menu'&&state!=='over')pause()},{passive:false});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
function update(dt){time+=dt;if(state!=='playing'){if(particles.length){for(const p of particles){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt}particles=particles.filter(p=>p.age<p.life)}return}elapsed+=dt;waveClock+=dt;const nextWave=1+Math.floor(elapsed/19);if(nextWave>wave){wave=nextWave;waveEl.textContent=String(wave);toast='OLEADA '+wave;toastUntil=time+1.2;sound('start')}
 if(wave>=3&&wave%3===0&&!boss&&lastBossWave<wave){spawnBoss();lastBossWave=wave;waveClock=0}
 const speed=W*.76;let dx=0,dy=0;if(keys.has('arrowleft')||keys.has('a'))dx--;if(keys.has('arrowright')||keys.has('d'))dx++;if(keys.has('arrowup')||keys.has('w'))dy--;if(keys.has('arrowdown')||keys.has('s'))dy++;
 if(pointerActive){targetX=clamp(targetX,player.r+5,W-player.r-5);targetY=clamp(targetY,H*.48,H*.9);player.x+=(targetX-player.x)*Math.min(1,dt*11);player.y+=(targetY-player.y)*Math.min(1,dt*11)}else if(dx||dy){player.x=clamp(player.x+dx*speed*dt,player.r+5,W-player.r-5);player.y=clamp(player.y+dy*speed*dt,H*.48,H*.9)}
 player.invuln=Math.max(0,player.invuln-dt);fireClock-=dt;if(fireClock<=0){fire();fireClock=.25}
 if(!boss){spawnClock-=dt;if(spawnClock<=0){spawnFormation();spawnClock=Math.max(.84,2.55-wave*.055)}}
 for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt}shots=shots.filter(s=>s.life>0&&s.y>-20);
 for(const e of enemies){e.phase+=dt*2.4;e.x=e.baseX+Math.sin(e.phase)*Math.min(W*.09,55);e.y+=e.speed*dt;e.fire-=dt;if(e.type==='scout'&&e.fire<=0&&e.y>30&&e.y<H*.75){enemyShots.push({x:e.x,y:e.y+e.r,vx:(player.x-e.x)*.22,vy:H*.32,r:5});e.fire=rand(2,3.3)}if(e.y>H+40)e.dead=true}
 for(const m of meteors){m.x+=m.vx*dt;m.y+=m.vy*dt;m.rot+=m.vr*dt}meteors=meteors.filter(m=>m.y<H+60);
 if(boss){boss.t+=dt;boss.y+=(boss.targetY-boss.y)*Math.min(1,dt*2);boss.x+=Math.sin(boss.t*1.25)*W*.2*dt;boss.x=clamp(boss.x,boss.r+5,W-boss.r-5);boss.fire-=dt;if(boss.fire<=0){for(let i=-2;i<=2;i++)enemyShots.push({x:boss.x+i*8,y:boss.y+boss.r*.55,vx:i*W*.055,vy:H*.32,r:6});boss.fire=Math.max(.65,1.2-wave*.012)}}
 for(const b of enemyShots){b.x+=b.vx*dt;b.y+=b.vy*dt}enemyShots=enemyShots.filter(b=>b.y<H+20&&b.x>-20&&b.x<W+20);
 for(const p of pickups){p.y+=p.vy*dt;p.phase+=dt*3}pickups=pickups.filter(p=>p.y<H+30);
 // Projectiles hit drones and boss.
 for(const s of shots){if(s.life<=0)continue;for(const e of enemies){if(e.dead)continue;if(Math.hypot(s.x-e.x,s.y-e.y)<e.r+s.r){s.life=0;e.hp--;addParticle(s.x,s.y,'#adf7ff',3,60);if(e.hp<=0)killEnemy(e);break}}if(boss&&s.life>0&&Math.hypot(s.x-boss.x,s.y-boss.y)<boss.r+s.r){s.life=0;boss.hp--;addParticle(s.x,s.y,'#ffe06a',3,70);if(boss.hp<=0){setScore(1200+wave*50);addParticle(boss.x,boss.y,'#ffb84d',50,330);toast='¡JEFE DERROTADO!';toastUntil=time+2;sound('explosion');boss=null}}}
 enemies=enemies.filter(e=>!e.dead);
 for(const e of enemies){if(Math.hypot(player.x-e.x,player.y-e.y)<player.r+e.r*.72)damage()}
 for(const m of meteors){if(Math.hypot(player.x-m.x,player.y-m.y)<player.r+m.r*.65){m.y=H+100;damage()}}
 for(const b of enemyShots){if(Math.hypot(player.x-b.x,player.y-b.y)<player.r+b.r){b.y=H+100;damage()}}
 if(boss&&Math.hypot(player.x-boss.x,player.y-boss.y)<player.r+boss.r*.7)damage();
 for(const p of pickups){if(!p.got&&Math.hypot(player.x-p.x,player.y-p.y)<player.r+p.r+4){p.got=true;if(p.type==='shield'){lives=Math.min(3,lives+1);livesEl.textContent='♥'.repeat(lives);toast='ESCUDO RECUPERADO';toastUntil=time+1.3}else{setScore(250);toast='+250';toastUntil=time+.8}sound('collect')}}pickups=pickups.filter(p=>!p.got);
 for(const p of particles){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985}particles=particles.filter(p=>p.age<p.life);shake=Math.max(0,shake-dt);flash=Math.max(0,flash-dt);if(state!=='playing')return
}
function rounded(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.sin(e.phase)*.1);const scout=e.type==='scout',w=e.r*2,h=e.r*1.35;const g=ctx.createLinearGradient(0,-h/2,0,h/2);if(scout){g.addColorStop(0,'#ff9eea');g.addColorStop(.45,'#b02bd4');g.addColorStop(1,'#572f96')}else{g.addColorStop(0,'#93f7ff');g.addColorStop(.48,'#277eb1');g.addColorStop(1,'#203a79')}ctx.shadowColor=scout?'#ed4bef':'#52ddff';ctx.shadowBlur=13;ctx.fillStyle=g;ctx.strokeStyle='#d5faff';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-w*.5,0);ctx.lineTo(-w*.25,-h*.35);ctx.lineTo(-w*.12,-h*.52);ctx.lineTo(0,-h*.28);ctx.lineTo(w*.12,-h*.52);ctx.lineTo(w*.25,-h*.35);ctx.lineTo(w*.5,0);ctx.lineTo(w*.22,h*.37);ctx.lineTo(0,h*.2);ctx.lineTo(-w*.22,h*.37);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=scout?'#ffdf81':'#b1faff';ctx.beginPath();ctx.ellipse(0,0,w*.25,h*.18,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#182149';ctx.beginPath();ctx.arc(-w*.1,0,2.4,0,Math.PI*2);ctx.arc(w*.1,0,2.4,0,Math.PI*2);ctx.fill();if(e.hp>1){ctx.fillStyle='#ffeb70';ctx.fillRect(-e.r,e.r*.82,e.r*2,3);ctx.fillStyle='#ff637d';ctx.fillRect(-e.r,e.r*.82,e.r*2*(e.hp/2),3)}ctx.restore()}
function drawMeteor(m){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(m.rot);ctx.shadowColor='#ff9e55';ctx.shadowBlur=12;const g=ctx.createLinearGradient(-m.r,-m.r,m.r,m.r);g.addColorStop(0,'#ffd494');g.addColorStop(.35,'#a66555');g.addColorStop(1,'#4b3553');ctx.fillStyle=g;ctx.strokeStyle='#ffc084';ctx.lineWidth=1.5;ctx.beginPath();for(let i=0;i<9;i++){const a=i*Math.PI*2/9,r=m.r*(.76+(i%3)*.1);if(i===0)ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);else ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#754c50';ctx.beginPath();ctx.arc(-m.r*.2,-m.r*.12,m.r*.16,0,Math.PI*2);ctx.arc(m.r*.29,m.r*.22,m.r*.12,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawBoss(){if(!boss)return;ctx.save();ctx.translate(boss.x,boss.y);const r=boss.r;ctx.shadowColor='#ee55bb';ctx.shadowBlur=25;const g=ctx.createLinearGradient(0,-r,0,r);g.addColorStop(0,'#ffb45c');g.addColorStop(.3,'#d24e8e');g.addColorStop(1,'#573087');ctx.fillStyle=g;ctx.strokeStyle='#ffdf93';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-r,-r*.18);ctx.lineTo(-r*.75,-r*.72);ctx.lineTo(-r*.22,-r*.48);ctx.lineTo(0,-r);ctx.lineTo(r*.22,-r*.48);ctx.lineTo(r*.75,-r*.72);ctx.lineTo(r,.0);ctx.lineTo(r*.65,r*.55);ctx.lineTo(0,r*.8);ctx.lineTo(-r*.65,r*.55);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#ffe87c';ctx.beginPath();ctx.ellipse(0,-r*.06,r*.35,r*.21,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#332456';ctx.fillRect(-r*.48,r*.95,r*.96,6);ctx.fillStyle='#ff566c';ctx.fillRect(-r*.48,r*.95,r*.96*(boss.hp/boss.maxHp),6);ctx.restore()}
function draw(){background(state==='playing'?Math.min(.04,(performance.now()-lastFrame)/1000):.008);ctx.save();if(shake>0)ctx.translate(rand(-5,5)*shake*4,rand(-4,4)*shake*4);
 for(const m of meteors)drawMeteor(m);for(const e of enemies)drawEnemy(e);drawBoss();
 for(const s of shots){ctx.shadowColor='#75efff';ctx.shadowBlur=16;const g=ctx.createLinearGradient(s.x,s.y,s.x,s.y+18);g.addColorStop(0,'#fff');g.addColorStop(.35,'#8fffff');g.addColorStop(1,'#398bff00');ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(s.x-s.r*.5,s.y-12,s.r,22,5);ctx.fill()}ctx.shadowBlur=0;
 for(const b of enemyShots){ctx.shadowColor='#ff6486';ctx.shadowBlur=12;ctx.fillStyle='#ff7596';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;
 for(const p of pickups){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.phase);ctx.shadowColor=p.type==='shield'?'#59edff':'#ffdf67';ctx.shadowBlur=16;ctx.fillStyle=p.type==='shield'?'#58d7f7':'#ffca47';ctx.beginPath();ctx.moveTo(0,-p.r);ctx.lineTo(p.r*.8,0);ctx.lineTo(0,p.r);ctx.lineTo(-p.r*.8,0);ctx.closePath();ctx.fill();ctx.shadowBlur=0;if(p.type==='shield'){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-4,-2);ctx.lineTo(0,4);ctx.lineTo(5,-5);ctx.stroke()}else drawStar(0,0,p.r*.55,0,'#fff1a2');ctx.restore()}
 for(const p of particles){const a=1-p.age/p.life;ctx.globalAlpha=a;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=12*a;ctx.beginPath();ctx.arc(p.x,p.y,p.r*a,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.shadowBlur=0;
 if(player&&(player.invuln<=0||Math.floor(time*14)%2===0))drawShip(ctx,player.x,player.y,Math.max(.68,Math.min(W,H)*.0012),Math.sin(time*18)*.45+.55);
 ctx.restore();if(boss){const bw=Math.min(W*.55,340),bx=(W-bw)/2;ctx.fillStyle='#14152f';rounded(ctx,bx,H*.105,bw,9,4);ctx.fillStyle='#ff6d9e';rounded(ctx,bx,H*.105,bw*(boss.hp/boss.maxHp),9,4);ctx.fillStyle='#fff1ba';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText('JEFE',W/2,H*.097)}
 if(toast&&time<toastUntil){ctx.save();ctx.textAlign='center';ctx.font='1000 '+clamp(W*.045,19,32)+'px system-ui';ctx.lineWidth=5;ctx.strokeStyle='#15102dcc';ctx.strokeText(toast,W/2,H*.24);ctx.fillStyle='#ffe990';ctx.shadowColor='#ffb84d';ctx.shadowBlur=14;ctx.fillText(toast,W/2,H*.24);ctx.restore()}if(flash>0){ctx.fillStyle='rgba(255,81,95,'+(flash*.45)+')';ctx.fillRect(0,0,W,H)}
}
function frame(t){const dt=Math.min(.04,Math.max(0,(t-lastFrame)/1000));lastFrame=t;update(dt);draw();if(state==='menu'||state==='over')drawHero();requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.__vladiGalaxia={get state(){return state},get metrics(){return{score,best,lives,wave,elapsed,enemies:enemies.length,boss:!!boss}},start,pause,spawnTestEnemy:(x,y,hp=1)=>enemies.push({type:'drone',x,y,baseX:x,r:22,hp,phase:0,speed:0,score:75,fire:99}),spawnTestMeteor:(x,y)=>meteors.push({x,y,r:18,vx:0,vy:0,rot:0,vr:0}),moveTo:(x,y)=>{if(player){player.x=x;player.y=y}},resize:()=>resize()};
})();
