import {Pinball,W,H,RAMPS,FLIPPERS,BUMPERS,ROOMS,rampPoint} from './engine.mjs?v=8';
let g=new Pinball(),best=0;try{best=Number(localStorage.getItem('vladi-pinball-best')||0)}catch{}const c=document.querySelector('#table'),screen=c.getContext('2d'),surface=document.createElement('canvas'),ctx=surface.getContext('2d'),arena=document.querySelector('#arena'),overlay=document.querySelector('#overlay');let view={},background,prev=0,acc=0,muted=false,audio,flash=0,notice='',noticeUntil=0,lastLevel=0,lastHUD=0,staticKey="",staticBoard;
surface.width=W;surface.height=H;
const playfield=new Image();playfield.src='assets/playfield-v3.webp';playfield.onload=()=>{background=null;staticKey=""};
function resize(){const r=arena.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);view={w:r.width,h:r.height,d,s:Math.min(r.width/W,r.height/H)};view.x=(r.width-W*view.s)/2;view.y=(r.height-H*view.s)/2;background=null;staticKey=""}new ResizeObserver(resize).observe(arena);window.visualViewport?.addEventListener('resize',resize);addEventListener('resize',resize);
function path(points,color,width=4){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke()}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}}
function label(text,x,y,size=15,color='#efd08c'){ctx.font='900 '+size+'px Arial';ctx.fillStyle=color;ctx.textAlign='center';ctx.strokeStyle='#080b17';ctx.lineWidth=4;ctx.strokeText(text,x,y);ctx.fillText(text,x,y)}
function base(){background=document.createElement('canvas');background.width=W;background.height=H;const b=background.getContext('2d');b.fillStyle='#192235';b.fillRect(0,0,W,H);if(playfield.complete&&playfield.naturalWidth)b.drawImage(playfield,0,0,W,H);const wash=b.createLinearGradient(0,0,0,H);wash.addColorStop(0,'#06132855');wash.addColorStop(.48,'#03122838');wash.addColorStop(.74,'#06132710');wash.addColorStop(1,'#03142666');b.fillStyle=wash;b.fillRect(0,0,W,H);if(g.level>1){b.fillStyle=['#62409b12','#16546612','#96452212'][(g.level-2)%3];b.fillRect(0,0,W,H)}for(const x of [8,581]){const wood=b.createLinearGradient(x,0,x+12,0);wood.addColorStop(0,'#38242c');wood.addColorStop(.5,'#ad7851');wood.addColorStop(1,'#402b37');b.fillStyle=wood;b.fillRect(x,0,12,H);for(let y=30;y<H;y+=68){b.fillStyle='#e4bd86';b.beginPath();b.arc(x+6,y,3,0,7);b.fill()}}}
function rampShape(kind){ctx.beginPath();for(let n=0;n<=90;n++){const p=rampPoint(kind,n/90);n?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H);if(!background)base();const key=[g.targets,g.room,g.progress,g.locks,g.multi,g.level].join(":");if(!staticBoard||staticKey!==key){ctx.drawImage(background,0,0);
 for(let n=0;n<10;n++){const y=90+n*73,lit=(n+Math.floor(g.time*3))%4===0;for(const x of [24,570]){ctx.save();ctx.shadowColor='#a9e6ff';ctx.shadowBlur=lit?14:0;circle(x,y,3,lit?'#edffc1':'#8e6752');ctx.restore()}}const rails=[[[45,640],[85,675]],[[45,800],[140,830]],[[45,800],[35,220],[80,70],[490,45],[565,90],[575,955]],[[520,180],[520,955]],[[45,800],[100,905]],[[510,800],[460,905]],[[105,747],[140,785],[140,830],[150,844]],[[450,844],[455,830],[455,785],[490,747]]];for(const rail of rails){path(rail,'#020914',14);path(rail,'#657784',8);path(rail,'#edf5eb',2)}
 // Translucent elevated ramps, with chrome edges and legs.
 for(let kind=0;kind<2;kind++){const colors=kind?['#68b7d2','#c2f3ff']:['#ba9152','#ffefab'];ctx.save();ctx.translate(4,8);rampShape(kind);ctx.strokeStyle='#020817aa';ctx.lineWidth=31;ctx.stroke();ctx.restore();for(let t=.12;t<.96;t+=.16){const p=rampPoint(kind,t);path([[p.x,p.y],[p.x+6,p.y+19]],'#8c8f90',3);circle(p.x+6,p.y+19,4,'#747d80','#cfd5c7')}rampShape(kind);ctx.strokeStyle=colors[0];ctx.lineWidth=29;ctx.stroke();ctx.strokeStyle='#101c2999';ctx.lineWidth=23;ctx.stroke();ctx.strokeStyle=kind?'#91e4f366':'#fee19366';ctx.lineWidth=19;ctx.stroke();ctx.strokeStyle=colors[1];ctx.lineWidth=2;ctx.stroke();const [x,y]=RAMPS[kind][0];const lit=ROOMS[g.room][1]==='ramp'+kind||ROOMS[g.room][1]==='ramp'||g.multi;ctx.save();ctx.shadowColor=colors[1];ctx.shadowBlur=lit?20:0;circle(x,y+8,10,lit?colors[1]:'#475862','#edf1be');ctx.restore();label(kind?'RELOJ':'BIBLIOTECA',x,y+34,10,colors[1]);}
 for(let i=0;i<4;i++){const x=110+i*100,on=g.targets&(1<<i);ctx.save();ctx.shadowBlur=on?18:0;ctx.shadowColor='#c7ff85';ctx.beginPath();ctx.roundRect(x-23,140,46,48,17);ctx.fillStyle='#21192ddd';ctx.fill();ctx.strokeStyle=on?'#e5ff97':'#be9360';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=on?'#caff94':'#584169';ctx.fillRect(x-14,150,28,27);path([[x,150],[x,177]],'#1d202e',3);path([[x-14,164],[x+14,164]],'#1d202e',3);label(['L','U','N','A'][i],x,200,11,on?'#d5ffa1':'#ecd0a7');ctx.restore()}
 for(let i=0;i<BUMPERS.length;i++){const[x,y]=BUMPERS[i];ctx.save();ctx.shadowBlur=5;ctx.shadowColor=['#b697ef','#8df5c0','#ffd783'][i%3];circle(x+4,y+6,33,'#030b17');circle(x,y,30,'#b5c8cb','#edeecc');const rg=ctx.createRadialGradient(x-9,y-10,2,x,y,28);rg.addColorStop(0,['#d6b4ff','#bfffdc','#ffe59a'][i%3]);rg.addColorStop(1,['#5e287d','#1e6b65','#925228'][i%3]);circle(x,y,26,rg,'#f1d19c');circle(x,y,15,'#21182ddd','#c6b8a1');label(['☾','✦','★','✧','♜'][i],x,y+6,19);for(let a=0;a<6;a++){circle(x+20*Math.cos(a*Math.PI/3),y+20*Math.sin(a*Math.PI/3),1.5,'#fff3b6')}ctx.restore()}
 // Mansion book targets and the ball-lock vault.
 for(let i=0;i<3;i++){const x=205+i*65;ctx.save();ctx.translate(x,520);ctx.beginPath();ctx.roundRect(-15,-15,30,30,3);ctx.fillStyle=['#8b466d','#517e6b','#826d36'][i];ctx.fill();ctx.strokeStyle='#dfc088';ctx.lineWidth=3;ctx.stroke();path([[-10,-10],[10,10]],'#efdfa744',2);label(['I','II','III'][i],0,5,12);ctx.restore()}
 ctx.save();ctx.fillStyle='#452b3d';ctx.fillRect(449,418,62,75);ctx.fillStyle='#a37347';ctx.fillRect(446,415,62,75);ctx.strokeStyle='#f0cd91';ctx.lineWidth=3;ctx.strokeRect(446,415,62,75);for(let n=0;n<5;n++){ctx.fillStyle=['#5d8f74','#7b4f7b','#9d6453'][n%3];ctx.fillRect(451+n*10,420,7,25)}path([[448,448],[506,448]],'#e2c38b',4);ctx.restore();circle(480,465,30,'#252338','#dab270');circle(480,465,23,'#020612','#8b6e52');label('BÓVEDA',479,511,10);for(let i=0;i<3;i++)circle(458+i*19,495,5,g.locks>i?'#acffba':'#54455a','#d3ba80');
 const slings=[[[85,675],[155,740],[78,747]],[[515,675],[450,740],[515,747]]];for(const pts of slings){ctx.save();ctx.shadowColor='#05091a';ctx.shadowBlur=8;ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle='#302351bb';ctx.fill();ctx.strokeStyle='#d4b2e6';ctx.lineWidth=7;ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#fff0bc';ctx.lineWidth=2;ctx.stroke();const x=pts[0][0]+(pts[0][0]<300?15:-15),y=pts[0][1]+42;circle(x,y,5,'#d9ffc9');ctx.restore()}
 for(let room=0;room<8;room++){const x=231+(room%4)*46,y=649+Math.floor(room/4)*37,lit=room<g.room,active=room===g.room;ctx.save();ctx.shadowColor='#c3ffc1';ctx.shadowBlur=active?12:0;ctx.beginPath();ctx.roundRect(x-16,y-14,32,28,[12,12,2,2]);ctx.fillStyle=lit?'#a8dc65':active?'#ffd76b':'#241b35cc';ctx.fill();ctx.strokeStyle='#ead2a0';ctx.lineWidth=2;ctx.stroke();label(String(room+1),x,y+5,11,lit||active?'#253224':'#e0cba1');ctx.restore()}ctx.save();ctx.fillStyle='#101b2ac9';ctx.beginPath();ctx.roundRect(175,737,250,55,9);ctx.fill();label(ROOMS[g.room][0]+' · '+g.progress+'/'+ROOMS[g.room][2],300,758,14,'#ffe6a2');label(g.multi?'MULTIBOLA · JACKPOT EN LAS RAMPAS':'MANSIÓN '+g.level+' · '+(g.room+1)+'/8 HABITACIONES',300,780,10,'#b8f1d2');ctx.restore();
 if(!staticBoard){staticBoard=document.createElement("canvas");staticBoard.width=W;staticBoard.height=H}staticBoard.getContext("2d").drawImage(surface,0,0);staticKey=key;}else ctx.drawImage(staticBoard,0,0);
 for(let i=0;i<FLIPPERS.length;i++){const f=FLIPPERS[i],angle=g.angles[i];ctx.save();ctx.translate(f.x,f.y);ctx.rotate(angle);ctx.shadowColor='#02040d';ctx.shadowBlur=6;ctx.shadowOffsetY=7;ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(f.len-10,-9);ctx.arc(f.len-10,0,9,-Math.PI/2,Math.PI/2);ctx.lineTo(0,12);ctx.arc(0,0,12,Math.PI/2,Math.PI*1.5);ctx.closePath();ctx.fillStyle='#401d36';ctx.fill();ctx.strokeStyle='#f3d9bb';ctx.lineWidth=5;ctx.stroke();ctx.shadowBlur=0;ctx.shadowOffsetY=0;const fg=ctx.createLinearGradient(0,-10,0,10);fg.addColorStop(0,'#ffefb7');fg.addColorStop(.5,'#e1a952');fg.addColorStop(1,'#99623b');ctx.fillStyle=fg;ctx.fill();path([[2,-8],[f.len-16,-4]],'#fff8d6',2);circle(0,0,5,'#5e4051','#c9ad8d');ctx.restore()}
 for(let y=950;y>915-g.charge*45;y-=6)path([[540,y],[564,y-3]],'#deb675',3);path([[552,920],[552,965]],'#dbc3a0',7);circle(552,966,13,'#865772','#e6ba82');
 for(const b of g.balls){if(b.capture)continue;ctx.save();circle(b.x+3,b.y+5,b.r+1,'#031021aa');ctx.shadowColor='#b6ffe0';ctx.shadowBlur=b.ramp?12:2;const gr=ctx.createRadialGradient(b.x-3,b.y-4,1,b.x,b.y,10);gr.addColorStop(0,'#fff');gr.addColorStop(.22,'#f5fff4');gr.addColorStop(.6,'#94bdc2');gr.addColorStop(1,'#283944');circle(b.x,b.y,b.r,gr);ctx.restore()}
 if(g.tilt)label('¡TILT! SOLTÁ LOS FLIPPERS',300,815,17,'#ff8b80');screen.setTransform(view.d,0,0,view.d,0,0);screen.clearRect(0,0,view.w,view.h);screen.translate(view.x,view.y);screen.scale(view.s,view.s);for(let y=0;y<H;y+=12){const factor=.86+.14*y/H;screen.drawImage(surface,0,y,W,Math.min(12,H-y),(W-W*factor)/2,y,W*factor,Math.min(12,H-y)+.6)}
}
function tone(f,d=.12,type='sine',vol=.07){if(muted||!audio)return;const o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(vol,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function announce(t){notice=t;noticeUntil=g.time+3}
function updateUI(){document.querySelector('#score').textContent=g.score.toLocaleString('es-AR');document.querySelector('#best').textContent=best.toLocaleString('es-AR');document.querySelector('#lives').textContent='● '.repeat(Math.max(0,g.lives)).trim()||'—';const waiting=g.balls.some(b=>b.waiting);document.querySelector('#launch').textContent=waiting?(g.charge?'SOLTÁ':'LANZAR'):'GOLPE';document.querySelector('#status').textContent=noticeUntil>g.time?notice:waiting?'Mantené y soltá LANZAR':ROOMS[g.room][3]+' · '+g.progress+'/'+ROOMS[g.room][2];overlay.hidden=g.state==='playing';if(g.state==='paused'){document.querySelector('#title').innerHTML='EN <span>PAUSA</span>';document.querySelector('#message').textContent='La mansión te espera. Continuá tu partida.';document.querySelector('#start').textContent='CONTINUAR'}else if(g.state==='over'){document.querySelector('#title').innerHTML='FIN DE <span>PARTIDA</span>';document.querySelector('#message').textContent='Sumaste '+g.score.toLocaleString('es-AR')+' puntos. ¡Volvé a despertar la mansión!';document.querySelector('#start').textContent='VOLVER A JUGAR'}}
function clear(){g.keys={};document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'))}
function pause(){if(g.state==='playing'){g.state='paused';clear()}else if(g.state==='paused')g.state='playing';updateUI()}
document.querySelector('#start').onclick=()=>{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();if(g.state==='over'){g=new Pinball();background=null}if(g.state==='paused')g.state='playing';else g.start();clear();updateUI()};document.querySelector('#pause').onclick=pause;document.querySelector('#full').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{}};document.querySelector('#sound').onclick=()=>{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();muted=!muted;document.querySelector('#sound').setAttribute('aria-label',muted?'Activar sonido':'Silenciar sonido');document.querySelector('#sound').textContent=muted?'♫':'♪'};
for(const id of ['left','right','launch']){const el=document.querySelector('#'+id);el.oncontextmenu=e=>e.preventDefault();el.onselectstart=e=>e.preventDefault();el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);if(g.state!=='playing')return;el.classList.add('held');if(id==='launch'&&!g.balls.some(b=>b.waiting))g.nudge();else g.keys[id]=true};const release=()=>{el.classList.remove('held');if(id==='launch'&&g.keys.launch)g.plunge();g.keys[id]=false};el.onpointerup=release;el.onpointercancel=()=>{g.keys[id]=false;el.classList.remove('held')};el.onlostpointercapture=()=>{g.keys[id]=false;el.classList.remove('held')}}
const keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'launch'};addEventListener('keydown',e=>{const k=keyMap[e.code];if(k){e.preventDefault();if(g.state==='playing')g.keys[k]=true}else if(!e.repeat&&(e.code==='Escape'||e.code==='KeyP'))pause();else if(!e.repeat&&e.code==='KeyN')g.nudge()});addEventListener('keyup',e=>{const k=keyMap[e.code];if(k==='launch'&&g.keys.launch)g.plunge();if(k)g.keys[k]=false});addEventListener('blur',()=>{if(g.state==='playing')pause();clear()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.state==='playing')pause()});
let musicAt=0;function loop(now){const dt=prev?Math.min(.1,(now-prev)/1000):0;prev=now;acc+=dt;while(acc>=1/240){g.update(1/240);acc-=1/240}flash=Math.max(0,flash-dt);for(const e of g.events.splice(0)){if(e==='bumper'){tone(650,.12,'triangle',.11);flash=.18}if(e==='nudge'){tone(65,.10,'triangle',.10);c.animate([{transform:'translate(0,0)'},{transform:'translate(-4px,2px)'},{transform:'translate(4px,-2px)'},{transform:'translate(0,0)'}],{duration:180});announce('¡GOLPE A LA MESA!')}if(e==='sling')tone(180,.07,'triangle',.09);if(e==='rollover')tone(1200,.05,'sine',.05);if(e==='flip')tone(110,.035,'triangle',.045);if(e==='launch')tone(220,.22,'sawtooth',.055);if(e==='target')tone(880,.2);if(e==='lost')tone(90,.5,'triangle',.10);if(e==='save')announce('¡BOLA SALVADA! LANZÁ DE NUEVO');if(e==='multi'){announce('¡MULTIBOLA! TRES BOLAS EN JUEGO');tone(1047,.5,'triangle',.1)}if(e==='ramp0'||e==='ramp1'){announce(g.multi?'¡JACKPOT DE RAMPA! +10.000':'¡RAMPA COMPLETA! +2000');tone(784,.4)}if(e==='scoop'){announce('¡BÓVEDA ABIERTA! +1500');tone(523,.3)}if(e==='room'){announce('¡HABITACIÓN SUPERADA! +3000');tone(880,.3)}if(e==='windows'){announce('¡LUNA COMPLETA! +3000 · BÓVEDA '+g.locks+'/3');tone(660,.3)}if(e==='skill'){announce('¡TIRO DE HABILIDAD! +1500');tone(990,.3)}if(e==='level'){background=null;staticKey='';announce('¡MANSIÓN '+g.level+'! +10.000 Y UNA BOLA');tone(1175,.5)}if(e==='tilt')announce('¡TILT! DEMASIADOS EMPUJONES')}
if(g.score>best){best=g.score;try{localStorage.setItem('vladi-pinball-best',best)}catch{}}if(g.level!==lastLevel){lastLevel=g.level;background=null}if(now-lastHUD>120){updateUI();lastHUD=now}if(audio&&!muted&&g.state==='playing'&&now>musicAt){musicAt=now+600;const notes=[196,233,293,220,196,261,233,174];tone(notes[Math.floor(now/600)%8],.45,'triangle',.027)}draw();requestAnimationFrame(loop)}resize();updateUI();requestAnimationFrame(loop);
