import {Pinball,W,H} from './engine.mjs?v=1';
let g=new Pinball(),best=0;try{best=Number(localStorage.getItem('vladi-pinball-best')||0)}catch{}const c=document.querySelector('#table'),ctx=c.getContext('2d'),arena=document.querySelector('#arena'),overlay=document.querySelector('#overlay');let view={},background,prev=0,acc=0,muted=false,audio,flash=0,notice='',noticeUntil=0,lastLevel=0,lastHUD=0;
const portrait=new Image();portrait.src='../assets/halloween-maze-480w.webp';portrait.onload=()=>{background=null};
function resize(){const r=arena.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);view={w:r.width,h:r.height,d,s:Math.min(r.width/W,r.height/H)};view.x=(r.width-W*view.s)/2;view.y=(r.height-H*view.s)/2;background=null}new ResizeObserver(resize).observe(arena);window.visualViewport?.addEventListener('resize',resize);addEventListener('resize',resize);
function path(points,color,width=4){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke()}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}}
function label(text,x,y,size=15,color='#efd08c'){ctx.font='900 '+size+'px Arial';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,x,y)}
function base(){background=document.createElement('canvas');background.width=W;background.height=H;const b=background.getContext('2d');const colors=[['#28233d','#071c21','#72d4ac'],['#392346','#17122d','#b393ee'],['#382b28','#151c25','#e5bd72'],['#182b43','#0a1525','#8bd9f2']][(g.level-1)%4];const gr=b.createLinearGradient(0,0,600,1000);gr.addColorStop(0,colors[0]);gr.addColorStop(.7,colors[1]);gr.addColorStop(1,'#110e1c');b.fillStyle=gr;b.fillRect(0,0,W,H);
 // Cabinet with wood, metal rails and ornamental rivets.
 for(const x of [8,581]){const wood=b.createLinearGradient(x,0,x+12,0);wood.addColorStop(0,'#38242c');wood.addColorStop(.5,'#ad7851');wood.addColorStop(1,'#402b37');b.fillStyle=wood;b.fillRect(x,0,12,H);for(let y=30;y<H;y+=68){b.fillStyle='#e4bd86';b.beginPath();b.arc(x+6,y,3,0,7);b.fill()}}
 for(let y=80;y<950;y+=36)for(let x=30;x<570;x+=65){b.fillStyle=(x+y)%3?'#ceb7cf08':'#00000014';b.fillRect(x+(y%72?25:0),y,61,32)}
 b.fillStyle='#171221';b.beginPath();b.moveTo(80,245);b.lineTo(80,110);b.lineTo(135,75);b.lineTo(160,125);b.lineTo(300,30);b.lineTo(440,125);b.lineTo(465,75);b.lineTo(515,110);b.lineTo(515,245);b.closePath();b.fill();b.strokeStyle='#947b8c';b.lineWidth=3;b.stroke();
 for(let x=115;x<500;x+=64){b.fillStyle=colors[2]+'55';b.fillRect(x,140,25,50);b.fillStyle='#302135';b.fillRect(x+10,140,4,50);b.fillRect(x,162,25,4)}
 b.strokeStyle='#6b566d';b.lineWidth=3;for(let x=40;x<560;x+=34){b.beginPath();b.moveTo(x,650);b.lineTo(x,730);b.moveTo(x-6,665);b.lineTo(x,650);b.lineTo(x+6,665);b.stroke()}
 b.fillStyle='#bacbd911';for(let i=0;i<18;i++){const x=75+i*24,y=500+Math.sin(i)*40;b.beginPath();b.ellipse(x,y,65,15,0,0,7);b.fill()}
 // Illustrated carpet and central crest, rather than a website panel.
 b.save();b.translate(300,570);b.rotate(Math.PI/4);b.fillStyle='#6d315e44';b.fillRect(-100,-100,200,200);b.strokeStyle='#bd915755';b.lineWidth=6;b.strokeRect(-100,-100,200,200);b.restore();if(portrait.complete&&portrait.naturalWidth){b.save();b.beginPath();b.moveTo(300,445);b.lineTo(460,550);b.lineTo(300,675);b.lineTo(140,550);b.closePath();b.clip();b.globalAlpha=.9;b.drawImage(portrait,140,445,320,214);b.restore()}b.textAlign='center';b.font='900 30px Georgia';b.fillStyle='#d4b77d';b.fillText('VLADI',300,661);b.font='900 38px Georgia';b.fillText('PINBALL',300,698);b.font='bold 11px Arial';b.fillStyle='#a6cfb6';b.fillText('LA MANSIÓN MISTERIOSA',300,717);
 b.strokeStyle='#b6d3bd66';b.lineWidth=2;for(const [x,y] of [[58,350],[508,550]]){b.beginPath();b.arc(x,y,46,0,7);b.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;b.beginPath();b.moveTo(x,y);b.lineTo(x+46*Math.cos(a),y+46*Math.sin(a));b.stroke()}}
}
function draw(){ctx.setTransform(view.d,0,0,view.d,0,0);ctx.clearRect(0,0,view.w,view.h);ctx.translate(view.x,view.y);ctx.scale(view.s,view.s);if(!background)base();ctx.drawImage(background,0,0);
 const rails=[[[45,800],[35,220],[80,70],[490,45],[565,90],[575,955]],[[520,180],[520,940]],[[45,800],[110,895]],[[510,800],[445,895]]];for(const rail of rails){path(rail,'#050c14',15);path(rail,'#697582',9);path(rail,'#ccd1cf',3)}
 // Raised loop ramp with separate entry and return.
 ctx.save();ctx.strokeStyle='#090d17';ctx.lineWidth=25;ctx.beginPath();ctx.ellipse(300,275,205,180,0,Math.PI*.6,Math.PI*2.7);ctx.stroke();ctx.strokeStyle='#94774f';ctx.lineWidth=19;ctx.stroke();ctx.strokeStyle='#ead5a066';ctx.lineWidth=11;ctx.stroke();ctx.strokeStyle='#faf2c1';ctx.lineWidth=2;ctx.stroke();ctx.restore();path([[98,420],[100,370],[126,333]],'#e5c97f',6);label('RAMPA',95,445,12,'#a3f5c3');
 for(let i=0;i<4;i++){const x=105+i*110,on=g.targets&(1<<i);ctx.save();ctx.shadowBlur=on?20:0;ctx.shadowColor='#c7ff85';ctx.fillStyle=on?'#d3ff91':'#49385a';ctx.strokeStyle='#e7c776';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(x-21,158,42,38,10);ctx.fill();ctx.stroke();ctx.restore();label(['L','U','N','A'][i],x,184,18,on?'#213228':'#bdafa5')}
 for(const [i,x,y] of [[0,210,295],[1,365,280],[2,295,405]]){ctx.save();ctx.shadowBlur=flash>0?25:10;ctx.shadowColor=['#b187ee','#7edca1','#e2bb66'][i];circle(x,y,38,'#18131f','#a381bd');const rg=ctx.createRadialGradient(x-10,y-13,4,x,y,33);rg.addColorStop(0,['#d2b0f5','#c5ffc9','#fff1ae'][i]);rg.addColorStop(1,['#59377b','#285c46','#8c5c32'][i]);circle(x,y,30,rg,'#e2cc95');circle(x,y,18,'#302139','#b6a088');label(['☾','★','✦'][i],x,y+8,25,'#f2e3b4');ctx.restore()}
 circle(485,490,26,'#080914','#b1915b');label('ESCONDITE',463,539,10);label('1200',485,494,11,'#b6f6c9');
 for(const pts of [[[85,680],[165,735],[80,745]],[[515,680],[465,735],[510,745]]]){ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle='#61387b';ctx.fill();ctx.strokeStyle='#ccb0ec';ctx.lineWidth=4;ctx.stroke();path([pts[0],pts[1]],'#9af3c5',7)}
 // Inlanes and drain are deliberately clear.
 path([[110,770],[135,795],[135,840]],'#a9bfbd',4);path([[455,770],[465,795],[465,840]],'#a9bfbd',4);label('MANSIÓN '+g.level,300,754,14,'#e6c58b');label(g.save>0?'BOLA SALVADA · '+Math.ceil(g.save)+'s':g.balls.length>1?'MULTIBOLA':'ENCENDÉ L · U · N · A',300,783,12,'#a7e9be');
 for(let i=0;i<2;i++){const x=i?440:160,y=845,a=g.angles[i];ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.shadowColor='#040811';ctx.shadowBlur=4;ctx.shadowOffsetY=6;ctx.beginPath();ctx.roundRect(-13,-14,123,28,14);ctx.fillStyle='#c6aa74';ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.beginPath();ctx.roundRect(-8,-10,112,20,10);const fg=ctx.createLinearGradient(0,-10,0,10);fg.addColorStop(0,'#fff1bc');fg.addColorStop(1,'#d38a45');ctx.fillStyle=fg;ctx.fill();circle(0,0,6,'#674c58','#e1d4c3');ctx.restore()}
 for(let y=950;y>915-g.charge*45;y-=6)path([[540,y],[564,y-3]],'#deb675',3);path([[552,920],[552,965]],'#dbc3a0',7);circle(552,966,13,'#865772','#e6ba82');
 for(const b of g.balls){ctx.save();ctx.shadowColor='#afffda';ctx.shadowBlur=b.ramp?18:5;const gr=ctx.createRadialGradient(b.x-3,b.y-4,1,b.x,b.y,10);gr.addColorStop(0,'#fff');gr.addColorStop(.25,'#ecf5ee');gr.addColorStop(.65,'#99aeb0');gr.addColorStop(1,'#36445b');circle(b.x,b.y,10,gr);ctx.restore()}
 if(g.tilt)label('¡TILT! SOLTÁ LOS FLIPPERS',300,710,20,'#ff8b80');
}
function tone(f,d=.12,type='sine',vol=.07){if(muted||!audio)return;const o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(vol,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function announce(t){notice=t;noticeUntil=g.time+3}
function updateUI(){document.querySelector('#score').textContent=g.score.toLocaleString('es-AR');document.querySelector('#best').textContent=best.toLocaleString('es-AR');document.querySelector('#lives').textContent='● '.repeat(Math.max(0,g.lives)).trim()||'—';const waiting=g.balls.some(b=>b.waiting);document.querySelector('#launch').textContent=waiting?(g.charge?'SOLTÁ':'LANZAR'):'EMPUJÓN';document.querySelector('#status').textContent=noticeUntil>g.time?notice:waiting?'Mantené y soltá LANZAR':'L · U · N · A: 4 ventanas para MULTIBOLA';overlay.hidden=g.state==='playing';if(g.state==='paused'){document.querySelector('#title').innerHTML='EN <span>PAUSA</span>';document.querySelector('#message').textContent='La mansión te espera. Continuá tu partida.';document.querySelector('#start').textContent='CONTINUAR'}else if(g.state==='over'){document.querySelector('#title').innerHTML='FIN DE <span>PARTIDA</span>';document.querySelector('#message').textContent='Sumaste '+g.score.toLocaleString('es-AR')+' puntos. ¡Volvé a despertar la mansión!';document.querySelector('#start').textContent='VOLVER A JUGAR'}}
function clear(){g.keys={};document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'))}
function pause(){if(g.state==='playing'){g.state='paused';clear()}else if(g.state==='paused')g.state='playing';updateUI()}
document.querySelector('#start').onclick=()=>{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();if(g.state==='over'){g=new Pinball();background=null}if(g.state==='paused')g.state='playing';else g.start();clear();updateUI()};document.querySelector('#pause').onclick=pause;document.querySelector('#full').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{}};document.querySelector('#sound').onclick=()=>{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume();muted=!muted;document.querySelector('#sound').setAttribute('aria-label',muted?'Activar sonido':'Silenciar sonido');document.querySelector('#sound').textContent=muted?'♫':'♪'};
for(const id of ['left','right','launch']){const el=document.querySelector('#'+id);el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);if(g.state!=='playing')return;el.classList.add('held');if(id==='launch'&&!g.balls.some(b=>b.waiting))g.nudge();else g.keys[id]=true};const release=()=>{el.classList.remove('held');if(id==='launch'&&g.keys.launch)g.plunge();g.keys[id]=false};el.onpointerup=release;el.onpointercancel=()=>{g.keys[id]=false;el.classList.remove('held')};el.onlostpointercapture=()=>{g.keys[id]=false;el.classList.remove('held')}}
const keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'launch'};addEventListener('keydown',e=>{const k=keyMap[e.code];if(k){e.preventDefault();if(g.state==='playing')g.keys[k]=true}else if(!e.repeat&&(e.code==='Escape'||e.code==='KeyP'))pause();else if(!e.repeat&&e.code==='KeyN')g.nudge()});addEventListener('keyup',e=>{const k=keyMap[e.code];if(k==='launch'&&g.keys.launch)g.plunge();if(k)g.keys[k]=false});addEventListener('blur',()=>{if(g.state==='playing')pause();clear()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.state==='playing')pause()});
let musicAt=0;function loop(now){const dt=prev?Math.min(.1,(now-prev)/1000):0;prev=now;acc+=dt;while(acc>=1/240){g.update(1/240);acc-=1/240}flash=Math.max(0,flash-dt);for(const e of g.events.splice(0)){if(e==='bumper'){tone(650,.12,'triangle',.11);flash=.18}if(e==='flip')tone(110,.035,'triangle',.045);if(e==='launch')tone(220,.22,'sawtooth',.055);if(e==='target')tone(880,.2);if(e==='lost')tone(90,.5,'triangle',.10);if(e==='save')announce('¡BOLA SALVADA! LANZÁ DE NUEVO');if(e==='multi'){announce('¡MULTIBOLA! TRES BOLAS EN JUEGO');tone(1047,.5,'triangle',.1)}if(e==='ramp'){announce('¡RAMPA COMPLETA! +2500');tone(784,.4)}if(e==='scoop'){announce('¡ENCONTRASTE EL ESCONDITE! +1200');tone(523,.3)}if(e==='level'){background=null;announce('¡MANSIÓN '+g.level+' DESPERTADA! +3000');tone(1175,.5)}if(e==='tilt')announce('¡TILT! DEMASIADOS EMPUJONES')}
if(g.score>best){best=g.score;try{localStorage.setItem('vladi-pinball-best',best)}catch{}}if(g.level!==lastLevel){lastLevel=g.level;background=null}if(now-lastHUD>120){updateUI();lastHUD=now}if(audio&&!muted&&g.state==='playing'&&now>musicAt){musicAt=now+600;const notes=[196,233,293,220,196,261,233,174];tone(notes[Math.floor(now/600)%8],.45,'triangle',.027)}draw();requestAnimationFrame(loop)}resize();updateUI();requestAnimationFrame(loop);
