
(()=>{'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),sprite=new Image(),trackArt=new Image(),rivalArt=[2,3,4].map(()=>new Image());sprite.src='assets/vladi-kart.webp';trackArt.src='assets/circuit.webp';rivalArt.forEach((img,i)=>img.src=`assets/rival-${i+2}.webp`);const $=s=>document.querySelector(s),hud=$('#hud'),overlay=$('#overlay'),title=$('#title'),subtitle=$('#subtitle'),chips=$('#chips'),help=$('#help'),start=$('#start'),pause=$('#pause'),controlBox=$('.controls');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);let W=0,H=0,DPR=1,state='menu',last=0,clock=0,player={lane:0,turn:0},rivals=[],boxes=[],fx=[],distance=0,speed=0,lapLength=560,raceLength=1680,boosts=1,boostTime=0,drift=0,driftPaid=false,elapsed=0,nextBox=70,collisionWait=0,shake=0,finishPlace=0,best=+(localStorage.getItem('vladiKartBest')||0),toast='',toastEnd=0;const keys={};
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize,{passive:true});resize();
// Una combinación de curvas largas y enlazadas hace que el trazado cambie de
// dirección durante toda la carrera. La cámara proyecta la carretera hasta el
// horizonte real; antes se cerraba a los 520 m y quedaba un borde plano visible.
function curve(d){return 1.25*Math.sin(d*Math.PI*2/lapLength)}function proj(z){const p=1/(1+z/230),hy=H*(H>W*1.15?.43:.38),y=hy+(H-hy)*p,half=W*(.018+.41*p),t=clamp((z-1000)/800,0,1),fade=1-t*t*(3-2*t),x=W/2+(curve(distance+z)-curve(distance))*W*.115*p*fade;return{x,y,half,p}}
function poly(points,fill,stroke,lw=1){ctx.beginPath();ctx.moveTo(...points[0]);for(let i=1;i<points.length;i++)ctx.lineTo(...points[i]);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.lineWidth=lw;ctx.strokeStyle=stroke;ctx.stroke()}}function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.lineWidth=2;ctx.strokeStyle=stroke;ctx.stroke()}}
function background(t){ctx.fillStyle='#72c9f4';ctx.fillRect(0,0,W,H);if(!trackArt.complete||!trackArt.naturalWidth)return;const iw=trackArt.naturalWidth,ih=trackArt.naturalHeight,portrait=H>W*1.15;if(portrait){const sourceW=Math.min(iw,ih*(W/H)*1.32),sx=(iw-sourceW)/2;ctx.drawImage(trackArt,sx,0,sourceW,ih,0,0,W,H)}else{const scale=Math.max(W/iw,H/ih),dw=iw*scale,dh=ih*scale;ctx.drawImage(trackArt,(W-dw)/2,0,dw,dh)}}
function road(){const zMax=12000,steps=600;const samples=[];for(let i=steps;i>=0;i--){const z=zMax*i/steps;samples.push({z,...proj(z)})}const asphalt=ctx.createLinearGradient(0,H*.38,0,H);asphalt.addColorStop(0,'#53636a');asphalt.addColorStop(.45,'#343e45');asphalt.addColorStop(1,'#242d34');ctx.beginPath();for(const s of samples)ctx.lineTo(s.x-s.half,s.y);for(let i=samples.length-1;i>=0;i--){const s=samples[i];ctx.lineTo(s.x+s.half,s.y)}ctx.closePath();ctx.fillStyle=asphalt;ctx.fill();
 for(let z=(10-distance%10)%10;z<1000;z+=10){const a=proj(z),b=proj(z+6),odd=Math.floor((distance+z)/10)%2;for(const side of [-1,1]){const innerA=a.half*1.01,outerA=a.half*1.13,innerB=b.half*1.01,outerB=b.half*1.13;poly([[a.x+side*innerA,a.y],[a.x+side*outerA,a.y],[b.x+side*outerB,b.y],[b.x+side*innerB,b.y]],odd?'#f7f3e7':'#e74738');const seam=Math.max(1,a.p*2);ctx.fillStyle='#332d2b77';ctx.fillRect(a.x+side*(innerA+seam),a.y,seam,Math.max(1,b.y-a.y))}}
 for(let z=(16-distance%16)%16;z<1800;z+=16){const a=proj(z),b=proj(z+6);for(const lane of [-.34,.34]){const x=a.x+lane*a.half,y=b.x+lane*b.half,w=Math.max(1,a.p*W*.0038);poly([[x-w,a.y],[x+w,a.y],[y+w*.7,b.y],[y-w*.7,b.y]],'#e7ece2b0')}}
 for(let z=(8-distance%8)%8;z<900;z+=8){const p=proj(z);for(let k=0;k<2;k++){const lane=((z*13+k*19)%53)/53*1.55-.775;ctx.fillStyle='#b9c2c322';ctx.beginPath();ctx.ellipse(p.x+lane*p.half,p.y,Math.max(.5,p.p*1.4),Math.max(.5,p.p*.7),0,0,Math.PI*2);ctx.fill()}}
 let line=lapLength-distance%lapLength;if(line<110){const p=proj(line),bw=2*p.half/16,bh=Math.max(3,p.p*H*.028);for(let i=0;i<16;i++){ctx.fillStyle=(i+Math.floor((distance+line)/5))%2?'#202632':'#fff';ctx.fillRect(p.x-p.half+i*bw,p.y-bh/2,bw,bh)}}}
function barrier(z,side){const p=proj(z),w=Math.max(4,p.p*W*.043),h=Math.max(4,p.p*H*.042);rr(p.x+side*p.half*1.1-w/2,p.y-h,w,h,4,Math.floor((distance+z)/9)%2?'#e8483b':'#f8f3e9','#583b2a')}
function kart(x,y,s,color,helmet,n){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(0,6,36,11,0,0,7);ctx.fill();rr(-34,-3,14,23,5,'#171c25');rr(20,-3,14,23,5,'#171c25');rr(-29,-14,58,30,8,color,'#27313b');poly([[-24,-12],[24,-12],[17,-28],[-17,-28]],color,'#202631',2);rr(-17,-39,34,23,12,helmet,'#222');ctx.fillStyle='#fff';ctx.fillRect(-16,-11,32,4);ctx.fillStyle='#fff';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText(n,0,4);ctx.restore()}
function itemDraw(it){const z=it.d-distance;if(z<2||z>500)return;const p=proj(z),s=Math.max(8,p.p*44),x=p.x+it.lane*p.half*.73,y=p.y-s*.9+Math.sin(clock/230+it.d)*s*.12;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(clock/380+it.d)*.1);ctx.shadowColor='#32ddff';ctx.shadowBlur=s*.5;poly([[0,-s*.48],[s*.43,-s*.24],[s*.43,s*.24],[0,s*.48],[-s*.43,s*.24],[-s*.43,-s*.24]],'#26c7f3','#e0fbff',2);ctx.shadowBlur=0;ctx.fillStyle='#fff36a';ctx.font=`1000 ${s*.62}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('⚡',0,0);ctx.restore()}
function renderWorld(){background(clock);road();for(let z=36;z<430;z+=65){barrier(z,-1);barrier(z+24,1)}boxes.forEach(itemDraw);const vis=[];for(const a of rivals){let dz=a.d-distance;if(dz>raceLength/2)dz-=raceLength;if(dz< -raceLength/2)dz+=raceLength;if(Math.abs(dz)<430)vis.push({a,dz})}vis.sort((a,b)=>b.dz-a.dz);const portrait=H>W*1.15,playerW=portrait?W*.55:W*.37;for(const o of vis){const depth=Math.max(22,Math.abs(o.dz)),p=proj(depth),img=rivalArt[o.a.id-2];if(!img.complete||!img.naturalWidth)continue;const relative=.24+.35*p.p,w=playerW*relative,h=w*img.naturalHeight/img.naturalWidth,x=p.x+o.a.lane*p.half*.92;ctx.save();ctx.globalAlpha=o.a.stun>0?.72:1;ctx.shadowColor='#09152277';ctx.shadowBlur=Math.max(3,p.p*12);ctx.shadowOffsetY=Math.max(2,p.p*7);ctx.drawImage(img,x-w/2,p.y-h,w,h);ctx.restore()}const p=proj(12),kw=playerW,kh=kw/1.314,kx=p.x+player.lane*p.half*.7;ctx.save();ctx.translate(kx,H*.985);ctx.rotate(player.turn*.1);if(boostTime>0){for(let i=0;i<2;i++){ctx.fillStyle=i?'#ffce36':'#ff6927';ctx.beginPath();ctx.moveTo((i?1:-1)*kw*.13,0);ctx.lineTo(rand(-kw*.2,kw*.2),H*.08);ctx.lineTo(rand(-kw*.2,kw*.2),H*.14);ctx.closePath();ctx.fill()}}if(sprite.complete&&sprite.naturalWidth)ctx.drawImage(sprite,-kw/2,-kh,kw,kh);else kart(0,-kh*.3,kw*.007,'#1670e7','#18243c','V');ctx.restore()}
function initRivals(){rivals=Array.from({length:3},(_,i)=>({id:i+2,d:[150,270,390][i],lane:[-.88,0,.88][i],laneGoal:[-.88,0,.88][i],think:4.5+i*.6,v:87+i*4.5+rand(-1,1),stun:0}))}
function rank(){return [{d:distance,p:true},...rivals.map(r=>({d:r.d}))].sort((a,b)=>b.d-a.d).findIndex(x=>x.p)+1}
function showToast(s){toast=s;toastEnd=performance.now()+900}
function begin(){distance=0;speed=0;elapsed=0;lapLength=560;raceLength=lapLength*3;boosts=1;boostTime=0;drift=0;driftPaid=false;boxes=[];fx=[];nextBox=65;collisionWait=0;finishPlace=0;player={lane:0,turn:0};initRivals();state='countdown';let count=3;overlay.classList.add('hidden');hud.classList.remove('hidden');pause.classList.remove('hidden');controlBox.classList.remove('hidden');last=performance.now();const timer=setInterval(()=>{count--;if(state!=='countdown'){clearInterval(timer);return}if(count<=0){state='race';clearInterval(timer)}},1000)}
function boost(){if(state==='race'&&boosts>0&&boostTime<=0){boosts--;boostTime=2.4;showToast('¡TURBO!');for(let i=0;i<12;i++)fx.push({x:W/2,y:H*.82,vx:rand(-80,80),vy:rand(-150,20),life:.6,c:'#ffad2c'})}}
function update(dt){clock=performance.now();if(state!=='race')return;elapsed+=dt;let steer=clamp((keys.right||keys.ArrowRight||keys.KeyD?1:0)-(keys.left||keys.ArrowLeft||keys.KeyA?1:0)+swipe,-1,1);player.turn+=(steer-player.turn)*Math.min(1,dt*9);if(steer&&speed>32){drift+=dt;if(drift>=1.2&&!driftPaid){boosts=Math.min(3,boosts+1);driftPaid=true;showToast('¡DERRAPE! + TURBO')}}else{drift=Math.max(0,drift-dt*1.8);if(drift<.16)driftPaid=false}if(keys.Space||keys.ShiftLeft||keys.ShiftRight||keys.KeyX)boost();const max=boostTime>0?118:104;speed=Math.min(max,speed+(speed<max?36:0)*dt);player.lane=clamp(player.lane+steer*dt*1.0,-1.5,1.5);if(Math.abs(player.lane)>1.02)speed=Math.max(36,speed-46*dt);if(Math.abs(player.lane)>1.38)speed=Math.max(30,speed-70*dt);if(boostTime>0)boostTime-=dt;distance+=speed/3.6*dt;
 for(const r of rivals){if(r.stun>0)r.stun-=dt;else{r.d+=r.v/3.6*dt;r.think-=dt;if(r.think<=0){const lanes=[-.9,0,.9],open=lanes.filter(l=>rivals.every(o=>o===r||Math.abs(o.lane-l)>.58)&&Math.abs(player.lane-l)>.44);if(open.length)r.laneGoal=open[Math.floor(Math.random()*open.length)];r.think=rand(2.5,4.2);r.v=clamp(r.v+rand(-1.5,1.5),84,102)}r.lane+=clamp(r.laneGoal-r.lane,-dt*.32,dt*.32)}}while(nextBox<distance+470){boxes.push({d:nextBox,lane:[-.62,-.2,.22,.64][Math.floor(Math.random()*4)],used:false});nextBox+=rand(64,82)}for(const b of boxes){const dz=b.d-distance;if(!b.used&&Math.abs(dz)<5.5&&Math.abs(player.lane-b.lane)<.36){b.used=true;boosts=Math.min(3,boosts+1);showToast('¡ENERGÍA TURBO!');for(let i=0;i<12;i++)fx.push({x:W/2,y:H*.76,vx:rand(-70,70),vy:rand(-120,20),life:.7,c:'#ffe15b'})}}boxes=boxes.filter(b=>!b.used&&b.d>distance-20);collisionWait=Math.max(0,collisionWait-dt);if(!collisionWait)for(const r of rivals){let dz=r.d-distance;if(dz>raceLength/2)dz-=raceLength;if(dz< -raceLength/2)dz+=raceLength;if(Math.abs(dz)<4&&Math.abs(r.lane-player.lane)<.24){speed=Math.max(40,speed-18);r.stun=.8;collisionWait=.8;shake=.2;showToast('¡CHOQUE!');break}}for(const p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=170*dt;p.life-=dt}fx=fx.filter(p=>p.life>0);shake=Math.max(0,shake-dt);if(distance>=raceLength){distance=raceLength;state='finished';finishPlace=rank();if(!best||elapsed<best){best=elapsed;localStorage.setItem('vladiKartBest',String(best))}overlay.classList.remove('hidden');hud.classList.add('hidden');pause.classList.add('hidden');controlBox.classList.add('hidden');title.textContent=finishPlace===1?'¡GANASTE!':'¡A LA META!';subtitle.textContent=`Llegaste ${finishPlace}° · ${timeText(elapsed)}`;chips.innerHTML=`<span class="chip">🏁 3 vueltas</span><span class="chip">⏱ Tu tiempo ${timeText(elapsed)}</span><span class="chip">🏆 Récord ${timeText(best)}</span>`;start.textContent='↻ CORRER OTRA VEZ';help.textContent='¡Probá de nuevo y buscá mejorar tu tiempo!'}}
function timeText(t){return`${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(2).padStart(5,'0')}`}
function draw(){ctx.save();if(shake)ctx.translate(rand(-4,4)*shake*5,rand(-3,3)*shake*5);renderWorld();for(const p of fx){ctx.globalAlpha=clamp(p.life/.7,0,1);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,4,0,7);ctx.fill()}ctx.globalAlpha=1;if(state==='countdown'){ctx.fillStyle='#061a2d77';ctx.fillRect(0,0,W,H);ctx.fillStyle='white';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`1000 ${Math.min(W,H)*.2}px system-ui`;ctx.shadowColor='#17365a';ctx.shadowBlur=15;ctx.fillText('¡YA!',W/2,H*.42);ctx.shadowBlur=0}if(state==='race'&&drift>0){const w=Math.min(170,W*.34),x=(W-w)/2,y=H*.68;rr(x,y,w,11,5,'#061a2aaa');rr(x+2,y+2,(w-4)*clamp(drift/1.15,0,1),7,4,'#ffe144')}if(toastEnd>performance.now()){rr(W/2-105,H*.28,210,46,15,'#0d2b4ddd','#ffffffaa');ctx.fillStyle='white';ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(toast,W/2,H*.28+23)}ctx.restore()}
function loop(t){const dt=last?Math.min(.04,(t-last)/1000):0;last=t;update(dt);draw();if(state==='race'||state==='countdown'){$('#lap').textContent=`${Math.min(3,Math.floor(distance/lapLength)+1)}/3`;$('#place').textContent=`${rank()}/4`;$('#charges').textContent=`⚡ ${boosts}`;$('#speed').textContent=String(Math.round(speed))}requestAnimationFrame(loop)}requestAnimationFrame(loop);
function pauseGame(){if(state==='race'){state='paused';title.textContent='PAUSA';subtitle.textContent='La carrera está en pausa';chips.innerHTML='<span class="chip">▶ Tocá continuar para seguir</span>';start.textContent='▶ CONTINUAR';help.textContent='';overlay.classList.remove('hidden');hud.classList.add('hidden');pause.classList.add('hidden');controlBox.classList.add('hidden')}else if(state==='paused'){state='race';overlay.classList.add('hidden');hud.classList.remove('hidden');pause.classList.remove('hidden');controlBox.classList.remove('hidden');last=performance.now()}}
start.addEventListener('click',()=>{if(state==='paused')pauseGame();else begin()});pause.addEventListener('click',pauseGame);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='race')pauseGame()});addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.code==='Escape')pauseGame()},{passive:false});addEventListener('keyup',e=>keys[e.code]=false);
for(const id of ['left','right']){const b=$('#'+id),name=id;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[name]=true;b.classList.add('active');b.setPointerCapture(e.pointerId)},{passive:false});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>{keys[name]=false;b.classList.remove('active')})}$('#turbo').addEventListener('pointerdown',e=>{e.preventDefault();boost()},{passive:false});let swipe=0;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){swipe=e.clientX<W*.43?-1:e.clientX>W*.57?1:0;canvas.setPointerCapture(e.pointerId)}},{passive:false});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&e.buttons)swipe=clamp((e.clientX-W/2)/(W*.34),-1,1)},{passive:false});for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,()=>swipe=0);
window.__vladiKart={get state(){return state},get metrics(){return{distance,speed,lap:Math.min(3,Math.floor(distance/lapLength)+1),place:rank(),boosts,elapsed,pickups:boxes.filter(x=>!x.used).length}},start:begin,boost,setSteer:v=>swipe=v};
})();
