(()=>{'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),playerArt=new Image();
playerArt.src='assets/vladi-kart.webp';
const $=s=>document.querySelector(s),overlay=$('#overlay'),title=$('#title'),subtitle=$('#subtitle'),chips=$('#chips'),help=$('#help'),start=$('#start'),hud=$('#hud'),pauseButton=$('#pause'),controls=$('.controls');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
let W=0,H=0,DPR=1,state='menu',last=0,elapsed=0,distance=0,stars=0,avoided=0,lane=1,obstacles=[],spawnTimer=.55,wave=0,best=+(localStorage.getItem('vladiDodgeBest')||0),flash=0,shake=0,toast='',toastUntil=0,swipeStart=null;
function resize(){DPR=Math.min(devicePixelRatio||1,1.75);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize,{passive:true});resize();
const roadWidth=()=>Math.min(W*.82,W>1000?620:900),roadLeft=()=> (W-roadWidth())/2,playerY=()=>H*.805,carWidth=()=>Math.min(roadWidth()*.42,W*.47,H*.33,W>1000?150:Infinity),carHeight=()=>carWidth()/1.31;
function roadCenter(y){return W/2+Math.sin((y/H)*2.05+distance*.004)*Math.min(W*.035,42)}
function laneX(n,y){return roadCenter(y)+(n-1)*roadWidth()/3}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.lineWidth=2;ctx.strokeStyle=stroke;ctx.stroke()}}
function poly(points,fill,stroke,lw=1){ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.lineWidth=lw;ctx.strokeStyle=stroke;ctx.stroke()}}
function backdrop(){const grass=ctx.createLinearGradient(0,0,W,0);grass.addColorStop(0,'#438d32');grass.addColorStop(.5,'#6bac43');grass.addColorStop(1,'#438d32');ctx.fillStyle=grass;ctx.fillRect(0,0,W,H);const strip=72,offset=distance*2%strip;ctx.fillStyle='#b8d96b12';for(let y=-strip+offset;y<H;y+=strip*2)ctx.fillRect(0,y,W,strip);}
function track(){const rw=roadWidth(),left=[],right=[];for(let y=0;y<=H+10;y+=18){const c=roadCenter(y);left.push([c-rw/2,y]);right.push([c+rw/2,y])}ctx.save();ctx.shadowColor='#06192799';ctx.shadowBlur=18;ctx.shadowOffsetY=5;ctx.beginPath();left.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));for(let i=right.length-1;i>=0;i--)ctx.lineTo(right[i][0],right[i][1]);ctx.closePath();const asphalt=ctx.createLinearGradient(roadLeft(),0,roadLeft()+rw,0);asphalt.addColorStop(0,'#26313b');asphalt.addColorStop(.5,'#3e4852');asphalt.addColorStop(1,'#26313b');ctx.fillStyle=asphalt;ctx.fill();ctx.restore();
 const step=34,offset=distance*2%step;for(let y=-step+offset,idx=0;y<H+step;y+=step,idx++){for(const side of [-1,1]){const c=roadCenter(y),edge=c+side*rw/2,inside=c+side*(rw/2-9),nextC=roadCenter(y+step),nextEdge=nextC+side*rw/2,nextInside=nextC+side*(rw/2-9);poly([[edge,y],[inside,y],[nextInside,y+step],[nextEdge,y+step]],idx%2?'#f7f1d9':'#e34b3c')}}
 for(let div=1;div<3;div++){for(let y=-(distance*2%76);y<H;y+=76){const y2=Math.min(H,y+42),x1=roadCenter(y)+(div-1.5)*rw/3,x2=roadCenter(y2)+(div-1.5)*rw/3;ctx.strokeStyle='#f4f5dfbd';ctx.lineWidth=Math.max(2,rw*.006);ctx.beginPath();ctx.moveTo(x1,y);ctx.lineTo(x2,y2);ctx.stroke()}}
 // Curbs, three lanes, and the painted finish-free vanishing point keep the
 // course readable without a road edge or end that can run out beneath play.
}
function drawCone(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.shadowColor='#09131c88';ctx.shadowBlur=7;ctx.shadowOffsetY=5;ctx.fillStyle='#111c25';ctx.beginPath();ctx.ellipse(0,18,27,9,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;poly([[-23,15],[23,15],[7,-27],[-7,-27]],'#f07825','#b84516',3);poly([[-16,2],[16,2],[12,-7],[-12,-7]],'#fff4db');ctx.fillStyle='#ffcb42';ctx.beginPath();ctx.ellipse(0,-27,7,4,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawTires(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.shadowColor='#09131c99';ctx.shadowBlur=8;ctx.shadowOffsetY=5;for(const [dx,dy] of [[-10,8],[10,-3]]){ctx.fillStyle='#111820';ctx.beginPath();ctx.ellipse(dx,dy,24,19,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#727c81';ctx.beginPath();ctx.ellipse(dx,dy,10,8,0,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawBarrier(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.shadowColor='#08141c99';ctx.shadowBlur=8;ctx.shadowOffsetY=5;roundRect(-32,-19,64,38,7,'#f3a43f','#733b18');roundRect(-26,-12,52,8,3,'#fff1c7');roundRect(-26,4,52,8,3,'#d94a35');ctx.restore()}
function drawRival(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.shadowColor='#08141c99';ctx.shadowBlur=10;ctx.shadowOffsetY=6;roundRect(-39,-27,16,31,6,'#141820','#080b10');roundRect(23,-27,16,31,6,'#141820','#080b10');roundRect(-39,8,16,28,6,'#141820','#080b10');roundRect(23,8,16,28,6,'#141820','#080b10');roundRect(-31,-35,62,72,13,'#c82e2b','#53191a');ctx.shadowBlur=0;poly([[-27,-18],[27,-18],[20,-32],[-20,-32]],'#ec5040','#802121',2);roundRect(-20,-9,40,21,9,'#264f70','#163148');ctx.fillStyle='#d6f4ff';ctx.fillRect(-17,-6,34,3);roundRect(-23,22,46,7,3,'#ffe15a');roundRect(-20,31,13,5,2,'#ffefab');roundRect(7,31,13,5,2,'#ffefab');ctx.restore()}
function drawStar(x,y,s){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(elapsed*4+y)*.16);ctx.shadowColor='#ffd52e';ctx.shadowBlur=16;ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?s*.45:s;const px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fillStyle='#ffd333';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#fff5b1';ctx.stroke();ctx.restore()}
function obstacleY(o){return -70+o.p*(playerY()+40)}
function drawObstacles(){for(const o of obstacles){const y=obstacleY(o),p=clamp(o.p,0,1),scale=.48+p*.55,x=laneX(o.lane,y);if(o.type==='cone')drawCone(x,y,scale);else if(o.type==='tires')drawTires(x,y,scale);else if(o.type==='barrier')drawBarrier(x,y,scale);else if(o.type==='rival')drawRival(x,y,scale);else if(o.type==='star')drawStar(x,y,scale*20)}}
function drawPlayer(){const x=laneX(lane,playerY()),w=carWidth(),h=carHeight(),y=playerY();ctx.save();ctx.translate(x,y);if(shake){ctx.translate(rand(-5,5)*shake,rand(-3,3)*shake)}ctx.shadowColor='#08131c99';ctx.shadowBlur=14;ctx.shadowOffsetY=7;if(playerArt.complete&&playerArt.naturalWidth)ctx.drawImage(playerArt,-w/2,-h/2,w,h);else drawRival(0,0,w/78);ctx.restore();if(flash>0){ctx.fillStyle=`rgba(255,255,255,${flash*.42})`;ctx.fillRect(x-w*.55,y-h*.55,w*1.1,h*1.1)}}
function drawToast(){if(!toast||performance.now()>toastUntil)return;roundRect(W/2-105,H*.19,210,45,16,'#0b2638d9','#ffffffbb');ctx.fillStyle='#fff';ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(toast,W/2,H*.19+23)}
function draw(){backdrop();track();drawObstacles();drawPlayer();drawToast()}
function updateHud(){const score=Math.floor(distance*2+stars*50+avoided*10);$('#meters').textContent=String(Math.floor(distance));$('#score').textContent=String(score);$('#best').textContent=String(Math.max(best,score))}
function showOverlay(mode){overlay.classList.remove('hidden');hud.classList.add('hidden');pauseButton.classList.add('hidden');controls.classList.add('hidden');if(mode==='menu'){title.textContent='VLADI KART';subtitle.textContent='¡Esquivá los obstáculos y llegá lo más lejos posible!';chips.innerHTML='<span class="chip">🚧 Esquivá conos y karts</span><span class="chip">⭐ Juntá estrellas</span><span class="chip">🏆 Superá tu récord</span>';start.textContent='▶ JUGAR';help.textContent='Usá ◀ ▶, las flechas o deslizá para cambiar de carril'}else if(mode==='paused'){title.textContent='PAUSA';subtitle.textContent='Tu carrera está detenida';chips.innerHTML=`<span class="chip">📏 ${Math.floor(distance)} metros</span><span class="chip">⭐ ${stars} estrellas</span>`;start.textContent='▶ SEGUIR';help.textContent='La carrera continúa desde donde la pausaste'}else{title.textContent='¡CHOQUE!';subtitle.textContent=`Recorriste ${Math.floor(distance)} metros · ${Math.floor(distance*2+stars*50+avoided*10)} puntos`;chips.innerHTML=`<span class="chip">⭐ ${stars} estrellas</span><span class="chip">🚧 ${avoided} obstáculos esquivados</span><span class="chip">🏆 Récord ${best}</span>`;start.textContent='↻ REINTENTAR';help.textContent='Cambiate de carril antes de que el obstáculo llegue a Vladi'}}
function begin(){window.VladiSound?.play('start');window.VladiSound?.engineStart?.();state='running';elapsed=0;distance=0;stars=0;avoided=0;lane=1;obstacles=[];spawnTimer=.48;wave=0;flash=0;shake=0;toast='';overlay.classList.add('hidden');hud.classList.remove('hidden');pauseButton.classList.remove('hidden');controls.classList.remove('hidden');last=performance.now();updateHud()}
function pauseGame(){if(state==='running'){window.VladiSound?.play('pause');window.VladiSound?.engineStop?.();state='paused';showOverlay('paused')}else if(state==='paused'){window.VladiSound?.play('resume');window.VladiSound?.engineStart?.();state='running';overlay.classList.add('hidden');hud.classList.remove('hidden');pauseButton.classList.remove('hidden');controls.classList.remove('hidden');last=performance.now()}}
function move(dir){if(state!=='running')return;const previous=lane;lane=clamp(lane+dir,0,2);if(previous!==lane)window.VladiSound?.play('move');toast='';}
function spawnWave(){const lanes=[0,1,2].sort(()=>Math.random()-.5),count=elapsed>7&&Math.random()<.34?2:1,types=['cone','tires','barrier','rival'];for(let i=0;i<count;i++)obstacles.push({lane:lanes[i],p:0,type:types[Math.floor(Math.random()*types.length)],passed:false});wave++;if(wave%4===0){const free=lanes[count];if(free!==undefined)obstacles.push({lane:free,p:rand(-.28,-.08),type:'star',passed:false})}spawnTimer=Math.max(1.38,1.9-elapsed*.006)}
function finish(){window.VladiSound?.play('gameover');window.VladiSound?.engineStop?.();state='over';const score=Math.floor(distance*2+stars*50+avoided*10);if(score>best){best=score;localStorage.setItem('vladiDodgeBest',String(best))}updateHud();showOverlay('over')}
function update(dt){if(state!=='running')return;elapsed+=dt;const speed=120+Math.min(100,elapsed*3);window.VladiSound?.engineUpdate?.(elapsed/36);distance+=speed/14*dt;spawnTimer-=dt;if(spawnTimer<=0)spawnWave();const passTime=Math.max(1.25,1.75-elapsed*.008);for(const o of obstacles){o.p+=dt/passTime;if(o.type==='star'&&o.p>.82&&o.lane===lane){o.p=2;stars++;window.VladiSound?.play('collect');toast='¡ESTRELLA! +50';toastUntil=performance.now()+800}if(o.type!=='star'&&!o.passed&&o.p>=.96){o.passed=true;if(o.lane===lane){flash=.8;shake=1;finish();return}else{avoided++;toast='¡BIEN ESQUIVADO!';toastUntil=performance.now()+550}}}obstacles=obstacles.filter(o=>o.p<1.08);flash=Math.max(0,flash-dt*1.7);shake=Math.max(0,shake-dt*2.8);updateHud()}
function loop(t){const dt=last?Math.min(.05,(t-last)/1000):0;last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
start.addEventListener('click',()=>{if(state==='paused')pauseGame();else begin()});pauseButton.addEventListener('click',pauseGame);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pauseGame()});
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'||e.code==='KeyP'){pauseGame();return}if(e.code==='Space'||e.code==='Enter'){if(state==='menu'||state==='over')begin();else if(state==='running')pauseGame();else if(state==='paused')pauseGame();return}if(e.code==='ArrowLeft'||e.code==='KeyA')move(-1);if(e.code==='ArrowRight'||e.code==='KeyD')move(1)},{passive:false});
$('#left').addEventListener('click',()=>move(-1));$('#right').addEventListener('click',()=>move(1));
canvas.addEventListener('pointerdown',e=>{if(state==='running')swipeStart=[e.clientX,e.clientY]},{passive:true});canvas.addEventListener('pointerup',e=>{if(state!=='running'||!swipeStart)return;const dx=e.clientX-swipeStart[0];if(Math.abs(dx)>24)move(dx<0?-1:1);else move(e.clientX<W/2?-1:1);swipeStart=null},{passive:true});canvas.addEventListener('pointercancel',()=>swipeStart=null,{passive:true});
window.__vladiDodge={get state(){return state},get metrics(){return{distance,stars,avoided,lane,obstacles:obstacles.length,score:Math.floor(distance*2+stars*50+avoided*10),best}},start:begin,move,setLane:n=>{lane=clamp(n,0,2)},forceObstacle:(n,p=.9,type='cone')=>obstacles.push({lane:n,p,type,passed:false}),getLayout:()=>({width:W,height:H,roadWidth:roadWidth(),carWidth:carWidth(),dpr:DPR})};
})();
