(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d'),arena=$('arena');
const ui={level:$('level'),score:$('score'),best:$('best'),lives:$('lives'),menuBest:$('menuBest'),menu:$('menu'),pause:$('pauseOverlay'),level:$('levelOverlay'),over:$('over'),toast:$('toast'),powerbar:$('powerbar'),powerfill:$('powerfill')};
const dirs={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]};
let level=1,score=0,best=+(localStorage.getItem('vladiHalloweenBest')||0),lives=3,state='menu',cols=21,rows=21,spawnX=1,spawnY=1,maze=[],items=[],player,ghosts=[],cell=20,ox=0,oy=0,acc=0,ghostAcc=0,last=0,power=0,invuln=0,queued=null,dir='left',sound=true,audio=null,toastTimer=0,anim=0,swipeStart=null,lastAspect=0;
$('best').textContent=ui.menuBest.textContent=best;
const sprite=new Image();sprite.src='../vladi-run/assets/vladi-runner.webp';const faceSprite=new Image();faceSprite.src='../vladi-run/assets/vladi-face.png';
function resize(){const rect=arena.getBoundingClientRect();const aspect=rect.width/Math.max(1,rect.height);const changed=lastAspect>0&&Math.abs(aspect-lastAspect)>.08;lastAspect=aspect;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const header=document.querySelector('.top').getBoundingClientRect().height,footer=document.querySelector('.bottom').getBoundingClientRect().height;let availW=rect.width-12,availH=rect.height-12;cell=Math.max(7,Math.floor(Math.min(availW/cols,availH/rows)));ox=(rect.width-cols*cell)/2;oy=(rect.height-rows*cell)/2;if(changed&&state==='playing')generateMaze();}
new ResizeObserver(resize).observe(arena);window.addEventListener('orientationchange',()=>setTimeout(()=>{resize();if(state==='playing'){generateMaze();pop('Laberinto adaptado a la pantalla');}},180));
function generateMaze(){const box=arena.getBoundingClientRect(),targetCell=Math.max(19,32-Math.floor((level-1)*.8));rows=Math.min(39,Math.max(17,Math.round(box.height/targetCell)));if(rows%2===0)rows+=rows<39?1:-1;cols=Math.min(61,Math.max(13,Math.round(box.width/Math.max(1,box.height)*rows)));if(cols%2===0)cols+=cols<61?1:-1;spawnX=Math.floor(cols/2);if(spawnX%2===0)spawnX--;spawnY=rows-4;maze=Array.from({length:rows},()=>Array(cols).fill(1));let stack=[[spawnX,spawnY]];maze[spawnY][spawnX]=0;while(stack.length){const [x,y]=stack[stack.length-1],opts=[];for(const [dx,dy]of [[0,-2],[2,0],[0,2],[-2,0]]){const nx=x+dx,ny=y+dy;if(nx>0&&ny>0&&nx<cols-1&&ny<rows-1&&maze[ny][nx])opts.push([nx,ny,dx,dy]);}if(!opts.length){stack.pop();continue;}const[nx,ny,dx,dy]=opts[Math.floor(Math.random()*opts.length)];maze[y+dy/2][x+dx/2]=0;maze[ny][nx]=0;stack.push([nx,ny]);}
 for(let i=0;i<Math.floor(cols*rows*.055);i++){const x=1+Math.floor(Math.random()*(cols-2)),y=1+Math.floor(Math.random()*(rows-2));if(maze[y][x]&&((maze[y-1][x]===0&&maze[y+1][x]===0)||(maze[y][x-1]===0&&maze[y][x+1]===0)))maze[y][x]=0;}
 player={x:spawnX,y:spawnY,fromX:spawnX,fromY:spawnY,t:1};let open=[];for(let y=1;y<rows-1;y++)for(let x=1;x<cols-1;x++)if(!maze[y][x]&&!(x===spawnX&&y===spawnY))open.push({x,y});open.sort((a,b)=>dist(b)-dist(a));function dist(p){return Math.abs(p.x-spawnX)+Math.abs(p.y-spawnY)}
 ghosts=[];const ghostCount=Math.min(4,2+Math.floor((level-1)/2));for(let i=0;i<ghostCount;i++){const p=open.splice(Math.min(open.length-1,Math.floor(open.length*(.22+i*.15))),1)[0]||{x:cols-2,y:1};ghosts.push({x:p.x,y:p.y,fromX:p.x,fromY:p.y,t:1,color:['#ff675f','#9a7cff','#48d9d0','#ff9b47'][i],kind:i%3});}
 const farther=open.filter(p=>dist(p)>4);items=Array.from({length:rows},()=>Array(cols).fill(''));for(const p of open)items[p.y][p.x]='c';const powers=Math.min(13,Math.max(7,Math.floor(cols*rows/130)));for(let i=0;i<powers&&farther.length;i++){const idx=Math.floor(i*(farther.length-1)/Math.max(1,powers-1));const p=farther[idx];items[p.y][p.x]='p';}resize();updateHud();}
function saveBest(){if(score>best){best=score;localStorage.setItem('vladiHalloweenBest',best);}}
function updateHud(){ui.level.textContent=level;ui.score.textContent=score;ui.best.textContent=best;ui.lives.textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);ui.menuBest.textContent=best;ui.powerbar.classList.toggle('hiddenbar',power<=0);ui.powerfill.style.width=`${Math.min(100,power/9*100)}%`;}
function beep(freq=500,dur=.07,type='sine',vol=.04){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur);}catch{}}
function blip(kind){if(kind==='candy')beep(720,.045,'triangle');else if(kind==='pumpkin'){[440,660,880].forEach((f,i)=>setTimeout(()=>beep(f,.14,'sine',.055),i*75));}else if(kind==='eat')beep(220,.18,'square',.035);else if(kind==='hit'){beep(130,.26,'sawtooth',.06);}else if(kind==='win'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>beep(f,.16),i*95));}}
function pop(msg){ui.toast.textContent=msg;ui.toast.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('on'),1050)}
function setDir(d){if(state!=='playing')return;queued=d;const v=dirs[d],nx=player.x+v[0],ny=player.y+v[1];if(!maze[ny]?.[nx])movePlayer(d);}
function movePlayer(d){if(state!=='playing'||player.t<1)return;const [dx,dy]=dirs[d],nx=player.x+dx,ny=player.y+dy;if(maze[ny]?.[nx]!==0)return;dir=d;queued=null;player.fromX=player.x;player.fromY=player.y;player.x=nx;player.y=ny;player.t=0;collect();checkCollisions();}
function collect(){const item=items[player.y]?.[player.x];if(item==='c'){items[player.y][player.x]='';score+=10;saveBest();blip('candy');}else if(item==='p'){items[player.y][player.x]='';power=9;score+=50;saveBest();blip('pumpkin');pop('¡PODER DE CALABAZA!');}updateHud();}
function passable(x,y){return maze[y]?.[x]===0;}
function sendGhostHome(g){let x=cols-2,y=rows-2;while(!passable(x,y)){x=Math.max(1,x-1);if(x===1)y=Math.max(1,y-1);}g.x=x;g.y=y;g.fromX=x;g.fromY=y;g.t=1;}
function pathStep(g){let q=[[g.x,g.y]],seen=new Set([g.x+','+g.y]),prev=new Map(),target=player.x+','+player.y;while(q.length){const [x,y]=q.shift(),key=x+','+y;if(key===target)break;for(const [dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=x+dx,ny=y+dy,k=nx+','+ny;if(passable(nx,ny)&&!seen.has(k)){seen.add(k);prev.set(k,key);q.push([nx,ny]);}}}if(!seen.has(target))return null;let k=target;while(prev.get(k)&&prev.get(k)!==g.x+','+g.y)k=prev.get(k);const [x,y]=k.split(',').map(Number);return{x,y};}
function moveGhosts(){for(const g of ghosts){let next;if(power>0){const dirs4=[[0,-1],[1,0],[0,1],[-1,0]],opts=dirs4.map(([dx,dy])=>({x:g.x+dx,y:g.y+dy})).filter(p=>passable(p.x,p.y));opts.sort((a,b)=>Math.abs(b.x-player.x)+Math.abs(b.y-player.y)-(Math.abs(a.x-player.x)+Math.abs(a.y-player.y)));next=opts[0];}else next=pathStep(g);if(!next)continue;g.fromX=g.x;g.fromY=g.y;g.x=next.x;g.y=next.y;g.t=0;checkCollisions();if(state!=='playing')return;}}
function checkCollisions(){for(const g of ghosts)if(Math.abs(g.x-player.x)+Math.abs(g.y-player.y)===0){if(power>0){sendGhostHome(g);score+=200;saveBest();blip('eat');pop('+200 · ¡MONSTRUO ATRAPADO!');updateHud();}else if(performance.now()>invuln){lives--;invuln=performance.now()+1700;blip('hit');pop('¡CUIDADO!');player.x=spawnX;player.y=spawnY;player.fromX=spawnX;player.fromY=spawnY;player.t=1;queued=null;sendGhostHome(g);updateHud();if(lives<=0)gameOver();}}}
function checkClear(){let left=0;for(const row of items)for(const v of row)if(v)left++;if(!left&&state==='playing'){score+=500;saveBest();ui.best.textContent=ui.menuBest.textContent=best;ui.doneLevel.textContent=level;ui.level.classList.remove('hidden');state='level';blip('win');}}
function gameOver(){state='over';best=Math.max(best,score);localStorage.setItem('vladiHalloweenBest',best);ui.finalScore.textContent=score;ui.finalLevel.textContent=level;ui.finalBest.textContent=best;ui.over.classList.remove('hidden');updateHud();}
async function start(){level=1;score=0;lives=3;power=0;invuln=0;state='playing';for(const id of ['menu','pauseOverlay','levelOverlay','over'])$(id).classList.add('hidden');if(document.fullscreenEnabled&&!document.fullscreenElement){try{await document.documentElement.requestFullscreen();}catch{}}generateMaze();last=performance.now();}
function nextLevel(){level++;power=0;state='playing';ui.level.classList.add('hidden');generateMaze();pop('¡NIVEL '+level+'!');}
function pause(){if(state==='playing'){state='paused';ui.pause.classList.remove('hidden');}}
function resume(){if(state==='paused'){state='playing';ui.pause.classList.add('hidden');last=performance.now();}}
$('play').onclick=start;$('again').onclick=start;$('next').onclick=nextLevel;$('pause').onclick=()=>state==='paused'?resume():pause();$('resume').onclick=resume;$('restart').onclick=start;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♪';$('sound').setAttribute('aria-label',sound?'Silenciar sonido':'Activar sonido');if(sound)beep(680,.08);};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{pop('Pantalla completa no disponible en este navegador')}};document.addEventListener('fullscreenchange',()=>{const active=!!document.fullscreenElement;$('fullscreen').textContent=active?'⛶':'⛶';$('fullscreen').setAttribute('aria-label',active?'Salir de pantalla completa':'Activar pantalla completa');setTimeout(resize,80)});
for(const btn of document.querySelectorAll('.pad button')){btn.addEventListener('pointerdown',e=>{e.preventDefault();setDir(btn.dataset.dir);});}
window.addEventListener('keydown',e=>{const map={ArrowUp:'up',w:'up',W:'up',ArrowRight:'right',d:'right',D:'right',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left'};if(e.key==='Escape'||e.key==='p'||e.key==='P'){e.preventDefault();state==='playing'?pause():state==='paused'?resume():null;return;}if(map[e.key]){e.preventDefault();if(!e.repeat)setDir(map[e.key]);}});
canvas.addEventListener('pointerdown',e=>{swipeStart={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;if(Math.max(Math.abs(dx),Math.abs(dy))>18)setDir(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));swipeStart=null;});
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function project(gx,gy){const w=canvas.clientWidth,h=canvas.clientHeight,z=Math.max(0,Math.min(1,gy/(rows-1))),scale=.42+.72*z;return{x:w*.5+(gx-cols*.5)*(w/cols)*scale,y:h*(.09+.91*z),scale,z};}
function quad(a,b,c,d){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.closePath();}
function drawFloor(x,y){const a=project(x,y),b=project(x+1,y),c=project(x+1,y+1),d=project(x,y+1);const grad=ctx.createLinearGradient(a.x,a.y,d.x,d.y);grad.addColorStop(0,'#080914');grad.addColorStop(1,'#121326');quad(a,b,c,d);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='#6972d018';ctx.lineWidth=1;ctx.stroke();}
function drawWall(x,y){const a=project(x,y),b=project(x+1,y),c=project(x+1,y+1),d=project(x,y+1),size=projectedSize(y+1),depth=Math.max(2,size.h*.2),shift=Math.max(1,size.w*.055);ctx.save();ctx.shadowColor='#03030b';ctx.shadowBlur=Math.max(2,size.w*.14);ctx.shadowOffsetY=depth*.42;quad(a,b,c,d);ctx.fillStyle='#161735';ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;
 ctx.beginPath();ctx.moveTo(d.x,d.y);ctx.lineTo(c.x,c.y);ctx.lineTo(c.x+shift,c.y+depth);ctx.lineTo(d.x+shift,d.y+depth);ctx.closePath();const front=ctx.createLinearGradient(d.x,d.y,d.x,d.y+depth);front.addColorStop(0,'#28265f');front.addColorStop(1,'#100f2d');ctx.fillStyle=front;ctx.fill();ctx.strokeStyle='#6a63df';ctx.lineWidth=Math.max(1,size.w*.035);ctx.stroke();
 ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(c.x+shift,c.y+depth);ctx.lineTo(b.x+shift,b.y+depth*.55);ctx.closePath();ctx.fillStyle='#171742';ctx.fill();
 quad(a,b,c,d);const top=ctx.createLinearGradient(a.x,a.y,c.x,c.y);top.addColorStop(0,'#625fe5');top.addColorStop(.48,'#3f4bd0');top.addColorStop(1,'#2936a8');ctx.fillStyle=top;ctx.fill();ctx.strokeStyle='#8d8bff';ctx.lineWidth=Math.max(1,size.w*.045);ctx.stroke();ctx.strokeStyle='#fff2a44a';ctx.lineWidth=Math.max(1,size.w*.025);ctx.beginPath();ctx.moveTo(a.x+shift,a.y+1);ctx.lineTo(b.x-shift,b.y+1);ctx.stroke();ctx.restore();}
function projectedSize(y){const w=canvas.clientWidth,h=canvas.clientHeight,z=Math.max(0,Math.min(1,y/(rows-1))),scale=.42+.72*z;return{w:w/cols*scale,h:h/rows*(.68+1.12*z),scale};}
function projectedCenter(x,y){const a=project(x+.5,y),b=project(x+.5,y+1);return{x:(a.x+b.x)/2,y:(a.y+b.y)/2};}
function drawVladi(x,y,t){const pos=projectedCenter(x,y),size=Math.max(12,Math.min(projectedSize(y).w,projectedSize(y).h)*1.04);ctx.save();ctx.shadowColor='#ffb838a8';ctx.shadowBlur=size*.72;ctx.fillStyle='#0009';ctx.beginPath();ctx.ellipse(pos.x,pos.y+size*.42,size*.42,size*.16,0,0,Math.PI*2);ctx.fill();ctx.shadowColor=power>0?'#ffe45b':'#ffae3e';ctx.shadowBlur=size*.22;ctx.beginPath();ctx.arc(pos.x,pos.y,size*.46,0,Math.PI*2);ctx.fillStyle=power>0?'#ffc83d':'#ffb72f';ctx.fill();ctx.save();ctx.beginPath();ctx.arc(pos.x,pos.y,size*.4,0,Math.PI*2);ctx.clip();if(faceSprite.complete&&faceSprite.naturalWidth){ctx.drawImage(faceSprite,108,0,166,166,pos.x-size*.42,pos.y-size*.42,size*.84,size*.84);}else{ctx.drawImage(sprite,0,0,sprite.naturalWidth/4,sprite.naturalHeight,pos.x-size*.4,pos.y-size*.4,size*.8,size*.8);}ctx.restore();ctx.strokeStyle='#ffe59a';ctx.lineWidth=Math.max(1,size*.035);ctx.beginPath();ctx.arc(pos.x,pos.y,size*.43,0,Math.PI*2);ctx.stroke();ctx.restore();}
function drawMonster(g,t){const pos=projectedCenter(g.x,g.y),dims=projectedSize(g.y),s=Math.max(16,Math.min(dims.w,dims.h)*.98);ctx.save();ctx.shadowColor='#000a';ctx.shadowBlur=s*.25;ctx.fillStyle='#0009';ctx.beginPath();ctx.ellipse(pos.x,pos.y+s*.52,s*.48,s*.16,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;const body=ctx.createLinearGradient(pos.x-s*.48,pos.y-s*.45,pos.x+s*.38,pos.y+s*.55);body.addColorStop(0,power>0?'#9ceeff':g.color);body.addColorStop(.52,power>0?'#499de9':'#713d9b');body.addColorStop(1,power>0?'#245db5':'#30204d');ctx.fillStyle=body;ctx.beginPath();ctx.moveTo(pos.x-s*.4,pos.y+s*.35);ctx.quadraticCurveTo(pos.x-s*.55,pos.y-s*.35,pos.x,pos.y-s*.48);ctx.quadraticCurveTo(pos.x+s*.55,pos.y-s*.35,pos.x+s*.4,pos.y+s*.35);ctx.lineTo(pos.x+s*.28,pos.y+s*.48);ctx.lineTo(pos.x+s*.08,pos.y+s*.34);ctx.lineTo(pos.x-s*.08,pos.y+s*.49);ctx.lineTo(pos.x-s*.28,pos.y+s*.34);ctx.closePath();ctx.fill();ctx.strokeStyle='#ffffff55';ctx.lineWidth=Math.max(1,s*.04);ctx.stroke();const mask=ctx.createLinearGradient(pos.x-s*.3,pos.y-s*.35,pos.x+s*.28,pos.y+s*.42);mask.addColorStop(0,'#fff8e7');mask.addColorStop(.5,'#e0d8d0');mask.addColorStop(1,'#9b99ac');ctx.fillStyle=mask;ctx.beginPath();if(g.kind===1){ctx.ellipse(pos.x,pos.y,s*.31,s*.43,0,0,Math.PI*2);}else{ctx.ellipse(pos.x,pos.y-s*.02,s*.34,s*.39,0,0,Math.PI*2);}ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,s*.025);ctx.stroke();ctx.fillStyle='#20192c';if(g.kind===0){ctx.beginPath();ctx.ellipse(pos.x-s*.14,pos.y-s*.08,s*.06,s*.15,-.12,0,Math.PI*2);ctx.ellipse(pos.x+s*.14,pos.y-s*.08,s*.06,s*.15,.12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8e3644';ctx.beginPath();ctx.ellipse(pos.x,pos.y+s*.23,s*.095,s*.04,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#cf5553';for(const dx of [-.23,.23])for(const dy of [-.22,.12]){ctx.beginPath();ctx.arc(pos.x+s*dx,pos.y+s*dy,s*.026,0,Math.PI*2);ctx.fill();}}else if(g.kind===1){ctx.beginPath();ctx.ellipse(pos.x-s*.13,pos.y-s*.1,s*.07,s*.13,-.2,0,Math.PI*2);ctx.ellipse(pos.x+s*.13,pos.y-s*.1,s*.07,s*.13,.2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(pos.x,pos.y+s*.2,s*.09,s*.16,0,0,Math.PI*2);ctx.fill();}else{ctx.beginPath();ctx.ellipse(pos.x-s*.14,pos.y-s*.06,s*.08,s*.045,0,0,Math.PI*2);ctx.ellipse(pos.x+s*.14,pos.y-s*.06,s*.08,s*.045,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#513341';ctx.lineWidth=Math.max(1,s*.055);ctx.beginPath();ctx.moveTo(pos.x-s*.16,pos.y+s*.22);ctx.quadraticCurveTo(pos.x,pos.y+s*.32,pos.x+s*.16,pos.y+s*.22);ctx.stroke();}ctx.restore();}
function render(t){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);if(!maze.length){requestAnimationFrame(render);return;}for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){if(maze[y][x])drawWall(x,y);else{drawFloor(x,y);const item=items[y]?.[x],p=projectedCenter(x,y),dims=projectedSize(y),r=Math.max(2,Math.min(dims.w,dims.h)*.13);if(item==='c'){ctx.save();ctx.shadowColor='#ffe66e';ctx.shadowBlur=r*2.5;const orb=ctx.createRadialGradient(p.x-r*.3,p.y-r*.35,1,p.x,p.y,r*1.4);orb.addColorStop(0,'#fffbc2');orb.addColorStop(.4,'#ffe84c');orb.addColorStop(1,'#db862c');ctx.fillStyle=orb;ctx.beginPath();ctx.ellipse(p.x,p.y,r,r*.78,0,0,Math.PI*2);ctx.fill();ctx.restore();}else if(item==='p'){const q=r*2.3;ctx.save();ctx.shadowColor='#ff812a';ctx.shadowBlur=q*.8;const pumpkin=ctx.createRadialGradient(p.x-q*.25,p.y-q*.25,1,p.x,p.y,q);pumpkin.addColorStop(0,'#fff0a0');pumpkin.addColorStop(.42,'#ffaf38');pumpkin.addColorStop(1,'#e34c19');ctx.fillStyle=pumpkin;ctx.beginPath();ctx.ellipse(p.x,p.y,q*.75,q*.65,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b94a20';ctx.lineWidth=Math.max(1,q*.1);for(const k of [-.35,0,.35]){ctx.beginPath();ctx.ellipse(p.x+q*k,p.y,q*.24,q*.55,0,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#71a448';ctx.beginPath();ctx.ellipse(p.x,p.y-q*.62,q*.13,q*.22,-.28,0,Math.PI*2);ctx.fill();ctx.restore();}}}
 const px=player.fromX+(player.x-player.fromX)*player.t,py=player.fromY+(player.y-player.fromY)*player.t;for(const g of ghosts){const gx=g.fromX+(g.x-g.fromX)*Math.min(1,g.t),gy=g.fromY+(g.y-g.fromY)*Math.min(1,g.t);drawMonster({...g,x:gx,y:gy},t);}if(state!=='menu')drawVladi(px,py,t);if(state==='playing'){const dt=Math.min((t-last)/1000,.05);last=t;acc+=dt;const step=Math.max(.105,.155-(level-1)*.003);if(player.t<1)player.t=Math.min(1,player.t+dt/(step*.72));if(player.t>=1){while(acc>=step){acc-=step;if(queued){const [dx,dy]=dirs[queued];if(passable(player.x+dx,player.y+dy)){movePlayer(queued);break;}}const[dx,dy]=dirs[dir];if(passable(player.x+dx,player.y+dy)){movePlayer(dir);break;}acc=0;break;}}ghostAcc+=dt;const ghostStep=Math.max(.36,.86-(level-1)*.025);if(ghostAcc>ghostStep){ghostAcc=0;moveGhosts();}if(power>0)power=Math.max(0,power-dt);checkCollisions();checkClear();updateHud();}for(const g of ghosts)if(g.t<1)g.t=Math.min(1,g.t+.12);requestAnimationFrame(render);}
requestAnimationFrame(render);
if(new URLSearchParams(location.search).has('test')){window.__mazeDebug={get state(){return state},get level(){return level},get score(){return score},get lives(){return lives},get power(){return power},get player(){return{x:player.x,y:player.y}},get candyCount(){return items.flat().filter(x=>x==='c').length},get pumpkinCount(){return items.flat().filter(x=>x==='p').length},get monsters(){return ghosts.length},putItemAhead(type){for(const[name,[dx,dy]]of Object.entries(dirs)){const x=player.x+dx,y=player.y+dy;if(passable(x,y)){items[y][x]=type;return name;}}return null;},placeNextGhost(){const g=ghosts[0];g.x=player.x;g.y=player.y;g.fromX=g.x;g.fromY=g.y;g.t=1;checkCollisions();},forcePower(){power=9;updateHud();},completeLevel(){items=items.map(r=>r.map(()=>''));checkClear();},start,nextLevel,pause,resume,setDir,resize};const tools=document.createElement('aside');tools.id='qa';tools.style.cssText='position:fixed;z-index:20;left:6px;bottom:6px;display:flex;gap:3px;max-width:98vw;flex-wrap:wrap';for(const[label,fn]of [['CARAMELO',()=>{const d=window.__mazeDebug.putItemAhead('c');if(d)setDir(d)}],['CALABAZA',()=>{const d=window.__mazeDebug.putItemAhead('p');if(d)setDir(d)}],['CHOQUE',()=>window.__mazeDebug.placeNextGhost()],['GOLPE',()=>{power=0;window.__mazeDebug.placeNextGhost()}],['NIVEL',()=>window.__mazeDebug.completeLevel()]]){const b=document.createElement('button');b.textContent=label;b.style.cssText='font:700 10px system-ui;padding:5px;background:#fff;color:#111;border:1px solid #333;border-radius:5px';b.onclick=fn;tools.append(b)}document.body.append(tools);}
})();
