(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d'),arena=$('arena');
const ui={level:$('level'),score:$('score'),best:$('best'),lives:$('lives'),menuBest:$('menuBest'),menu:$('menu'),pause:$('pauseOverlay'),level:$('levelOverlay'),over:$('over'),toast:$('toast'),powerbar:$('powerbar'),powerfill:$('powerfill')};
const dirs={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]};
let level=1,score=0,best=+(localStorage.getItem('vladiHalloweenBest')||0),lives=3,state='menu',cols=21,rows=21,maze=[],items=[],player,ghosts=[],cell=20,ox=0,oy=0,acc=0,ghostAcc=0,last=0,power=0,invuln=0,queued=null,dir='left',sound=true,audio=null,toastTimer=0,anim=0,swipeStart=null;
$('best').textContent=ui.menuBest.textContent=best;
const sprite=new Image();sprite.src='../vladi-run/assets/vladi-runner.webp';
function resize(){const rect=arena.getBoundingClientRect();const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const header=document.querySelector('.top').getBoundingClientRect().height,footer=document.querySelector('.bottom').getBoundingClientRect().height;let availW=rect.width-12,availH=rect.height-12;cell=Math.max(7,Math.floor(Math.min(availW/cols,availH/rows)));ox=(rect.width-cols*cell)/2;oy=(rect.height-rows*cell)/2;}
new ResizeObserver(resize).observe(arena);window.addEventListener('orientationchange',()=>setTimeout(resize,100));
function generateMaze(){cols=Math.min(31,21+2*Math.floor((level-1)/2));rows=Math.min(27,21+2*Math.floor((level-1)/3));if(cols%2===0)cols--;if(rows%2===0)rows--;maze=Array.from({length:rows},()=>Array(cols).fill(1));let stack=[[1,1]];maze[1][1]=0;while(stack.length){const [x,y]=stack[stack.length-1],opts=[];for(const [dx,dy]of [[0,-2],[2,0],[0,2],[-2,0]]){const nx=x+dx,ny=y+dy;if(nx>0&&ny>0&&nx<cols-1&&ny<rows-1&&maze[ny][nx])opts.push([nx,ny,dx,dy]);}if(!opts.length){stack.pop();continue;}const[nx,ny,dx,dy]=opts[Math.floor(Math.random()*opts.length)];maze[y+dy/2][x+dx/2]=0;maze[ny][nx]=0;stack.push([nx,ny]);}
 // Add a few loops so chases have alternate routes.
 for(let i=0;i<Math.floor(cols*rows*.035);i++){const x=1+Math.floor(Math.random()*(cols-2)),y=1+Math.floor(Math.random()*(rows-2));if(maze[y][x]&&((maze[y-1][x]===0&&maze[y+1][x]===0)||(maze[y][x-1]===0&&maze[y][x+1]===0)))maze[y][x]=0;}
 player={x:1,y:1,fromX:1,fromY:1,t:1};let open=[];for(let y=1;y<rows-1;y++)for(let x=1;x<cols-1;x++)if(!maze[y][x]&&!(x===1&&y===1))open.push({x,y});open.sort((a,b)=>dist(b)-dist(a));function dist(p){return Math.abs(p.x-1)+Math.abs(p.y-1)}
 ghosts=[];const ghostCount=Math.min(4,2+Math.floor((level-1)/2));for(let i=0;i<ghostCount;i++){const p=open.splice(Math.min(open.length-1,Math.floor(open.length*.15)),1)[0]||{x:cols-2,y:rows-2};ghosts.push({x:p.x,y:p.y,fromX:p.x,fromY:p.y,t:1,color:['#ff675f','#9a7cff','#48d9d0','#ff9b47'][i],kind:i%3});}
 const farther=open.filter(p=>dist(p)>3);items=Array.from({length:rows},()=>Array(cols).fill(''));for(const p of open)items[p.y][p.x]='c';const powers=Math.min(4,2+Math.floor((level-1)/3));for(let i=0;i<powers&&farther.length;i++){const idx=Math.floor(i*(farther.length-1)/Math.max(1,powers-1));const p=farther[idx];items[p.y][p.x]='p';}resize();updateHud();}
function updateHud(){ui.level.textContent=level;ui.score.textContent=score;ui.best.textContent=best;ui.lives.textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);ui.menuBest.textContent=best;ui.powerbar.classList.toggle('hiddenbar',power<=0);ui.powerfill.style.width=`${Math.min(100,power/9*100)}%`;}
function beep(freq=500,dur=.07,type='sine',vol=.04){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur);}catch{}}
function blip(kind){if(kind==='candy')beep(720,.045,'triangle');else if(kind==='pumpkin'){[440,660,880].forEach((f,i)=>setTimeout(()=>beep(f,.14,'sine',.055),i*75));}else if(kind==='eat')beep(220,.18,'square',.035);else if(kind==='hit'){beep(130,.26,'sawtooth',.06);}else if(kind==='win'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>beep(f,.16),i*95));}}
function pop(msg){ui.toast.textContent=msg;ui.toast.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('on'),1050)}
function setDir(d){if(state!=='playing')return;queued=d;const v=dirs[d],nx=player.x+v[0],ny=player.y+v[1];if(!maze[ny]?.[nx])movePlayer(d);}
function movePlayer(d){if(state!=='playing'||player.t<1)return;const [dx,dy]=dirs[d],nx=player.x+dx,ny=player.y+dy;if(maze[ny]?.[nx]!==0)return;dir=d;queued=null;player.fromX=player.x;player.fromY=player.y;player.x=nx;player.y=ny;player.t=0;collect();checkCollisions();}
function collect(){const item=items[player.y]?.[player.x];if(item==='c'){items[player.y][player.x]='';score+=10;blip('candy');}else if(item==='p'){items[player.y][player.x]='';power=9;score+=50;blip('pumpkin');pop('¡PODER DE CALABAZA!');}updateHud();}
function passable(x,y){return maze[y]?.[x]===0;}
function pathStep(g){let q=[[g.x,g.y]],seen=new Set([g.x+','+g.y]),prev=new Map(),target=player.x+','+player.y;while(q.length){const [x,y]=q.shift(),key=x+','+y;if(key===target)break;for(const [dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=x+dx,ny=y+dy,k=nx+','+ny;if(passable(nx,ny)&&!seen.has(k)){seen.add(k);prev.set(k,key);q.push([nx,ny]);}}}if(!seen.has(target))return null;let k=target;while(prev.get(k)&&prev.get(k)!==g.x+','+g.y)k=prev.get(k);const [x,y]=k.split(',').map(Number);return{x,y};}
function moveGhosts(){for(const g of ghosts){let next;if(power>0){const dirs4=[[0,-1],[1,0],[0,1],[-1,0]],opts=dirs4.map(([dx,dy])=>({x:g.x+dx,y:g.y+dy})).filter(p=>passable(p.x,p.y));opts.sort((a,b)=>Math.abs(b.x-player.x)+Math.abs(b.y-player.y)-(Math.abs(a.x-player.x)+Math.abs(a.y-player.y)));next=opts[0];}else next=pathStep(g);if(!next)continue;g.fromX=g.x;g.fromY=g.y;g.x=next.x;g.y=next.y;g.t=0;checkCollisions();if(state!=='playing')return;}}
function checkCollisions(){for(const g of ghosts)if(Math.abs(g.x-player.x)+Math.abs(g.y-player.y)===0){if(power>0){g.x=cols-2;g.y=rows-2;while(!passable(g.x,g.y)){g.x=Math.max(1,g.x-1);if(g.x===1)g.y=Math.max(1,g.y-1);}g.fromX=g.x;g.fromY=g.y;g.t=1;score+=200;blip('eat');pop('+200 · ¡MONSTRUO ATRAPADO!');updateHud();}else if(performance.now()>invuln){lives--;invuln=performance.now()+1700;blip('hit');pop('¡CUIDADO!');player.x=1;player.y=1;player.fromX=1;player.fromY=1;player.t=1;queued=null;updateHud();if(lives<=0)gameOver();}}}
function checkClear(){let left=0;for(const row of items)for(const v of row)if(v)left++;if(!left&&state==='playing'){score+=500;best=Math.max(best,score);localStorage.setItem('vladiHalloweenBest',best);ui.best.textContent=ui.menuBest.textContent=best;ui.doneLevel.textContent=level;ui.level.classList.remove('hidden');state='level';blip('win');}}
function gameOver(){state='over';best=Math.max(best,score);localStorage.setItem('vladiHalloweenBest',best);ui.finalScore.textContent=score;ui.finalLevel.textContent=level;ui.finalBest.textContent=best;ui.over.classList.remove('hidden');updateHud();}
function start(){level=1;score=0;lives=3;power=0;state='playing';for(const id of ['menu','pauseOverlay','levelOverlay','over'])$(id).classList.add('hidden');generateMaze();last=performance.now();}
function nextLevel(){level++;power=0;state='playing';ui.level.classList.add('hidden');generateMaze();pop('¡NIVEL '+level+'!');}
function pause(){if(state==='playing'){state='paused';ui.pause.classList.remove('hidden');}}
function resume(){if(state==='paused'){state='playing';ui.pause.classList.add('hidden');last=performance.now();}}
$('play').onclick=start;$('again').onclick=start;$('next').onclick=nextLevel;$('pause').onclick=()=>state==='paused'?resume():pause();$('resume').onclick=resume;$('restart').onclick=start;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♪';$('sound').setAttribute('aria-label',sound?'Silenciar sonido':'Activar sonido');if(sound)beep(680,.08);};
for(const btn of document.querySelectorAll('.pad button')){btn.addEventListener('pointerdown',e=>{e.preventDefault();setDir(btn.dataset.dir);});}
window.addEventListener('keydown',e=>{const map={ArrowUp:'up',w:'up',W:'up',ArrowRight:'right',d:'right',D:'right',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left'};if(e.key==='Escape'||e.key==='p'||e.key==='P'){e.preventDefault();state==='playing'?pause():state==='paused'?resume():null;return;}if(map[e.key]){e.preventDefault();if(!e.repeat)setDir(map[e.key]);}});
canvas.addEventListener('pointerdown',e=>{swipeStart={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;if(Math.max(Math.abs(dx),Math.abs(dy))>18)setDir(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));swipeStart=null;});
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function drawWall(x,y){const X=ox+x*cell,Y=oy+y*cell;ctx.fillStyle='#201b34';rr(X+1,Y+1,cell-2,cell-2,Math.max(2,cell*.2));ctx.fill();ctx.strokeStyle='#70475d';ctx.lineWidth=Math.max(1,cell*.055);ctx.stroke();ctx.fillStyle='#ff863a';ctx.globalAlpha=.3;ctx.fillRect(X+cell*.18,Y+cell*.16,cell*.64,Math.max(1,cell*.045));ctx.globalAlpha=1;}
function drawVladi(x,y,t){const X=ox+(x+.5)*cell,Y=oy+(y+.5)*cell;ctx.save();ctx.translate(X,Y);const faceDir=dirs[dir];ctx.rotate(Math.atan2(faceDir[1],faceDir[0]));ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,cell*.31,cell*.35,cell*.13,0,0,Math.PI*2);ctx.fill();if(sprite.complete&&sprite.naturalWidth){const sw=sprite.naturalWidth/4,sh=sprite.naturalHeight,frame=Math.floor(t/125)%4;const h=cell*.94,w=h*(sw/sh);ctx.drawImage(sprite,frame*sw,0,sw,sh,-w/2,-h/2,w,h);}else{ctx.fillStyle='#ffc89e';ctx.beginPath();ctx.arc(0,0,cell*.36,0,Math.PI*2);ctx.fill();ctx.fillStyle='#513221';ctx.fillRect(-cell*.31,-cell*.36,cell*.62,cell*.14);ctx.fillStyle='#4c8ad8';ctx.fillRect(-cell*.27,cell*.12,cell*.54,cell*.25);ctx.fillStyle='#241522';ctx.beginPath();ctx.arc(cell*.13,-cell*.04,Math.max(1,cell*.04),0,Math.PI*2);ctx.fill();}ctx.restore();}
function drawMonster(g,t){const x=ox+(g.x+.5)*cell,y=oy+(g.y+.5)*cell;const s=cell*.35;ctx.save();ctx.translate(x,y);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,s*.95,s*.9,s*.28,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=power>0?'#72d7ff':g.color;ctx.beginPath();ctx.arc(0,0,s,Math.PI,0);ctx.lineTo(s,s*.65);for(let i=0;i<4;i++)ctx.lineTo(s-s*.5*(i+1),s*(i%2?.52:.85));ctx.closePath();ctx.fill();ctx.fillStyle='#f4eadf';ctx.beginPath();ctx.ellipse(0,-s*.04,s*.62,s*.68,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#262032';if(g.kind===0){ctx.beginPath();ctx.ellipse(-s*.25,-s*.12,s*.13,s*.22,-.2,0,Math.PI*2);ctx.ellipse(s*.25,-s*.12,s*.13,s*.22,.2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b44345';ctx.fillRect(-s*.17,s*.33,s*.34,s*.06);}else if(g.kind===1){ctx.beginPath();ctx.arc(-s*.25,-s*.08,s*.13,0,Math.PI*2);ctx.arc(s*.25,-s*.08,s*.13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d65d56';ctx.beginPath();ctx.arc(0,s*.3,s*.12,0,Math.PI*2);ctx.fill();}else{ctx.fillRect(-s*.42,-s*.14,s*.24,s*.1);ctx.fillRect(s*.18,-s*.14,s*.24,s*.1);ctx.beginPath();ctx.moveTo(-s*.2,s*.28);ctx.lineTo(s*.2,s*.28);ctx.strokeStyle='#633c49';ctx.lineWidth=Math.max(1,s*.07);ctx.stroke();}ctx.restore();}
function render(t){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);if(!maze.length){requestAnimationFrame(render);return;}for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){if(maze[y][x])drawWall(x,y);else{const item=items[y]?.[x];if(item==='c'){ctx.fillStyle='#ffd88b';ctx.shadowColor='#ffbd62';ctx.shadowBlur=cell*.32;ctx.beginPath();ctx.arc(ox+(x+.5)*cell,oy+(y+.5)*cell,Math.max(1.5,cell*.095),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}else if(item==='p'){const X=ox+(x+.5)*cell,Y=oy+(y+.5)*cell;ctx.save();ctx.shadowColor='#ff922b';ctx.shadowBlur=cell*.55;ctx.fillStyle='#ff8a34';ctx.beginPath();ctx.arc(X,Y,cell*.31,0,Math.PI*2);ctx.fill();ctx.fillStyle='#426f42';ctx.beginPath();ctx.ellipse(X,Y-cell*.28,cell*.1,cell*.17,-.3,0,Math.PI*2);ctx.fill();ctx.restore();}}}
 const px=player.x+(player.x-player.fromX)*(1-player.t),py=player.y+(player.y-player.fromY)*(1-player.t);if(state!=='menu')drawVladi(px,py,t);for(const g of ghosts){const gx=g.fromX+(g.x-g.fromX)*Math.min(1,g.t),gy=g.fromY+(g.y-g.fromY)*Math.min(1,g.t);drawMonster({...g,x:gx,y:gy},t);}if(state==='playing'){const dt=Math.min((t-last)/1000,.05);last=t;acc+=dt;const step=Math.max(.105,.155-(level-1)*.003);if(player.t<1)player.t=Math.min(1,player.t+dt/(step*.72));if(player.t>=1){while(acc>=step){acc-=step;if(queued){const [dx,dy]=dirs[queued];if(passable(player.x+dx,player.y+dy)){movePlayer(queued);break;}}const[dx,dy]=dirs[dir];if(passable(player.x+dx,player.y+dy)){movePlayer(dir);break;}acc=0;break;}}ghostAcc+=dt;const ghostStep=Math.max(.36,.74-(level-1)*.025);if(ghostAcc>ghostStep){ghostAcc=0;moveGhosts();}if(power>0)power=Math.max(0,power-dt);checkCollisions();checkClear();updateHud();}for(const g of ghosts)if(g.t<1)g.t=Math.min(1,g.t+.12);requestAnimationFrame(render);}
requestAnimationFrame(render);if(new URLSearchParams(location.search).has('test')){window.__mazeDebug={get state(){return state},get level(){return level},get score(){return score},get lives(){return lives},get power(){return power},get player(){return{x:player.x,y:player.y}},get candyCount(){return items.flat().filter(x=>x==='c').length},get pumpkinCount(){return items.flat().filter(x=>x==='p').length},get monsters(){return ghosts.length},putItemAhead(type){for(const[name,[dx,dy]]of Object.entries(dirs)){const x=player.x+dx,y=player.y+dy;if(passable(x,y)){items[y][x]=type;return name;}}return null;},placeNextGhost(){const g=ghosts[0];g.x=player.x;g.y=player.y;g.fromX=g.x;g.fromY=g.y;g.t=1;checkCollisions();},forcePower(){power=9;updateHud();},completeLevel(){items=items.map(r=>r.map(()=>''));checkClear();},start,nextLevel,pause,resume,setDir,resize};const tools=document.createElement('aside');tools.id='qa';tools.style.cssText='position:fixed;z-index:20;left:6px;bottom:6px;display:flex;gap:3px;max-width:98vw;flex-wrap:wrap';for(const[label,fn]of [['CARAMELO',()=>{const d=window.__mazeDebug.putItemAhead('c');if(d)setDir(d)}],['CALABAZA',()=>{const d=window.__mazeDebug.putItemAhead('p');if(d)setDir(d)}],['CHOQUE',()=>window.__mazeDebug.placeNextGhost()],['NIVEL',()=>window.__mazeDebug.completeLevel()]]){const b=document.createElement('button');b.textContent=label;b.style.cssText='font:700 10px system-ui;padding:5px;background:#fff;color:#111;border:1px solid #333;border-radius:5px';b.onclick=fn;tools.append(b)}document.body.append(tools);}
})();
