(()=>{'use strict';
const canvas=document.querySelector('#field'),viewCtx=canvas.getContext('2d');let ctx=viewCtx;
const backgroundCanvas=document.createElement('canvas');let backgroundCtx=backgroundCanvas.getContext('2d');
const ui={score:document.querySelector('#score'),shot:document.querySelector('#shot'),best:document.querySelector('#best'),panel:document.querySelector('#panel'),title:document.querySelector('#title'),eyebrow:document.querySelector('#eyebrow'),desc:document.querySelector('#desc'),instructions:document.querySelector('#instructions'),pills:document.querySelector('#pills'),start:document.querySelector('#start'),foot:document.querySelector('#foot'),result:document.querySelector('#result'),grid:document.querySelector('#aimGrid'),zones:[...document.querySelectorAll('.aimZone')],hint:document.querySelector('#hint'),feedback:document.querySelector('#feedback'),kick:document.querySelector('#kick'),pause:document.querySelector('#pause')};
const STORE='vladiFutbolBest';let W=innerWidth,H=innerHeight,D=1,phase='menu',last=0,time=0,score=0,best=0,round=1,shots=0,shotsInRound=0,streak=0,maxStreak=0,lives=3,selected=-1,shot=null,keeperTarget=4,keeperProgress=1,keeperHold=0,lastZone=-1,zoneStreak=0,transition=0,feedbackTime=0,feedbackText='',crowd=[],sparkles=[],animationFrame=0,playerCanvas=null,playerMetrics=null;
const player=new Image();player.src='./assets/vladi-futbol.webp';player.addEventListener('load',()=>{preparePlayerSprite();draw()});
const ballSprite=document.createElement('canvas');ballSprite.width=256;ballSprite.height=256;
try{best=+(localStorage.getItem(STORE)||0)}catch(_){}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),choose=a=>a[Math.floor(Math.random()*a.length)];
function goal(){const w=Math.min(W*.82,760),h=Math.min(H*.275,330);return{x:(W-w)/2,y:H*.275,w,h}}
function fit(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx=viewCtx;ctx.setTransform(D,0,0,D,0,0);crowd=Array.from({length:Math.max(120,Math.floor(W*H/1700))},()=>({x:Math.random()*W,y:rand(H*.09,H*.29),r:rand(1,2.6),c:choose(['#ffe2a0','#f2f6ff','#ff6b70','#55d8ee','#82edaa','#ffc34b'])}));sparkles=Array.from({length:45},()=>({x:Math.random()*W,y:Math.random()*H,r:rand(.5,1.5),p:rand(0,7)}));buildBackground();preparePlayerSprite();positionGrid();draw()}
addEventListener('resize',fit,{passive:true});
function buildBackground(){backgroundCanvas.width=Math.round(W*D);backgroundCanvas.height=Math.round(H*D);backgroundCtx=backgroundCanvas.getContext('2d');const previous=ctx;ctx=backgroundCtx;ctx.setTransform(D,0,0,D,0,0);fieldBackground();drawGoal();ctx=previous}
function preparePlayerSprite(){if(!player.complete||!player.naturalWidth||!W||!H)return;const h=Math.min(H*.34,W*.54),w=h*player.naturalWidth/player.naturalHeight,pad=24;const sprite=document.createElement('canvas');sprite.width=Math.ceil((w+pad*2)*D);sprite.height=Math.ceil((h+pad*2)*D);const c=sprite.getContext('2d');c.setTransform(D,0,0,D,0,0);c.shadowColor='#06140f';c.shadowBlur=16;c.shadowOffsetY=8;c.drawImage(player,pad,pad,w,h);playerCanvas=sprite;playerMetrics={w,h,pad}}
function prepareBallSprite(){const c=ballSprite.getContext('2d'),cx=128,cy=128,r=111;c.clearRect(0,0,256,256);const leather=c.createRadialGradient(cx-r*.34,cy-r*.4,r*.05,cx,cy,r);leather.addColorStop(0,'#fff');leather.addColorStop(.7,'#f4f6f6');leather.addColorStop(1,'#bcc9ce');c.fillStyle=leather;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.save();c.beginPath();c.arc(cx,cy,r*.95,0,Math.PI*2);c.clip();c.fillStyle='#17232c';const pentagon=(x,y,size,angle)=>{c.beginPath();for(let i=0;i<5;i++){const a=angle+i*Math.PI*2/5,px=x+Math.cos(a)*size,py=y+Math.sin(a)*size;if(!i)c.moveTo(px,py);else c.lineTo(px,py)}c.closePath();c.fill()};pentagon(cx,cy,r*.245,-Math.PI/2);for(let i=0;i<5;i++){const a=-Math.PI/2+i*Math.PI*2/5;pentagon(cx+Math.cos(a)*r*.62,cy+Math.sin(a)*r*.62,r*.205,a+Math.PI/5)}c.strokeStyle='#3b4a52';c.lineWidth=2.4;c.beginPath();for(let i=0;i<5;i++){const a=-Math.PI/2+i*Math.PI*2/5;c.moveTo(cx+Math.cos(a)*r*.27,cy+Math.sin(a)*r*.27);c.lineTo(cx+Math.cos(a)*r*.94,cy+Math.sin(a)*r*.94)}c.stroke();c.restore();c.strokeStyle='#c5d1d5';c.lineWidth=4;c.beginPath();c.arc(cx,cy,r*.91,0,Math.PI*2);c.stroke();c.strokeStyle='#ffffffb8';c.lineWidth=3;c.beginPath();c.arc(cx,cy,r*.78,Math.PI*1.08,Math.PI*1.52);c.stroke()}
function snd(n){window.VladiSound?.play(n)}
function syncHUD(){ui.score.textContent=score;ui.shot.textContent=Math.min(shotsInRound+1,5)+'/5';ui.shot.closest('.stat').querySelector('small').textContent='TANDA '+round;ui.best.textContent=best}
function syncView(){const live=phase==='playing';ui.panel.hidden=live;ui.grid.style.display=live&&!shot?'grid':'none';ui.hint.style.display=live&&!shot?'block':'none';ui.kick.style.display=live?'block':'none';ui.kick.disabled=!live||selected<0||!!shot;ui.pause.style.display=live||phase==='paused'?'grid':'none';ui.zones.forEach((b,i)=>{b.classList.toggle('selected',i===selected);b.disabled=!live||!!shot});}
function showPanel(mode){ui.panel.hidden=false;ui.result.hidden=true;ui.instructions.style.display='block';ui.pills.style.display='flex';
 if(mode==='menu'){ui.eyebrow.textContent='ARCADE DE PENALES';ui.title.innerHTML='VLADI<br>FÚTBOL';ui.desc.textContent='¡Es hora de los penales! Apuntá y tratá de vencer al arquero.';ui.instructions.innerHTML='<b>TOCÁ UNA ZONA DEL ARCO</b> y apretá <b>PATEAR</b>. Cambiá de esquina: el arquero aprende si repetís el tiro. En PC usá las flechas y espacio.';ui.pills.innerHTML='<span>⚽ 5 tiros por tanda</span><span>🧤 El arquero se adapta</span>';ui.start.textContent='▶  EMPEZAR';ui.foot.textContent='Récord: '+best+' goles'}
 if(mode==='paused'){ui.eyebrow.textContent='DESCANSO ENTRE PENALES';ui.title.textContent='PAUSA';ui.desc.textContent='La tanda queda pausada. Cuando quieras, seguí pateando.';ui.instructions.style.display='none';ui.pills.style.display='none';ui.start.textContent='▶  SEGUIR JUGANDO';ui.foot.textContent='Goles: '+score+' · Tanda '+round}
 if(mode==='over'){ui.eyebrow.textContent='FIN DEL PARTIDO';ui.title.textContent='¡BUENA TANDA!';ui.desc.textContent=score?'¡Buen trabajo, Vladi! Volvé a intentarlo y superá tu récord.':'El arquero estuvo atento. ¡Probá otra vez!';ui.instructions.style.display='none';ui.pills.innerHTML='<span>Tandas: '+round+'</span><span>Mejor racha: '+maxStreak+'×</span>';ui.start.textContent='↻  JUGAR OTRA VEZ';ui.foot.textContent='Récord: '+best+' goles';ui.result.textContent='Marcaste '+score+' '+(score===1?'gol':'goles');ui.result.hidden=false}
}
function reset(){score=0;round=1;shots=0;shotsInRound=0;streak=0;maxStreak=0;lives=3;selected=-1;shot=null;keeperProgress=0;keeperHold=0;lastZone=-1;zoneStreak=0;transition=.55;phase='playing';syncHUD();syncView();snd('start');startLoop()}
function pause(){if(phase==='playing'){phase='paused';showPanel('paused');syncView();snd('pause');draw()}else if(phase==='paused'){phase='playing';syncView();snd('resume');startLoop()}}
function say(s,d=.9){feedbackText=s;feedbackTime=d;ui.feedback.textContent=s;ui.feedback.classList.add('show')}
function setTarget(i){if(phase!=='playing'||shot)return;selected=clamp(i,0,5);ui.zones.forEach((b,n)=>b.classList.toggle('selected',n===selected));ui.kick.disabled=false;say(['ESQUINA ALTA','AL MEDIO','ESQUINA ALTA','ESQUINA BAJA','AL MEDIO','ESQUINA BAJA'][selected],.55)}
function kick(){if(phase!=='playing'||shot)return;if(selected<0){say('ELEGÍ UNA ZONA DEL ARCO');return}const g=goal(),col=selected%3,row=Math.floor(selected/3);const tx=g.x+g.w*(.17+col*.33),ty=g.y+g.h*(.31+row*.38);zoneStreak=selected===lastZone?zoneStreak+1:0;lastZone=selected;const keeperChance=Math.min(.84,.46+(round-1)*.085+Math.min(zoneStreak*.13,.26)+Math.min(score*.003,.06));const saved=Math.random()<keeperChance;keeperTarget=saved?selected:choose([0,1,2,3,4,5].filter(x=>x!==selected));keeperProgress=0;keeperHold=1.45;shot={x:W*.45,y:H*.84,sx:W*.45,sy:H*.84,tx,ty,t:0,duration:.62,saved,zone:selected};shots++;shotsInRound++;selected=-1;syncView();snd('kick')}
function finishShot(){if(!shot)return;const saved=shot.saved;shot=null;selected=-1;if(saved){lives--;streak=0;say('¡ATAJÓ!',.9);snd('save')}else{score++;streak++;maxStreak=Math.max(maxStreak,streak);if(score>best){best=score;try{localStorage.setItem(STORE,String(best))}catch(_){}}say(choose(['¡GOL!','¡GOLAZO!','¡IMPARABLE!']),.95);snd('goal')}
 syncHUD();if(lives<=0){phase='over';syncView();showPanel('over');snd('gameover');return}if(shotsInRound>=5){round++;shotsInRound=0;lives=Math.min(3,lives+1);transition=1.4;say('¡TANDA COMPLETA! +1 OPORTUNIDAD',1.2);syncHUD()}else transition=.9;syncView();
}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function fieldBackground(){const sky=ctx.createLinearGradient(0,0,0,H*.57);sky.addColorStop(0,'#06142a');sky.addColorStop(.55,'#16436a');sky.addColorStop(1,'#28788b');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
 // stadium roof and the light haze
 ctx.fillStyle='#071225';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(W,0);ctx.lineTo(W,H*.105);ctx.quadraticCurveTo(W*.5,H*.04,0,H*.105);ctx.fill();
 for(let i=0;i<7;i++){let x=(i+.5)*W/7;ctx.save();ctx.shadowColor='#c8edff';ctx.shadowBlur=20;ctx.fillStyle='#f7fbff';rr(x-19,H*.07,38,7,4);ctx.fill();ctx.restore();ctx.globalAlpha=.13;const light=ctx.createLinearGradient(x,H*.08,x,H*.34);light.addColorStop(0,'#d6f4ff');light.addColorStop(1,'#d6f4ff00');ctx.fillStyle=light;ctx.beginPath();ctx.moveTo(x-6,H*.08);ctx.lineTo(x+6,H*.08);ctx.lineTo(x+W*.07,H*.34);ctx.lineTo(x-W*.07,H*.34);ctx.fill();ctx.globalAlpha=1}
 // crowd tiers
 const stands=ctx.createLinearGradient(0,H*.09,0,H*.34);stands.addColorStop(0,'#283d56');stands.addColorStop(.55,'#13263d');stands.addColorStop(1,'#0b1c30');ctx.fillStyle=stands;ctx.fillRect(0,H*.09,W,H*.25);
 crowd.forEach(p=>{ctx.fillStyle=p.c;ctx.globalAlpha=.35;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;
 for(let k=0;k<3;k++){ctx.fillStyle=k===1?'#e4a839':'#dceafa';ctx.globalAlpha=.86;ctx.fillRect(0,H*(.16+k*.073),W,2);ctx.globalAlpha=1}
 // crowd banners
 for(let i=0;i<5;i++){const x=(i+.5)*W/5;ctx.fillStyle=i%2?'#15556c':'#1b3650';rr(x-W*.045,H*.24,W*.09,H*.055,4);ctx.fill();ctx.fillStyle='#f6d170';ctx.font='900 '+Math.max(8,W*.011)+'px system-ui';ctx.textAlign='center';ctx.fillText(i%2?'VLADI FC':'¡DALE!',x,H*.275)}
 // field and pitch perspective
 const gy=goal().y;const turf=ctx.createLinearGradient(0,gy,0,H);turf.addColorStop(0,'#58bd75');turf.addColorStop(.14,'#258456');turf.addColorStop(1,'#07503f');ctx.fillStyle=turf;ctx.beginPath();ctx.moveTo(0,gy+H*.21);ctx.lineTo(W,gy+H*.21);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();
 for(let i=0;i<8;i++){const y=gy+H*.22+i*(H-gy-H*.22)/8;ctx.fillStyle=i%2?'#ffffff08':'#071c1510';ctx.fillRect(0,y,W,(H-gy-H*.22)/8)}
 // Markings drawn as closed perspective rectangles; each baseline connects its own sides.
 ctx.strokeStyle='#f0ffe7aa';ctx.lineWidth=Math.max(1.4,Math.min(W,H)*.0025);ctx.lineJoin='round';ctx.beginPath();
 ctx.moveTo(W*.18,gy+H*.23);ctx.lineTo(W*.82,gy+H*.23);ctx.lineTo(W*.99,H);ctx.lineTo(W*.01,H);ctx.closePath();
 ctx.moveTo(W*.27,gy+H*.4);ctx.lineTo(W*.73,gy+H*.4);ctx.lineTo(W*.91,H);ctx.lineTo(W*.09,H);ctx.closePath();ctx.stroke();
 ctx.fillStyle='#effff0';ctx.beginPath();ctx.arc(W*.5,gy+H*.48,3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#effff055';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(W*.5,gy+H*.48,W*.065,H*.035,0,0,Math.PI*2);ctx.stroke();
}
function drawSparkles(){sparkles.forEach(p=>{ctx.globalAlpha=.16+.16*Math.sin(time*1.4+p.p);ctx.fillStyle='#fff2ca';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1}
function ballRadius(){return clamp(Math.min(H*.34,W*.54)*.085,16,28)}
function drawBall(x,y,r,rot=0){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.globalAlpha=.2;ctx.fillStyle='#00121a';ctx.beginPath();ctx.ellipse(r*.18,r*.58,r*.64,r*.2,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.drawImage(ballSprite,-r,-r,r*2,r*2);ctx.restore()}
function drawGoal(){const g=goal(),post=Math.max(6,W*.009);ctx.save();
 // goal shadow and net body
 ctx.fillStyle='#00141a55';ctx.beginPath();ctx.ellipse(W*.5,g.y+g.h+14,g.w*.53,19,0,0,Math.PI*2);ctx.fill();
 const net=ctx.createLinearGradient(0,g.y,0,g.y+g.h);net.addColorStop(0,'#e7f5ff2b');net.addColorStop(1,'#f7fbff0b');ctx.fillStyle=net;ctx.fillRect(g.x,g.y,g.w,g.h);
 ctx.strokeStyle='#eff9ff48';ctx.lineWidth=1;for(let x=g.x+12;x<g.x+g.w;x+=Math.max(17,g.w*.045)){ctx.beginPath();ctx.moveTo(x,g.y);ctx.lineTo(x,g.y+g.h);ctx.stroke()}for(let y=g.y+12;y<g.y+g.h;y+=Math.max(15,g.h*.11)){ctx.beginPath();ctx.moveTo(g.x,y);ctx.lineTo(g.x+g.w,y);ctx.stroke()}
 // goal frame
 ctx.shadowColor='#d9f3ff88';ctx.shadowBlur=13;ctx.fillStyle='#f8fbff';rr(g.x-post/2,g.y-post/2,g.w+post,g.h+post,post*.4);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#dee9ee';ctx.fillRect(g.x+post*.3,g.y+post*.45,g.w-post*.6,g.h-post*.5);ctx.strokeStyle='#fff';ctx.lineWidth=post*.55;ctx.beginPath();ctx.moveTo(g.x,g.y+g.h);ctx.lineTo(g.x,g.y);ctx.lineTo(g.x+g.w,g.y);ctx.lineTo(g.x+g.w,g.y+g.h);ctx.stroke();ctx.strokeStyle='#c8dce5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(g.x+post,g.y+post);ctx.lineTo(g.x+g.w-post,g.y+post);ctx.stroke();
 ctx.restore();return g}
function drawKeeper(){const g=goal(),cx=W*.5,baseY=g.y+g.h*.88;let dx=0,dy=0,scale=1,tilt=0;const p=keeperProgress;if(p>.01){const cols=[-.32,0,.32],rows=[-.12,.13];dx=cols[keeperTarget%3]*g.w*p;dy=rows[Math.floor(keeperTarget/3)]*g.h*p;tilt=cols[keeperTarget%3]*p*.7;scale=1-.13*p}
 ctx.save();ctx.translate(cx+dx,baseY+dy);ctx.rotate(tilt);ctx.scale(scale,scale);
 // keeper gloves and limbs, with clear silhouette
 ctx.fillStyle='#142338';ctx.beginPath();ctx.ellipse(0,11,42,8,0,0,Math.PI*2);ctx.fill();
 const reach=25+40*p,lift=24+38*p,gloveY=-25-34*p;ctx.strokeStyle='#f0a851';ctx.lineWidth=18;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-18,-55);ctx.lineTo(-reach,-lift);ctx.moveTo(18,-55);ctx.lineTo(reach,-lift);ctx.stroke();
 ctx.strokeStyle='#142944';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(-18,-55);ctx.lineTo(-reach,-lift);ctx.moveTo(18,-55);ctx.lineTo(reach,-lift);ctx.stroke();
 const grad=ctx.createLinearGradient(-35,-88,35,-35);grad.addColorStop(0,'#ffcb62');grad.addColorStop(1,'#de733d');ctx.fillStyle=grad;rr(-31,-87,62,74,20);ctx.fill();ctx.strokeStyle='#fff0ce';ctx.lineWidth=3;ctx.stroke();
 ctx.fillStyle='#dff4fb';rr(-reach-8,gloveY-10,18,23,7);ctx.fill();rr(reach-10,gloveY-10,18,23,7);ctx.fill();ctx.fillStyle='#6ee6ad';ctx.beginPath();ctx.ellipse(-reach,gloveY,13,14,-.2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(reach,gloveY,13,14,.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f3fff3';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-reach-5,gloveY);ctx.lineTo(-reach+5,gloveY);ctx.moveTo(reach-5,gloveY);ctx.lineTo(reach+5,gloveY);ctx.stroke();
 ctx.fillStyle='#eec49b';ctx.beginPath();ctx.arc(0,-105,22,0,Math.PI*2);ctx.fill();ctx.fillStyle='#392821';ctx.beginPath();ctx.arc(0,-111,23,Math.PI,Math.PI*2);ctx.lineTo(22,-104);ctx.quadraticCurveTo(0,-97,-22,-104);ctx.fill();ctx.fillStyle='#18243a';ctx.beginPath();ctx.arc(-7,-105,2,0,Math.PI*2);ctx.arc(7,-105,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#9d4c35';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-98,5,.2,Math.PI-.2);ctx.stroke();ctx.restore();}
function drawPlayer(){if(!playerCanvas||!playerMetrics)return;const{w,h,pad}=playerMetrics,x=W*.45-w*.82,y=H*.53+Math.sin(time*5)*2;ctx.drawImage(playerCanvas,x-pad,y-pad,w+pad*2,h+pad*2);return{x,y,w,h}}
function drawAim(){const g=goal();ctx.save();const pulse=.5+.5*Math.sin(time*4);if(selected>=0&&!shot){const col=selected%3,row=Math.floor(selected/3);const x=g.x+g.w*(col/3),y=g.y+g.h*(row/2);ctx.globalAlpha=.2+pulse*.15;ctx.fillStyle='#ffe18a';ctx.fillRect(x,y,g.w/3,g.h/2);ctx.globalAlpha=1;ctx.strokeStyle='#ffe18a';ctx.lineWidth=3;ctx.strokeRect(x+2,y+2,g.w/3-4,g.h/2-4)}ctx.restore()}
function drawShot(){if(!shot)return;const p=clamp(shot.t/shot.duration,0,1),ease=p*p*(3-2*p),x=shot.sx+(shot.tx-shot.sx)*ease,y=shot.sy+(shot.ty-shot.sy)*ease- Math.sin(Math.PI*p)*H*.1,r=ballRadius()*(1-ease*.48);ctx.save();if(!shot.saved){ctx.strokeStyle='#fff9';ctx.lineWidth=4;ctx.globalAlpha=.35;ctx.beginPath();ctx.moveTo(shot.sx,shot.sy);ctx.lineTo(x,y);ctx.stroke();ctx.globalAlpha=1}drawBall(x,y,r,p*5);ctx.restore()}
function draw(){if(!W||!H)return;ctx=viewCtx;ctx.drawImage(backgroundCanvas,0,0,W,H);if(phase==='playing')drawSparkles();drawKeeper();drawAim();const pos=drawPlayer();if(pos&&!shot){const bx=pos.x+pos.w*.81,by=pos.y+pos.h*.91;drawBall(bx,by,ballRadius(),time*.5)}if(shot)drawShot();
 // lives for saves and round marker remain readable above the shot area
 if(phase==='playing'){ctx.save();ctx.textAlign='left';ctx.font='900 '+Math.max(15,Math.min(20,W*.032))+'px system-ui';ctx.fillStyle='#ff8075';ctx.shadowColor='#0009';ctx.shadowBlur=5;ctx.fillText('🥅 '+'♥ '.repeat(lives),16,H*.17);ctx.restore()}
}
function placeGrid(){const g=goal(),pad=Math.max(8,W*.012);ui.grid.style.left=(g.x+pad)+'px';ui.grid.style.top=(g.y+pad)+'px';ui.grid.style.width=(g.w-pad*2)+'px';ui.grid.style.height=(g.h-pad*2)+'px'}
function positionGrid(){placeGrid()}
function startLoop(){if(!animationFrame&&phase==='playing'){last=performance.now();animationFrame=requestAnimationFrame(loop)}}
function loop(now){animationFrame=0;if(phase!=='playing')return;const dt=Math.min(.1,(now-last)/1000||0);last=now;time+=dt;if(shot){shot.t+=dt;if(shot.t>=shot.duration)finishShot()}else if(transition>0){transition-=dt;if(transition<=0&&lives<=0){phase='over';syncView();showPanel('over');snd('gameover')}}if(shot)keeperProgress=Math.min(1,keeperProgress+dt*3.2);else if(keeperHold>0)keeperHold=Math.max(0,keeperHold-dt);else if(keeperProgress>0)keeperProgress=Math.max(0,keeperProgress-dt*1.7);if(feedbackTime>0){feedbackTime-=dt;if(feedbackTime<=0)ui.feedback.classList.remove('show')}draw();if(phase==='playing')animationFrame=requestAnimationFrame(loop)}
ui.zones.forEach((b,i)=>b.addEventListener('pointerdown',e=>{e.preventDefault();setTarget(i)}));
ui.kick.addEventListener('pointerdown',e=>{e.preventDefault();kick()});
ui.pause.addEventListener('click',pause);
ui.start.addEventListener('click',()=>{if(phase==='paused'){phase='playing';syncView();snd('resume');startLoop()}else reset()});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowleft','arrowright','arrowup','arrowdown','escape','enter'].includes(k))e.preventDefault();if(k==='escape'||k==='p'){pause();return}if((phase==='menu'||phase==='over')&&(k==='enter'||k===' ')){ui.start.click();return}if(phase==='paused'&&(k==='enter'||k===' ')){ui.start.click();return}if(phase!=='playing')return;if(k===' '||k==='enter'){kick();return}let base=selected<0?4:selected,col=base%3,row=Math.floor(base/3);if(k==='arrowleft')col=Math.max(0,col-1);if(k==='arrowright')col=Math.min(2,col+1);if(k==='arrowup')row=0;if(k==='arrowdown')row=1;if(['arrowleft','arrowright','arrowup','arrowdown'].includes(k))setTarget(row*3+col)});
addEventListener('contextmenu',e=>e.preventDefault());
ui.eyebrow.textContent='ARCADE DE PENALES';prepareBallSprite();fit();syncHUD();syncView();showPanel('menu');draw();
})();
