import {Game,WIDTH,HEIGHT} from './engine.mjs';
const g=new Game(),canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),arena=document.querySelector('#arena'),overlay=document.querySelector('#overlay');
const boss=new Image();boss.src='assets/kong.webp';document.querySelector('#bossPortrait').src=boss.src;const runner=new Image();runner.src='../vladi-run/assets/vladi-runner.webp';
const themes=[['TORRE AZUL','#061d3f','#174d69','#34dafa'],['FÁBRICA DORADA','#302013','#75582b','#ffd367'],['CIUDAD VIOLETA','#1c1040','#493077','#bd8cff'],['SELVA NOCTURNA','#082d2b','#176158','#69e0b4'],['FORJA ROJA','#35132a','#783445','#ff978b'],['CUMBRE CELESTE','#122b4b','#295b78','#a4eeff']];let view={w:1,h:1,scale:1,x:0,y:0},background=null,best=0,prev=0,acc=0,lastState='',hudTime=0,muted=true,audio=null,musicAt=0;
try{best=Number(localStorage.getItem('vladi-kong-best')||0)}catch(_){}document.querySelector('#best').textContent=best;
function resize(){const r=arena.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);view={w:r.width,h:r.height,scale:Math.min(r.width/WIDTH,r.height/HEIGHT),x:0,y:0,d};view.x=(r.width-WIDTH*view.scale)/2;view.y=(r.height-HEIGHT*view.scale)/2;background=null}
new ResizeObserver(resize).observe(arena);addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);
function round(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function star(x,y,r){ctx.beginPath();for(let i=0;i<10;i++){let a=-Math.PI/2+i*Math.PI/5,k=i%2?r*.46:r;const xx=x+Math.cos(a)*k,yy=y+Math.sin(a)*k;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)}ctx.closePath();ctx.fillStyle='#ffd550';ctx.fill();ctx.strokeStyle='#fff0a2';ctx.lineWidth=2;ctx.stroke()}
function makeBackground(){background=document.createElement('canvas');background.width=WIDTH;background.height=HEIGHT;const b=background.getContext('2d'),t=themes[(g.level-1)%6];let gr=b.createLinearGradient(0,0,0,HEIGHT);gr.addColorStop(0,t[0]?t[1]:'#061d3f');gr.addColorStop(1,'#030e25');b.fillStyle=gr;b.fillRect(0,0,WIDTH,HEIGHT);for(let i=0;i<16;i++){const x=i*67-35,h=130+(i*79)%230;b.fillStyle=i%2?'#112842':'#0c1d36';b.fillRect(x,HEIGHT-h,52,h);b.fillStyle='#39c7df33';for(let y=HEIGHT-h+20;y<HEIGHT;y+=24)for(let dx=9;dx<44;dx+=17)b.fillRect(x+dx,y,7,9)}b.strokeStyle=t[2];b.lineWidth=6;for(const x of [48,852]){b.beginPath();b.moveTo(x,230);b.lineTo(x,1010);b.stroke();for(let y=270;y<980;y+=70){b.beginPath();b.moveTo(x-15,y);b.lineTo(x+15,y+50);b.moveTo(x+15,y);b.lineTo(x-15,y+50);b.stroke()}}b.fillStyle='#ffffff22';for(let i=0;i<65;i++)b.fillRect((i*137)%WIDTH,(i*53)%750,2,2);}
function draw(){ctx.setTransform(view.d,0,0,view.d,0,0);ctx.clearRect(0,0,view.w,view.h);ctx.translate(view.x,view.y);ctx.scale(view.scale,view.scale);if(!background)makeBackground();ctx.drawImage(background,0,0);const theme=themes[(g.level-1)%6];
 for(let row=0;row<6;row++){const y1=g.surface(row,55),y2=g.surface(row,845);ctx.beginPath();ctx.moveTo(55,y1);ctx.lineTo(845,y2);ctx.lineTo(845,y2+23);ctx.lineTo(55,y1+23);ctx.closePath();const grad=ctx.createLinearGradient(0,y1,0,y1+30);grad.addColorStop(0,theme[2]);grad.addColorStop(1,'#081124');ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle=theme[3];ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='#ffffff25';ctx.lineWidth=2;for(let x=65;x<840;x+=45){let y=g.surface(row,x);ctx.beginPath();ctx.moveTo(x,y+3);ctx.lineTo(x+29,y+20);ctx.moveTo(x+29,y+3);ctx.lineTo(x,y+20);ctx.stroke()}}
 for(const l of g.ladders){const top=g.surface(l.row+1,l.x),bottom=g.surface(l.row,l.x);ctx.lineWidth=7;ctx.strokeStyle='#edb947';ctx.beginPath();ctx.moveTo(l.x-17,top);ctx.lineTo(l.x-17,bottom);ctx.moveTo(l.x+17,top);ctx.lineTo(l.x+17,bottom);ctx.stroke();ctx.strokeStyle='#ffe5a0';ctx.lineWidth=5;for(let y=top+13;y<bottom;y+=18){ctx.beginPath();ctx.moveTo(l.x-17,y);ctx.lineTo(l.x+17,y);ctx.stroke()}}
 if(boss.complete&&boss.naturalWidth){ctx.save();ctx.translate(85,65+Math.sin(g.elapsed*2)*3);ctx.drawImage(boss,0,0,185,220);ctx.restore()}
 round(303,140,280,51,12,'#061831','#43d6ef66');ctx.fillStyle='#b9eaff';ctx.textAlign='center';ctx.font='900 23px Arial';ctx.fillText('VLADI KONG',443,173);ctx.font='bold 15px Arial';ctx.fillStyle='#a2bbd6';ctx.fillText('SUBÍ HASTA LA ESTRELLA',443,211);
 ctx.save();ctx.shadowColor='#ffce40';ctx.shadowBlur=14;star(805,g.surface(5,805)-45,29);ctx.restore();
 for(const s of g.stars)if(!s.taken)star(s.x,g.surface(s.row,s.x)-48+Math.sin(g.elapsed*3+s.row)*4,15);
 if(!g.hammer.taken){const y=g.surface(2,520)-41;ctx.save();ctx.translate(520,y);ctx.rotate(-.5);round(-4,-2,8,28,3,'#e5a53e');round(-17,-12,34,17,4,'#a6e9ff','#fff');ctx.restore()}
 for(const b of g.barrels){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.spin);const gr=ctx.createRadialGradient(-6,-6,2,0,0,19);gr.addColorStop(0,'#f1b366');gr.addColorStop(1,'#8d431f');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffc36d';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='#3d291b';ctx.lineWidth=3;for(const x of [-8,8]){ctx.beginPath();ctx.moveTo(x,-14);ctx.lineTo(x,14);ctx.stroke()}ctx.strokeStyle='#ffe0a3';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.stroke();ctx.restore()}
 const p=g.player;ctx.save();ctx.translate(p.x,p.y);if(g.invulnerable>0&&Math.floor(g.elapsed*9)%2)ctx.globalAlpha=.5;if(g.power>0){ctx.strokeStyle='#ffdb62';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-30,38,0,7);ctx.stroke()}ctx.scale(p.facing,1);if(runner.complete&&runner.naturalWidth){const fw=runner.naturalWidth/4,frame=(g.keys.left||g.keys.right||p.climbing)?Math.floor(g.elapsed*9)%4:0;ctx.drawImage(runner,frame*fw,0,fw,runner.naturalHeight,-27,-62,54,66)}else{round(-16,-42,32,42,8,'#21bbf2');star(0,-27,8)}ctx.restore();
}
function tone(freq,duration=.1,type='sine',volume=.08){if(muted||!audio)return;const o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.value=freq;v.gain.setValueAtTime(volume,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function saveBest(){if(g.score>best){best=g.score;try{localStorage.setItem('vladi-kong-best',best)}catch(_){}}}
function ui(){document.querySelector('#score').textContent=g.score;document.querySelector('#best').textContent=best;document.querySelector('#lives').textContent='♥ '.repeat(g.lives).trim()||'—';document.querySelector('#stage').textContent='ETAPA '+g.level+' · '+themes[(g.level-1)%6][0];document.querySelector('#time').textContent=Math.ceil(g.remaining)+'s';document.querySelector('#power').textContent=g.power>0?'⚒ '+Math.ceil(g.power)+'s':'';document.querySelector('#pause').textContent=g.state==='paused'?'▶':'Ⅱ';}
function showState(){overlay.hidden=g.state==='playing';if(g.state==='playing')return;const won=g.state==='won',over=g.state==='over',paused=g.state==='paused';document.querySelector('#eyebrow').textContent=won?'¡LLEGASTE A LA CUMBRE!':over?'UNA NUEVA OPORTUNIDAD':paused?'TOMATE UN RESPIRO':'UNA AVENTURA EN LAS ALTURAS';document.querySelector('#title').innerHTML=won?'¡ETAPA <span>SUPERADA!</span>':over?'¡VOLVÉ A <span>INTENTAR!</span>':paused?'EN <span>PAUSA</span>':'VLADI <span>KONG</span>';document.querySelector('#message').textContent=won?'Sumaste '+g.score+' puntos. Te espera otro escenario con barriles más rápidos.':over?'Conseguiste '+g.score+' puntos. Tu récord es '+best+'. ¡Vamos por más!':paused?'Tu partida te espera. Continuá cuando quieras.':'Subí las escaleras, saltá los barriles y alcanzá la estrella. ¡Vladi Kong te espera arriba!';document.querySelector('#start').textContent=won?'SIGUIENTE ETAPA →':over?'VOLVER A JUGAR →':paused?'CONTINUAR →':'JUGAR AHORA →';document.querySelector('#tips').hidden=won||over;document.querySelector('#note').textContent=won?'Recuperás una vida · Hasta 3 vidas':'3 vidas · Guardás tu avance entre plataformas';}
function clearKeys(){g.keys={};document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'))}
function pause(){if(g.state==='playing'){g.state='paused';clearKeys()}else if(g.state==='paused')g.state='playing';showState();ui()}
const keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down'};
addEventListener('keydown',e=>{if(keyMap[e.code]||e.code==='Space'){e.preventDefault();if(g.state!=='playing')return;if(keyMap[e.code])g.keys[keyMap[e.code]]=true;else if(!e.repeat)g.jump()}else if((e.code==='Escape'||e.code==='KeyP')&&!e.repeat)pause()});addEventListener('keyup',e=>{if(keyMap[e.code])g.keys[keyMap[e.code]]=false});addEventListener('blur',()=>{if(g.state==='playing')pause();clearKeys()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.state==='playing')pause()});
for(const button of document.querySelectorAll('[data-key],#jump')){const key=button.dataset.key;button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);if(g.state!=='playing')return;button.classList.add('held');key?g.keys[key]=true:g.jump()});const release=()=>{button.classList.remove('held');if(key)g.keys[key]=false};button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release)}
document.querySelector('#start').onclick=()=>{if(g.state==='won'){g.next();background=null}else if(g.state==='over'){g.restart();background=null}else if(g.state==='paused')g.state='playing';else g.start();clearKeys();showState();ui()};document.querySelector('#pause').onclick=pause;document.querySelector('#sound').onclick=async()=>{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();muted=!muted;document.querySelector('#sound').style.color=muted?'#91a7bb':'#ffdc68';document.querySelector('#sound').setAttribute('aria-label',muted?'Activar sonido':'Silenciar sonido');tone(440,.15)};document.querySelector('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(_){}};
function loop(now){const dt=prev?Math.min((now-prev)/1000,.12):0;prev=now;acc+=dt;while(acc>=1/120){g.update(1/120);acc-=1/120}if(g.event){const event=g.event;g.event='';if(event==='jump')tone(450,.09,'triangle');if(event==='star'||event==='climb')tone(780,.12);if(event==='hit')tone(100,.25,'sawtooth',.06);if(event==='win')tone(1047,.5);if(event==='smash'||event==='power')tone(520,.2);saveBest()}if(g.state!==lastState){lastState=g.state;showState();ui()}hudTime+=dt;if(hudTime>.15){hudTime=0;ui()}if(!muted&&audio&&g.state==='playing'&&now>musicAt){musicAt=now+320;const notes=[196,246.94,293.66,392,293.66,246.94,220,293.66];tone(notes[Math.floor(now/320)%notes.length],.18,'triangle',.025)}draw();requestAnimationFrame(loop)}resize();ui();showState();requestAnimationFrame(loop);
