(()=>{
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),panel=document.querySelector('#panel'),title=document.querySelector('#panelTitle'),panelText=document.querySelector('#panelText'),hint=document.querySelector('#hint'),startBtn=document.querySelector('#start'),pauseBtn=document.querySelector('#pause'),hud=document.querySelector('#hud'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),livesEl=document.querySelector('#lives'),menuBest=document.querySelector('#menuBest');
const MAX_LIVES=15;
let W=innerWidth,H=innerHeight,dpr=1,state='menu',last=0,now=0,elapsed=0,score=0,best=+(localStorage.getItem('vladiFruitNinjaBest')||0),lives=MAX_LIVES,objects=[],particles=[],trail=[],missedWaves=new Set(),nextWave=.85,wave=0,lastCutAt=-1e6,combo=0,activePointer=null,lastPoint=null,flash=0,shake=0,toast='',toastUntil=0;
const colors={apple:'#f3423a',orange:'#ff942d',watermelon:'#ef4660',strawberry:'#ed3851',kiwi:'#7bbd3f',lemon:'#ffd447',pear:'#85c94b',pineapple:'#ffb82e'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
function renderLives(){livesEl.textContent=`♥ ${lives}`}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
function radius(){return clamp(Math.min(W,H)*.078,26,48)}
function drawLeaf(x,y,len,angle,color,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(len*.44,-len*.38,len,0);ctx.quadraticCurveTo(len*.5,len*.36,0,0);ctx.fill();ctx.strokeStyle='#d7ffd077';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(len*.45,0,len*.9,0);ctx.stroke();ctx.restore()}
function drawBamboo(x,y,h,side){ctx.save();const w=Math.max(8,Math.min(24,W*.026));const g=ctx.createLinearGradient(x-w,0,x+w,0);g.addColorStop(0,'#12533d');g.addColorStop(.35,'#38865b');g.addColorStop(.72,'#236b4c');g.addColorStop(1,'#0d493d');ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(x-w/2,y-h,w,h,8);ctx.fill();ctx.strokeStyle='#82bd69';ctx.lineWidth=Math.max(2,w*.12);for(let yy=y-h+30;yy<y;yy+=Math.max(46,h*.18)){ctx.beginPath();ctx.moveTo(x-w*.56,yy);ctx.lineTo(x+w*.56,yy);ctx.stroke()}for(let i=0;i<5;i++)drawLeaf(x,y-h+12,Math.min(W*.22,100)*(1+i%2*.2),side*(.35+i*.42)+(i%2?-.3:.22),i%2?'#49a957':'#23794e',.9);ctx.restore()}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#65d9e7');g.addColorStop(.45,'#28a6c1');g.addColorStop(1,'#075477');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const glow=ctx.createRadialGradient(W*.52,H*.34,8,W*.52,H*.34,Math.max(W,H)*.75);glow.addColorStop(0,'#e4ffc733');glow.addColorStop(1,'#073f6711');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);
// Soft, layered island silhouettes keep the cutting area legible.
for(let layer=0;layer<3;layer++){const y=H*(.23+layer*.11),rise=H*(.12-layer*.012);ctx.fillStyle=['#1c846b55','#126c6055','#0b5e5655'][layer];ctx.beginPath();ctx.moveTo(0,y+rise*.4);for(let x=0;x<=W+20;x+=W/6){const bump=Math.sin(x/W*Math.PI*2+layer*1.7)*rise*.35;ctx.lineTo(x,y+bump)}ctx.lineTo(W,H*.57+layer*30);ctx.lineTo(0,H*.59+layer*30);ctx.closePath();ctx.fill()}
// Gentle water glints.
ctx.strokeStyle='#c5ffff35';ctx.lineWidth=2;for(let i=0;i<15;i++){const yy=H*.54+i*H*.032,x=(i*137+Math.sin(now*.001+i)*25)%Math.max(W,1);ctx.beginPath();ctx.moveTo(x,yy);ctx.quadraticCurveTo(x+W*.035,yy-4,x+W*.07,yy);ctx.stroke()}
const stemY=H*.73;drawBamboo(W*.025,stemY,H*.53,1);drawBamboo(W*.975,stemY,H*.47,-1);
// Low dark foreground vignette frames fruit without covering it.
const v=ctx.createLinearGradient(0,H*.74,0,H);v.addColorStop(0,'#04283a00');v.addColorStop(1,'#032b43aa');ctx.fillStyle=v;ctx.fillRect(0,H*.72,W,H*.28)}
function fruitPath(kind,r){ctx.beginPath();if(kind==='strawberry'){ctx.moveTo(0,r*.9);ctx.bezierCurveTo(-r*.28,r*.58,-r*.92,r*.05,-r*.67,-r*.47);ctx.bezierCurveTo(-r*.48,-r*.84,-r*.12,-r*.8,0,-r*.53);ctx.bezierCurveTo(r*.22,-r*.86,r*.67,-r*.77,r*.74,-r*.37);ctx.bezierCurveTo(r*.84,r*.02,r*.3,r*.59,0,r*.9)}else if(kind==='pear'){ctx.moveTo(0,-r*.9);ctx.bezierCurveTo(r*.12,-r*.43,r*.75,-r*.21,r*.77,r*.36);ctx.bezierCurveTo(r*.8,r*.82,r*.36,r,0,r*.94);ctx.bezierCurveTo(-r*.51,r*.98,-r*.84,r*.62,-r*.74,r*.19);ctx.bezierCurveTo(-r*.64,-r*.28,-r*.12,-r*.49,0,-r*.9)}else if(kind==='lemon'){ctx.moveTo(-r*.95,0);ctx.quadraticCurveTo(-r*.48,-r*.75,0,-r*.7);ctx.quadraticCurveTo(r*.57,-r*.62,r*.96,0);ctx.quadraticCurveTo(r*.45,r*.67,0,r*.72);ctx.quadraticCurveTo(-r*.52,r*.72,-r*.95,0)}else{ctx.ellipse(0,0,r*(kind==='watermelon'?.94:.82),r*(kind==='apple'?.88:.92),0,0,Math.PI*2)}ctx.closePath()}
function drawFruit(o){const r=o.r,kind=o.fruitKind||'apple',base=colors[kind]||colors.apple;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot||0);ctx.shadowColor='#062c3988';ctx.shadowBlur=r*.25;ctx.shadowOffsetY=r*.16;
if(kind==='watermelon'){const wg=ctx.createLinearGradient(-r,0,r,0);wg.addColorStop(0,'#168f57');wg.addColorStop(.55,'#44c36d');wg.addColorStop(1,'#147b50');ctx.fillStyle=wg;fruitPath(kind,r);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#d7f27d';ctx.lineWidth=Math.max(2,r*.08);for(let x=-r*.55;x<=r*.56;x+=r*.38){ctx.beginPath();ctx.moveTo(x,-r*.74);ctx.quadraticCurveTo(x-r*.23,0,x,r*.75);ctx.stroke()}}
else{const grad=ctx.createRadialGradient(-r*.38,-r*.46,r*.06,r*.06,r*.1,r*1.3);grad.addColorStop(0,'#ffffff');grad.addColorStop(.14,base);grad.addColorStop(1,shade(base,-.38));ctx.fillStyle=grad;fruitPath(kind,r);ctx.fill();ctx.shadowBlur=0;
if(kind==='strawberry'){ctx.fillStyle='#ffdb72';for(let i=0;i<10;i++){const a=i*2.4+.4,rr=r*(.2+(i%3)*.17);ctx.beginPath();ctx.ellipse(Math.cos(a)*rr,Math.sin(a)*rr,Math.max(1,r*.035),r*.07,a,0,Math.PI*2);ctx.fill()}}
if(kind==='orange'||kind==='lemon'){ctx.fillStyle='#fff2c8aa';ctx.beginPath();ctx.ellipse(-r*.23,-r*.22,r*.12,r*.09,-.6,0,Math.PI*2);ctx.fill()}
if(kind==='kiwi'){ctx.fillStyle='#fff0c8';ctx.beginPath();ctx.ellipse(0,0,r*.24,r*.24,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2f5125';for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.arc(Math.cos(a)*r*.4,Math.sin(a)*r*.4,r*.035,0,Math.PI*2);ctx.fill()}}
if(kind==='apple'){ctx.fillStyle='#72391c';ctx.beginPath();ctx.roundRect(-r*.05,-r*.95,r*.1,r*.28,3);ctx.fill();drawLeaf(r*.02,-r*.78,r*.42,-.5,'#69c444')}
if(kind==='pear'||kind==='orange'||kind==='lemon'){drawLeaf(r*.03,-r*.72,r*.34,-.7,'#70c849')}}
ctx.restore()}
function shade(hex,amt){const n=parseInt(hex.slice(1),16),r=clamp((n>>16)+amt*255,0,255),g=clamp(((n>>8)&255)+amt*255,0,255),b=clamp((n&255)+amt*255,0,255);return`rgb(${r|0},${g|0},${b|0})`}
function drawBomb(o){const r=o.r;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot);ctx.shadowColor='#09121e99';ctx.shadowBlur=r*.25;ctx.shadowOffsetY=r*.16;const g=ctx.createRadialGradient(-r*.35,-r*.4,r*.04,0,0,r*1.2);g.addColorStop(0,'#9da7b4');g.addColorStop(.3,'#414b5b');g.addColorStop(1,'#101b2a');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r*.78,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#111927';ctx.lineWidth=r*.12;for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(a)*r*.58,Math.sin(a)*r*.58);ctx.lineTo(Math.cos(a)*r*.94,Math.sin(a)*r*.94);ctx.stroke()}ctx.strokeStyle='#ffd887';ctx.lineWidth=r*.1;ctx.beginPath();ctx.moveTo(r*.25,-r*.64);ctx.quadraticCurveTo(r*.5,-r*1.15,r*.13,-r*1.2);ctx.stroke();ctx.fillStyle='#fff29d';ctx.beginPath();ctx.arc(r*.12,-r*1.2,r*.12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffdf83';ctx.font=`1000 ${r*.75}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('!',0,1);ctx.restore()}
function spawnWave(){wave++;const r=radius(),count=3+Math.min(2,Math.floor(elapsed/22)),span=Math.min(W*.66,520),start=W/2-span/2;const hasBomb=elapsed>14&&Math.random()<Math.min(.24,.07+elapsed*.003);const bombIndex=hasBomb?Math.floor(Math.random()*count):-1;for(let i=0;i<count;i++){const bomb=i===bombIndex;objects.push({id:wave+'-'+i,waveId:wave,kind:bomb?'bomb':'fruit',fruitKind:Object.keys(colors)[Math.floor(Math.random()*Object.keys(colors).length)],x:count===1?W/2:start+(i/(count-1))*span+rand(-r*.22,r*.22),y:H+r*1.3,vx:rand(-W*.08,W*.08),vy:-(H*1.52+rand(0,H*.18)),r:r*rand(.88,1.08),rot:rand(-.45,.45),vr:rand(-2,2),cut:false,age:0,slot:i})}}
function puff(x,y,color,bomb=false){for(let i=0;i<(bomb?24:15);i++){const a=rand(0,Math.PI*2),speed=rand(80,390)*(Math.min(W,H)/700);particles.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed-rand(0,90),r:rand(2,7)*(Math.min(W,H)/700),color:bomb?(i%2?'#ff8c38':'#fff0a0'):color,life:rand(.35,.8),age:0})}}
function swipeSlash(o){if(o.kind==='bomb'){window.VladiSound?.play('hit');o.cut=true;o.age=.49;o.halves=[];lives--;renderLives();combo=0;flash=.16;shake=.24;puff(o.x,o.y,'#ff663d',true);toast='¡BOMBA!';toastUntil=now+800;if(lives<=0)endGame('¡La bomba explotó!');return}
window.VladiSound?.play('slice');o.cut=true;o.age=0;o.halves=[{vx:o.vx-100,vy:o.vy*.25-120,side:-1},{vx:o.vx+100,vy:o.vy*.25-120,side:1}];puff(o.x,o.y,colors[o.fruitKind]||'#ff6a55');if(now-lastCutAt<500)combo++;else combo=1;lastCutAt=now;const award=10+(combo>1?(combo-1)*5:0);score+=award;scoreEl.textContent=score;if(score>best){best=score;bestEl.textContent=best;menuBest.textContent=best;localStorage.setItem('vladiFruitNinjaBest',String(best))}if(combo>=2){toast=`COMBO ×${combo}  +${award}`;toastUntil=now+650}}
function point(e){const rect=canvas.getBoundingClientRect();return{x:(e.clientX-rect.left)*(W/rect.width),y:(e.clientY-rect.top)*(H/rect.height)}}
function segmentDistance(px,py,a,b){const dx=b.x-a.x,dy=b.y-a.y,len=dx*dx+dy*dy;if(!len)return Math.hypot(px-a.x,py-a.y);const t=clamp(((px-a.x)*dx+(py-a.y)*dy)/len,0,1);return Math.hypot(px-(a.x+t*dx),py-(a.y+t*dy))}
function sliceSegment(a,b){if(!a||!b||Math.hypot(b.x-a.x,b.y-a.y)<3)return;for(const o of objects){if(state!=='playing')break;if(o.cut)continue;if(segmentDistance(o.x,o.y,a,b)<o.r*.78)swipeSlash(o)}trail.push({x:b.x,y:b.y,t:now});if(trail.length>16)trail.splice(0,trail.length-16)}
function drawBlade(){if(trail.length<2)return;ctx.save();for(let i=1;i<trail.length;i++){const p=trail[i-1],q=trail[i],age=now-q.t,a=clamp(1-age/.19,0,1);if(a<=0)continue;ctx.globalAlpha=a;ctx.strokeStyle=i%2?'#f4ffff':'#fff2a3';ctx.shadowColor='#9fffff';ctx.shadowBlur=22*a;ctx.lineWidth=Math.max(1,12*(i/trail.length)*a);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}ctx.restore()}
function drawParticles(){for(const p of particles){const a=1-p.age/p.life;ctx.globalAlpha=a;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=10*a;ctx.beginPath();ctx.arc(p.x,p.y,p.r*a,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.shadowBlur=0}
function drawSliced(o){const age=o.age,t=age/.48,fade=1-t;for(const h of o.halves){const x=o.x+h.side*(o.r*.26+age*90)+h.vx*age*.18,y=o.y+age*h.vy+Math.max(0,age*age*H*.5);ctx.save();ctx.globalAlpha=fade;ctx.translate(x,y);ctx.rotate(o.rot+h.side*age*2);ctx.beginPath();if(h.side<0){ctx.moveTo(0,-o.r);ctx.arc(0,0,o.r,-Math.PI/2,Math.PI/2);ctx.closePath()}else{ctx.moveTo(0,-o.r);ctx.arc(0,0,o.r,-Math.PI/2,-Math.PI*1.5,true);ctx.closePath()}ctx.clip();drawFruit({...o,x:0,y:0,rot:0});ctx.shadowBlur=0;ctx.fillStyle='#fff0c8';ctx.beginPath();ctx.ellipse(h.side*o.r*.23,0,o.r*.2,o.r*.43,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8c5128';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(h.side*o.r*.25,(-.25+i*.25)*o.r,o.r*.03,o.r*.07,.3,0,Math.PI*2);ctx.fill()}ctx.restore()}}
function draw(){drawBackground();ctx.save();if(shake>0)ctx.translate(rand(-5,5)*shake,rand(-4,4)*shake);for(const o of objects){if(o.cut)drawSliced(o);else if(o.kind==='bomb')drawBomb(o);else drawFruit(o)}drawParticles();ctx.restore();drawBlade();if(flash>0){ctx.fillStyle=`rgba(255,90,49,${flash*.55})`;ctx.fillRect(0,0,W,H)}if(toast&&now<toastUntil){ctx.save();ctx.textAlign='center';ctx.font=`1000 ${clamp(W*.055,22,36)}px system-ui`;ctx.lineWidth=5;ctx.strokeStyle='#143a43aa';ctx.strokeText(toast,W/2,H*.24);ctx.fillStyle='#fff4aa';ctx.shadowColor='#24424a';ctx.shadowBlur=15;ctx.fillText(toast,W/2,H*.24);ctx.restore()}}
function endGame(reason){if(state!=='playing')return;window.VladiSound?.play('gameover');state='over';objects=[];particles=[];trail=[];title.textContent='¡FIN DE LA RONDA!';panelText.textContent=`${reason} Cortaste ${score} puntos.`;hint.textContent='Deslizá rápido por varias frutas para encadenar combos.';startBtn.textContent='↻ JUGAR OTRA VEZ';panel.classList.remove('hidden');pauseBtn.classList.add('hidden');menuBest.textContent=best}
function start(){window.VladiSound?.play('start');score=0;lives=MAX_LIVES;elapsed=0;objects=[];particles=[];trail=[];missedWaves.clear();wave=0;combo=0;lastCutAt=-1e6;nextWave=.85;flash=0;shake=0;toast='';scoreEl.textContent='0';bestEl.textContent=best;renderLives();state='playing';panel.classList.add('hidden');hud.classList.remove('hidden');pauseBtn.classList.remove('hidden');startBtn.textContent='▶ JUGAR'}
function pause(){if(state==='playing'){window.VladiSound?.play('pause');state='paused';title.textContent='PAUSA';panelText.textContent=`Puntaje actual: ${score}. Tocá continuar para seguir.`;hint.textContent='';startBtn.textContent='▶ CONTINUAR';panel.classList.remove('hidden')}else if(state==='paused'){window.VladiSound?.play('resume');state='playing';panel.classList.add('hidden');startBtn.textContent='▶ JUGAR'}}
startBtn.addEventListener('click',()=>state==='paused'?pause():start());pauseBtn.addEventListener('click',pause);
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;e.preventDefault();activePointer=e.pointerId;lastPoint=point(e);trail.push({x:lastPoint.x,y:lastPoint.y,t:now});try{canvas.setPointerCapture(e.pointerId)}catch{}},{passive:false});
canvas.addEventListener('pointermove',e=>{if(state!=='playing'||activePointer!==e.pointerId)return;e.preventDefault();const p=point(e);sliceSegment(lastPoint,p);lastPoint=p},{passive:false});
function release(e){if(activePointer!==e.pointerId)return;activePointer=null;lastPoint=null}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
addEventListener('keydown',e=>{if(e.code==='Escape'||e.code==='KeyP'){e.preventDefault();pause()}},{passive:false});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
function update(dt){now+=dt*1000;if(state==='playing'){elapsed+=dt;nextWave-=dt;if(nextWave<=0){spawnWave();nextWave=Math.max(.88,1.48-elapsed*.004)}for(const o of objects){o.rot+=o.vr*dt;if(o.cut){o.age+=dt;for(const h of o.halves){h.vy+=H*1.1*dt;h.vx+=o.vx*.08*dt}continue}o.x+=o.vx*dt;o.y+=o.vy*dt;o.vy+=H*2.35*dt;if(o.y-o.r>H+10){if(o.kind==='fruit'&&!missedWaves.has(o.waveId??o.id)){const group=o.waveId??o.id;missedWaves.add(group);lives--;renderLives();toast='¡SE ESCAPÓ UNA FRUTA!';toastUntil=now+700;if(lives<=0)endGame('Se te escaparon demasiadas frutas.')}o.cut=true;o.age=.49}}
objects=objects.filter(o=>!o.cut||o.age<.48);for(const p of particles){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=H*.75*dt;p.vx*=.985}particles=particles.filter(p=>p.age<p.life);trail=trail.filter(p=>now-p.t<190);flash=Math.max(0,flash-dt);shake=Math.max(0,shake-dt*2.8)}else{elapsed+=dt*.2;trail=trail.filter(p=>now-p.t<190);for(const p of particles){p.age+=dt}particles=particles.filter(p=>p.age<p.life)}}
function frame(t){const dt=Math.min(.04,Math.max(0,(t-last)/1000));last=t;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.__vladiFruitNinja={get state(){return state},get metrics(){return{score,best,lives,wave,objects:objects.length,elapsed}},start,pause,spawnTestObject:(x,y,kind='fruit',waveId)=>{const group=waveId||'test-'+elapsed+'-'+objects.length;objects.push({id:group,waveId:group,kind:kind==='bomb'?'bomb':'fruit',fruitKind:'orange',x,y,vx:0,vy:0,r:radius(),rot:0,vr:0,cut:false,age:0})},pointerDown:(x,y,id=1)=>{activePointer=id;lastPoint={x,y}},pointerMove:(x,y,id=1)=>{const p={x,y};if(activePointer===id)sliceSegment(lastPoint,p);lastPoint=p},pointerUp:(id=1)=>release({pointerId:id}),resize:()=>resize(),getLayout:()=>({width:W,height:H,dpr})};
})();
