(()=>{'use strict';
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id), els={round:$('round'),score:$('score'),time:$('time'),timerStat:$('timerStat'),saved:$('saved'),best:$('best'),hearts:$('hearts'),status:$('status'),menu:$('menu'),pause:$('pause'),over:$('gameover'),toast:$('toast')};
const STORE='vladiRescateBestV1';let best=Number(localStorage.getItem(STORE)||0),round=1,total=0,rescues=0,lives=3,timeLeft=90,timeLimit=90,lastClockShown=-1,maze=null,animals=[],exit=null,player={x:1,y:1,fromX:1,fromY:1,t:1},bugs=[],steps=0,state='menu',moveBusy=false,moveQueue=null,lastMove=0,invulnerableUntil=0,particles=[],animFrame=0,sound=true,audio=null,toastTimer=0;
let W=innerWidth,H=innerHeight,DPR=1,cell=32,ox=0,oy=0,cols=11,rows=11;
const sprite=new Image();sprite.src='../vladi-run/assets/vladi-runner.webp';
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function resize(){const oldCols=cols,oldRows=rows;W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);layoutMaze();if(maze&&(cols!==oldCols||rows!==oldRows))makeMaze()}
function layoutMaze(){const base=round<2?11:round<4?13:round<7?15:17;if(H<520&&W>H){cols=Math.min(17,base+4);rows=9}else cols=rows=base;const top=H<520?92:Math.max(128,H*.16),bottom=H<520?83:Math.max(142,H*.18);const usable=Math.max(150,H-top-bottom);cell=clamp(Math.floor(Math.min((W-26)/cols,usable/rows)),14,58);ox=(W-cols*cell)/2;oy=top+(usable-rows*cell)/2}
function makeMaze(){layoutMaze();timeLimit=Math.max(45,90-(round-1)*6);timeLeft=timeLimit;lastClockShown=-1;maze=Array.from({length:rows},()=>Array(cols).fill(1));const start={x:1,y:rows-2};maze[start.y][start.x]=0;const stack=[start],dirs=[[0,-2],[2,0],[0,2],[-2,0]];while(stack.length){const c=stack[stack.length-1],opts=[];for(const [dx,dy] of dirs){const nx=c.x+dx,ny=c.y+dy;if(nx>0&&ny>0&&nx<cols-1&&ny<rows-1&&maze[ny][nx]===1)opts.push([dx,dy])}if(!opts.length){stack.pop();continue}const [dx,dy]=opts[rnd(0,opts.length-1)];maze[c.y+dy/2][c.x+dx/2]=0;maze[c.y+dy][c.x+dx]=0;stack.push({x:c.x+dx,y:c.y+dy})}
 player={x:start.x,y:start.y,fromX:start.x,fromY:start.y,t:1};const dist=bfs(start),reachable=Object.keys(dist).map(k=>{const [y,x]=k.split(',').map(Number);return{x,y,d:dist[k]}}).filter(p=>p.d>5).sort((a,b)=>b.d-a.d);exit=reachable[Math.min(reachable.length-1,Math.floor(reachable.length*.08))]||reachable[reachable.length-1];maze[exit.y][exit.x]=2;const count=Math.min(5,3+Math.floor((round-1)/2));const candidates=reachable.filter(p=>!(p.x===exit.x&&p.y===exit.y)&&p.d>3).sort((a,b)=>a.d-b.d);animals=[];for(let i=0;i<count;i++){const target=(i+1)/(count+1),idx=clamp(Math.floor(candidates.length*target+rnd(-2,2)),0,candidates.length-1);const pos=candidates.splice(idx,1)[0];if(pos)animals.push({...pos,icon:['🐒','🐢','🦜','🐰','🦊'][i%5],rescued:false,bob:Math.random()*6})}bugs=[];if(round>=3){const n=Math.min(3,1+Math.floor((round-3)/3));const safe=candidates.filter(p=>p.d>5&&Math.abs(p.x-start.x)+Math.abs(p.y-start.y)>4);for(let i=0;i<n&&safe.length;i++){const p=safe.splice(rnd(0,safe.length-1),1)[0];bugs.push({...p,fromX:p.x,fromY:p.y,t:1,delay:0})}}steps=0;moveBusy=false;moveQueue=null;updateHud();
}
function bfs(start){const q=[start],d={[`${start.y},${start.x}`]:0};for(let i=0;i<q.length;i++){const p=q[i];for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,y=p.y+dy,k=`${y},${x}`;if(y>=0&&y<rows&&x>=0&&x<cols&&maze[y][x]!==1&&d[k]===undefined){d[k]=d[`${p.y},${p.x}`]+1;q.push({x,y})}}}return d}
function updateHud(){const rescued=animals.filter(a=>a.rescued).length;els.round.textContent=round;els.score.textContent=total;const secs=Math.max(0,Math.ceil(timeLeft));els.time.textContent=`${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')}`;els.timerStat.classList.toggle('urgent',secs<=15);lastClockShown=secs;els.saved.textContent=`${rescued}/${animals.length||Math.min(5,3+Math.floor((round-1)/2))}`;els.best.textContent=best;els.hearts.textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);$('menuBest').textContent=best;$('overBest').textContent=best;els.status.textContent=rescued===animals.length&&animals.length?'¡Todos rescatados! ¡Encontrá el portal!':'Rescatá a los animales y encontrá la salida'}
function drawBg(t){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#137fc1');g.addColorStop(.42,'#58d3e1');g.addColorStop(.72,'#77c657');g.addColorStop(1,'#1e573c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.18;for(let i=0;i<9;i++){let x=(i*173+40)%W,y=H*.17+(i%3)*H*.09;ctx.fillStyle=i%2?'#fff3c1':'#1f8248';ctx.beginPath();ctx.ellipse(x,y,70+i%4*15,20,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(let i=0;i<15;i++){const x=(i*97+27)%W,y=(i*67+Math.sin(t*.0005+i)*18+H*.11)%Math.max(H*.85,1);if(y<oy-10||y>oy+rows*cell+12){drawPlant(x,y,.45+(i%4)*.12,t+i)}}}
function drawPlant(x,y,s,t){ctx.save();ctx.translate(x,y);ctx.fillStyle='#174b32';ctx.beginPath();ctx.ellipse(0,4*s,18*s,5*s,0,0,Math.PI*2);ctx.fill();for(let i=0;i<5;i++){const a=-Math.PI*.9+i*Math.PI*.24+Math.sin(t*.001+i)*.04;ctx.strokeStyle=i%2?'#2c9b4e':'#52bd4b';ctx.lineWidth=4*s;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(Math.cos(a)*9*s,-14*s,Math.cos(a)*21*s,-28*s);ctx.stroke();ctx.fillStyle=i%2?'#41a949':'#70cd4d';ctx.beginPath();ctx.ellipse(Math.cos(a)*21*s,-28*s,8*s,3*s,a,0,Math.PI*2);ctx.fill()}ctx.restore()}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawWorld(t){ctx.clearRect(0,0,W,H);drawBg(t);if(!maze)return;const mw=cols*cell,mh=rows*cell;ctx.save();ctx.shadowColor='#09281766';ctx.shadowBlur=20;ctx.fillStyle='#123d2c';rr(ox-8,oy-7,mw+16,mh+18,18);ctx.fill();ctx.restore();for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=ox+x*cell,py=oy+y*cell;drawTile(x,y,px,py,t)}drawExit(t);for(const a of animals)if(!a.rescued)drawAnimal(a,t);for(const b of bugs)drawBug(b,t);drawPlayer(t);drawParticles(t);drawDecor(t)}
function drawTile(x,y,px,py,t){const v=maze[y][x];if(v===1){ctx.fillStyle='#70482a';rr(px+1,py+3,cell-2,cell-1,5);ctx.fill();ctx.fillStyle='#2c703f';rr(px+1,py+1,cell-2,cell-5,6);ctx.fill();ctx.fillStyle='#49a84e';rr(px+2,py+1,cell-4,cell*.67,5);ctx.fill();ctx.fillStyle='#76ce54';ctx.beginPath();ctx.ellipse(px+cell*.33,py+cell*.24,cell*.22,cell*.09,-.25,0,Math.PI*2);ctx.fill();ctx.fillStyle='#318044';for(let k=0;k<3;k++){const sx=px+((x*19+y*13+k*17)%Math.max(cell-7,1))+3,sy=py+((y*13+x*7+k*11)%Math.max(cell*.45,1))+cell*.24;ctx.beginPath();ctx.arc(sx,sy,Math.max(1,cell*.035),0,Math.PI*2);ctx.fill()}return}
 const floor=((x+y)%2)?'#9bdb67':'#8bd35b';ctx.fillStyle=floor;ctx.fillRect(px,py,cell,cell);ctx.strokeStyle='#b6e88155';ctx.lineWidth=1;ctx.strokeRect(px+.5,py+.5,cell-1,cell-1);ctx.fillStyle='#ffffff24';ctx.beginPath();ctx.ellipse(px+cell*.28,py+cell*.3,cell*.07,cell*.025,-.5,0,Math.PI*2);ctx.fill();if((x*7+y*11)%19===0){ctx.fillStyle='#398941';ctx.beginPath();ctx.arc(px+cell*.77,py+cell*.77,cell*.045,0,Math.PI*2);ctx.fill()}}
function drawExit(t){if(!exit)return;const x=ox+(exit.x+.5)*cell,y=oy+(exit.y+.5)*cell,pulse=1+Math.sin(t*.005)*.06;ctx.save();ctx.translate(x,y);ctx.scale(pulse,pulse);ctx.font=`1000 ${Math.max(8,cell*.19)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=2;ctx.strokeStyle='#5a391e';ctx.fillStyle='#fff1a6';ctx.strokeText('SALIDA',0,-cell*.43);ctx.fillText('SALIDA',0,-cell*.43);ctx.fillStyle='#173c2b8c';ctx.beginPath();ctx.ellipse(0,cell*.27,cell*.43,cell*.14,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#6b431d';ctx.lineWidth=Math.max(3,cell*.12);ctx.beginPath();ctx.arc(0,cell*.04,cell*.34,Math.PI,Math.PI*2);ctx.stroke();ctx.strokeStyle='#ffe477';ctx.lineWidth=Math.max(2,cell*.08);ctx.beginPath();ctx.arc(0,cell*.04,cell*.33,Math.PI,Math.PI*2);ctx.stroke();ctx.fillStyle=animals.some(a=>!a.rescued)?'#b86c31':'#4df08e';rr(-cell*.29,-cell*.03,cell*.58,cell*.38,cell*.12);ctx.fill();ctx.fillStyle='#fff1aa';ctx.fillRect(-cell*.19,cell*.02,cell*.38,cell*.29);ctx.fillStyle='#8c542c';ctx.beginPath();ctx.arc(cell*.14,cell*.15,cell*.035,0,Math.PI*2);ctx.fill();if(animals.some(a=>!a.rescued)){ctx.font=`${cell*.34}px system-ui`;ctx.textAlign='center';ctx.fillText('🔒',0,cell*.12)}else{ctx.shadowColor='#ffe060';ctx.shadowBlur=16;ctx.font=`${cell*.43}px system-ui`;ctx.fillText('✨',0,cell*.19)}ctx.restore()}
function drawAnimal(a,t){const x=ox+(a.x+.5)*cell,y=oy+(a.y+.5)*cell+Math.sin(t*.004+a.bob)*cell*.07;ctx.save();ctx.fillStyle='#fff2a7';ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(x,y,cell*.42+Math.sin(t*.005+a.bob)*2,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.shadowColor='#ffdc5b';ctx.shadowBlur=cell*.34;ctx.font=`${cell*.64}px system-ui,Apple Color Emoji,Segoe UI Emoji`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(a.icon,x,y);ctx.restore()}
function drawBug(b,t){const x=ox+(b.fromX+(b.x-b.fromX)*b.t+.5)*cell,y=oy+(b.fromY+(b.y-b.fromY)*b.t+.52)*cell;ctx.save();ctx.fillStyle='#16452c77';ctx.beginPath();ctx.ellipse(x,y+cell*.18,cell*.32,cell*.1,0,0,Math.PI*2);ctx.fill();ctx.font=`${cell*.55}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('🪲',x,y+Math.sin(t*.01)*2);ctx.restore()}
function drawPlayer(t){const px=ox+(player.fromX+(player.x-player.fromX)*player.t+.5)*cell,py=oy+(player.fromY+(player.y-player.fromY)*player.t+.53)*cell;ctx.save();ctx.fillStyle='#16452c88';ctx.beginPath();ctx.ellipse(px,py+cell*.39,cell*.4,cell*.13,0,0,Math.PI*2);ctx.fill();const frame=Math.floor(t/105)%4;if(sprite.complete&&sprite.naturalWidth){const sw=sprite.naturalWidth/4,sh=sprite.naturalHeight,h=cell*1.45,w=h*(sw/sh);ctx.drawImage(sprite,frame*sw,0,sw,sh,px-w/2,py-h*.84,w,h)}else{ctx.font=`${cell*.9}px system-ui`;ctx.textAlign='center';ctx.fillText('🏃🏻',px,py)}ctx.restore()}
function drawParticles(t){particles=particles.filter(p=>t-p.t<680);for(const p of particles){const k=(t-p.t)/680;ctx.globalAlpha=1-k;ctx.font=`${cell*.25}px system-ui`;ctx.textAlign='center';ctx.fillText(p.icon,p.x+(p.dx||0)*k,p.y-(18+k*25));ctx.globalAlpha=1}}
function drawDecor(t){for(let i=0;i<10;i++){const x=(i*139+Math.sin(t*.0006+i)*22+W)%W,y=H*.39+(i*73%Math.max(50,H*.4));if(x<ox-7||x>ox+cols*cell+7||y<oy-7||y>oy+rows*cell+7){ctx.globalAlpha=.55;ctx.fillStyle=i%2?'#fff1ad':'#d9fff1';ctx.beginPath();ctx.arc(x,y,1.5+(i%3),0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}}
let previousFrame=performance.now();function frame(t){animFrame=t;const dt=Math.min(Math.max((t-previousFrame)/1000,0),.08);previousFrame=t;if(state==='playing'){timeLeft=Math.max(0,timeLeft-dt);const sec=Math.ceil(timeLeft);if(sec!==lastClockShown)updateHud();if(timeLeft<=0){endGame('time')}if(player.t<1){player.t=Math.min(1,player.t+dt*1000/105);if(player.t>=1){moveBusy=false;if(moveQueue){const q=moveQueue;moveQueue=null;move(q[0],q[1])}}}for(const b of bugs)if(b.t<1)b.t=Math.min(1,b.t+dt*4.8)}drawWorld(t);requestAnimationFrame(frame)}
function audioTone(freq,dur,type='sine',vol=.06){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
function blip(kind){if(kind==='collect'){audioTone(720,.12,'sine',.09);setTimeout(()=>audioTone(980,.15,'sine',.055),55)}else if(kind==='rescue'){audioTone(523,.14);setTimeout(()=>audioTone(659,.14),90);setTimeout(()=>audioTone(784,.22),180)}else if(kind==='hit'){audioTone(145,.22,'triangle',.08)}else if(kind==='win'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>audioTone(f,.16),i*80))}else audioTone(330,.055,'sine',.035)}
function popup(msg){els.toast.textContent=msg;els.toast.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove('on'),1000)}
function move(dx,dy){if(state!=='playing')return;if(moveBusy){moveQueue=[dx,dy];return}const nx=player.x+dx,ny=player.y+dy;if(nx<0||nx>=cols||ny<0||ny>=rows||maze[ny][nx]===1){blip('bump');return}player.fromX=player.x;player.fromY=player.y;player.x=nx;player.y=ny;player.t=0;moveBusy=true;lastMove=performance.now();steps++;blip('step');const a=animals.find(v=>!v.rescued&&v.x===nx&&v.y===ny);if(a){a.rescued=true;rescues++;total+=100;particles.push({x:ox+(nx+.5)*cell,y:oy+(ny+.5)*cell,t:performance.now(),icon:'💛'});blip('rescue');popup('¡Animal rescatado! 🐾');if(total>best){best=total;localStorage.setItem(STORE,String(best))}updateHud()}
 if(bugs.some(b=>b.x===nx&&b.y===ny))hurtPlayer();if(state==='over')return;
 if(maze[ny][nx]===2){if(animals.some(v=>!v.rescued)){popup('¡Faltan animalitos! 🐾')}else{state='transition';player.t=1;moveBusy=false;moveQueue=null;blip('win');total+=250;if(total>best){best=total;localStorage.setItem(STORE,String(best))}round++;popup('¡Ronda superada! +2 ⭐');updateHud();setTimeout(()=>{if(state==='transition'){state='playing';makeMaze();popup('¡Aventura '+round+'!')}} ,700);return}}
 if(steps%2===0)moveBugs();if(lives<=0)endGame();updateHud()}
function moveBugs(){for(const b of bugs){const opts=[];for(const [dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const x=b.x+dx,y=b.y+dy;if(x>0&&y>0&&x<cols-1&&y<rows-1&&maze[y][x]!==1)opts.push({x,y})}if(!opts.length)continue;const next=opts[rnd(0,opts.length-1)];b.fromX=b.x;b.fromY=b.y;b.x=next.x;b.y=next.y;b.t=0;if(b.x===player.x&&b.y===player.y)hurtPlayer()}}
function hurtPlayer(){if(performance.now()<invulnerableUntil)return;lives--;invulnerableUntil=performance.now()+1500;blip('hit');popup('¡Cuidado con el guardián!');player.x=1;player.y=rows-2;player.fromX=player.x;player.fromY=player.y;player.t=1;if(lives<=0)endGame();updateHud()}
function start(){round=1;total=0;rescues=0;lives=3;state='playing';els.menu.classList.add('hidden');els.pause.classList.add('hidden');els.over.classList.add('hidden');makeMaze();updateHud()}
function endGame(reason=''){state='over';$('finalSaved').textContent=rescues;$('finalScore').textContent=total;$('finalRound').textContent=round;$('overTitle').textContent=reason==='time'?'¡SE ACABÓ EL TIEMPO!':'¡AVENTURA TERMINADA!';$('overBest').textContent=best;els.over.classList.remove('hidden')}
function pause(){if(state==='playing'){state='paused';els.pause.classList.remove('hidden')}}function resume(){if(state==='paused'){state='playing';els.pause.classList.add('hidden')}}
$('playBtn').addEventListener('click',start);$('againBtn').addEventListener('click',start);$('restartPause').addEventListener('click',start);$('pauseBtn').addEventListener('click',()=>state==='paused'?resume():pause());$('resumeBtn').addEventListener('click',resume);$('soundBtn').addEventListener('click',()=>{sound=!sound;$('soundBtn').textContent=sound?'♫':'♪';$('soundBtn').setAttribute('aria-label',sound?'Silenciar sonido':'Activar sonido');if(sound)blip('step')});
const directions={ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1],ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0]};window.addEventListener('keydown',e=>{if(e.key==='Escape'||e.key==='p'||e.key==='P'){e.preventDefault();if(state==='playing')pause();else if(state==='paused')resume();return}const v=directions[e.key];if(v){e.preventDefault();if(!e.repeat)move(v[0],v[1])}});
let holdTimer=null;document.querySelectorAll('[data-dir]').forEach(btn=>{const act=e=>{e.preventDefault();const [dx,dy]=btn.dataset.dir==='up'?[0,-1]:btn.dataset.dir==='down'?[0,1]:btn.dataset.dir==='left'?[-1,0]:[1,0];move(dx,dy);clearInterval(holdTimer);holdTimer=setInterval(()=>move(dx,dy),170)};btn.addEventListener('pointerdown',act);for(const ev of ['pointerup','pointercancel','pointerleave'])btn.addEventListener(ev,()=>clearInterval(holdTimer))});
let touch=null;canvas.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY,id:e.pointerId};try{canvas.setPointerCapture(e.pointerId)}catch{}});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.hypot(dx,dy)>18){if(Math.abs(dx)>Math.abs(dy))move(Math.sign(dx),0);else move(0,Math.sign(dy))}touch=null});
let lastTouch=0;document.addEventListener('touchend',e=>{if(e.target.closest('.panel'))return;const now=Date.now();if(now-lastTouch<300)e.preventDefault();lastTouch=now},{passive:false});window.addEventListener('resize',resize);window.addEventListener('orientationchange',()=>setTimeout(resize,150));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
resize();makeMaze();updateHud();requestAnimationFrame(frame);
})();
